### ISSUE TITLE
How to get model structure after conversion?   Or how can I find out which operators are converted in my model？

### ISSUE THREAD

**Issue by yezifeiafei** [NVIDIA-AI-IOT/torch2trt#102]
How to get model structure after conversion?   Or how can I find out which operators are converted in my model？

I can print original model’s parameters with its name by
```
for name, param in model.named_parameters():
    print(name)
```
	
But TRTModule().named_parameters() return none.

Any one has any suggestion?

**Comment by yezifeiafei** [comment]
Hi jaybdub,

Thanks for your immediate reply！
 
I have a pytorch model and try to use torch2trt for acceleration. I want to know which operators in my model are supported by torch2trt and successfully converted to tensorrt operators. Just as I convert a tensorflow model using tf-trt ([link](https://github.com/tensorflow/tensorrt)), I can get a list of node name from graph definition, where I find some operators don’t change at all and some others are replaced by tensorrt engine operators.
 
Meantime, some blogs tried to convert a pytorch model to onnx format first and create a tensorrt engine from the onnx file. Is there any difference in efficiency between these two implementations?

**Comment by jaybdub** [comment]
Hi yezifeiafei,

Unlike TF-TRT, torch2trt is currently focused on converting models entirely to native TensorRT.  Generally this is desired for embedded applications (which was our initial focus).  

The module returned by ``torch2trt``  is using only the TensorRT runtime for execution.

So if you come across a layer that is not supported, please raise an issue and let us know.  Often it is straightforward to implement a new converter so the model can run in native TensorRT.  In some scenarios, this is more difficult.  (ie: [interpolate](https://github.com/NVIDIA-AI-IOT/torch2trt/tree/master/torch2trt/converters/interpolate) which required a plugin).

Please let me know if this helps or you have any additional questions.

Best,
John
