### ISSUE TITLE
could u pls add 'upsample' ?

### ISSUE THREAD

**Issue by sn1ff1918** [NVIDIA-AI-IOT/torch2trt#108]
Thank you very much for your kind help.

**Comment by jaybdub** [comment]
Hi sn1ff1918,

Thanks for reaching out!  I will look into adding support for upsample.  In the meantime, you may be able to replace calls to upsample with interpolate. This is supported if you build torch2trt with plugin support.

Best,
John

**Comment by sn1ff1918** [comment]
> Hi sn1ff1918,
> 
> Thanks for reaching out! I will look into adding support for upsample. In the meantime, you may be able to replace calls to upsample with interpolate. This is supported if you build torch2trt with plugin support.
> 
> Best,
> John

Thank u so much for ur quick reply. Looking forward to adding support for upsample.
