### ISSUE TITLE
Interpolate failure

### ISSUE THREAD

**Issue by tetelias** [NVIDIA-AI-IOT/torch2trt#119]
Install completed without a problem and I can see torch.nn.functional.interpolate among keys, but when I try to use it, I run into:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-b3021d16f99a> in <module>
----> 1 model_trt = torch2trt(model, [x])

/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py in torch2trt(module, inputs, input_names, output_names, log_level, max_batch_size, fp16_mode, max_workspace_size, strict_type_constraints)
    348         ctx.add_inputs(inputs, input_names)
    349 
--> 350         outputs = module(*inputs)
    351 
    352         if not isinstance(outputs, tuple) and not isinstance(outputs, list):

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

<ipython-input-1-03a2fbee9c09> in forward(self, x)
    304         e5 = self.encode5(e4)  # 512, 16, 16
    305 
--> 306         f = self.center(e5)  # 256, 8, 8
    307 
    308         d5 = self.decode5(f, e5)  # 64, 16, 16

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py in forward(self, input)
     90     def forward(self, input):
     91         for module in self._modules.values():
---> 92             input = module(input)
     93         return input
     94 

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

<ipython-input-1-03a2fbee9c09> in forward(self, x)
     32         # x shape: 512, 16, 16
     33         x_glob = self.glob(x)  # 256, 1, 1
---> 34         x_glob = F.interpolate(x_glob, scale_factor=16, mode='bilinear', align_corners=True)  # 256, 16, 16
     35 
     36         d2 = self.down2_1(x)  # 512, 8, 8

/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py in wrapper(*args, **kwargs)
    193 
    194             #print('%s : %s' % (method.__qualname__, converter.__name__))
--> 195             converter(ctx)
    196 
    197             # convert to None so conversion will fail for unsupported layers

/opt/conda/lib/python3.6/site-packages/torch2trt/converters/interpolate/interpolate.py in convert_interpolate(ctx)
     33     size = list(output.shape[2:])
     34 
---> 35     plugin = get_interpolate_plugin(size=size, mode=mode, align_corners=align_corners)
     36 
     37     layer = ctx.network.add_plugin_v2([input_trt], plugin)

/opt/conda/lib/python3.6/site-packages/torch2trt/converters/interpolate/interpolate.py in get_interpolate_plugin(size, mode, align_corners)
      9     PLUGIN_NAME = 'interpolate'
     10     registry = trt.get_plugin_registry()
---> 11     creator = [c for c in registry.plugin_creator_list if c.name == PLUGIN_NAME and c.plugin_namespace == 'torch2trt'][0]
     12     message = interpolate_Message(size=size, mode=mode, align_corners=align_corners)
     13     return creator.deserialize_plugin(PLUGIN_NAME, message.SerializeToString())

IndexError: list index out of range

Any ideas?

**Comment by saulzar** [comment]
The plugin is failing to load silently then when it tries to find it it doesn't exist - I'm also struggling to make this work. As far as I can tell the problem (for me) is how to build correctly in a conda sandbox.

To find the real cause of the problem:
```
Hi saulzar,

Could you try commenting out this try-catch statement and repeating?

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/__init__.py#L17

This way we may be able to see the error that occurs when an attempt is made to load the plugin library.

Best,
John
```

**Comment by ppaanngggg** [comment]
The same problem.

I can't find `libtorch2trt.so` in my tensor2trt package dir.

**Comment by ppaanngggg** [comment]
> The same problem.
> 
> I can't find `libtorch2trt.so` in my tensor2trt package dir.

I had compiled `libtorch2trt.so` now. But when I run `ctypes.CDLL`, it throws error `OSError: /usr/lib/python3.7/site-packages/torch2trt/libtorch2trt.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev`

I should install protobuf. I use manjaro as OS.

**Comment by ppaanngggg** [comment]
> > The same problem.
> > I can't find `libtorch2trt.so` in my tensor2trt package dir.
> 
> I had compiled `libtorch2trt.so` now. But when I run `ctypes.CDLL`, it throws error `OSError: /usr/lib/python3.7/site-packages/torch2trt/libtorch2trt.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev`
> 
> I should install protobuf. I use manjaro as OS.

I have solved it.

I compile install latest protobuf and then reinstall tensor2trt.

**Comment by tetelias** [comment]
Could you be a bit more specific: 
according to readme we need to run "sudo apt-get install libprotobuf* protobuf-compiler ninja-build". From "compile install latest protobuf" I gather that we can drop "libprotobuf* protobuf-compiler" from the command mentioned above, and instead install protobuf from source, right?
Also does it matter which version of protobuf, or any 3.x.x would do?

**Comment by ppaanngggg** [comment]
I think you should check whether `libtorch2trt.so` exists in your torch2trt package folder. If not, you should reinstall torch2trt by set more cmdline params to compile it.

**Comment by jasonliu19** [comment]
Hi, I'm also having this issue. I've compiled and installed protobuf from source, but the library doesn't seem be properly linking in the build step.

**Comment by peasant98** [comment]
I also had this issue; for me, the issue was with Pytorch (that I had installed via pip). So, I installed it from source. I read that the Libtorch binaries should compiled with flag _GLIBCXX_USE_CXX11_ABI = 1, so I did that. 

Also, in the rule cxx in `build.py`, instead of `g++`, I did `g++ -D_GLIBCXX_USE_CXX11_ABI=1`

**Comment by jasonliu19** [comment]
I ended up solving this issue by compiling PyTorch from source with g++7. Didn't have to touch any additional settings during the compilation of both PyTorch and `build.py`

**Comment by xieydd** [comment]
I solve the problem. i make a summary:
```
# first you can 
ldd -r /usr/local/lib/python3.6/dist-packages/torch2trt/libtorch2trt.so # if you see protobuf error
Download https://github.com/protocolbuffers/protobuf/releases 3.6.1 c++ compile
cd torch2trt
sudo python setup.py clean
python setup.py install --plugin --cuda-dir=/usr/local/cuda-10.1/ --torch-dir=/usr/local/lib/python3.6/dist-packages/torch --trt-lib-dir=/usr/lib/x86_64-linux-gnu/ --trt-inc-dir=/usr/include/x86_64-linux-gnu/
```

**Comment by ouguozhen** [comment]
@xieydd hi, when i run python setup.py install --plugin --cuda-dir=/usr/local/cuda-10.1/ --torch-dir=/usr/local/lib/python3.6/dist-packages/torch --trt-lib-dir=/usr/lib/x86_64-linux-gnu/ --trt-inc-dir=/usr/include/x86_64-linux-gnu/, and i got the error:
![image](https://user-images.githubusercontent.com/14123404/70691186-6c6dfe80-1cf3-11ea-95a5-7eb9992a296c.png)
i have complied protobuf-3.6.1 already, what's the problem? holpful for your reply

**Comment by tianmaliuixing** [comment]
> @xieydd hi, when i run python setup.py install --plugin --cuda-dir=/usr/local/cuda-10.1/ --torch-dir=/usr/local/lib/python3.6/dist-packages/torch --trt-lib-dir=/usr/lib/x86_64-linux-gnu/ --trt-inc-dir=/usr/include/x86_64-linux-gnu/, and i got the error:
> ![image](https://user-images.githubusercontent.com/14123404/70691186-6c6dfe80-1cf3-11ea-95a5-7eb9992a296c.png)
> i have complied protobuf-3.6.1 already, what's the problem? holpful for your reply

I have met same problem, do u have any solution?
