### ISSUE TITLE
ValueError: negative shift count

### ISSUE THREAD

**Issue by olelukoje** [NVIDIA-AI-IOT/torch2trt#126]
I'm trying to convert a detection model with torch.nn.Softmax(dim=-1) layer, but get this error:
```
"torch2trt/converters/softmax.py", line 17, in convert_softmax
    axes = 1 << (dim - 1)
ValueError: negative shift count
```
Is there any way to fix it?

**Comment by ziweizhan** [comment]
I have the same problem. Has your problem been solved？

**Comment by ziweizhan** [comment]
You can solve this problem by setting dim = 1.
