### ISSUE TITLE
dimensions mismatched at input 1 at index 1. Input 0 shape: [1,256,90,120], Input 1 shape: [1,512,90,120]

### ISSUE THREAD

**Issue by marooncn** [NVIDIA-AI-IOT/torch2trt#128]
Hi, when I convert [BiSeNet](https://github.com/ooooverflow/BiSeNet) model to trt, 

```
from model.build_BiSeNet import BiSeNet
model = BiSeNet(12, 'resnet18').cuda()
model.module.load_state_dict(torch.load('best_dice_loss_miou_0.655.pth'))
x = torch.ones((1, 3, 720, 960)).cuda()
model_trt = torch2trt(model, [x])
```

here comes an error:

> [TensorRT] ERROR: (Unnamed Layer* 88) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at input 1 at index 1. Input 0 shape: [1,256,90,120], Input 1 shape: [1,512,90,120]
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/segmentation/laomuji/BiSeNet/torch2trt/torch2trt/torch2trt.py", line 347, in torch2trt
>     outputs = module(*inputs)
>   File "/home/segmentation/miniconda3/envs/dl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/segmentation/laomuji/BiSeNet/model/build_BiSeNet.py", line 157, in forward
>     result = self.feature_fusion_module(sx, cx)
>   File "/home/segmentation/miniconda3/envs/dl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/segmentation/laomuji/BiSeNet/model/build_BiSeNet.py", line 69, in forward
>     x = torch.cat((input_1, input_2), dim=1)
>   File "/home/segmentation/laomuji/BiSeNet/torch2trt/torch2trt/torch2trt.py", line 198, in wrapper
>     converter(ctx)
>   File "/home/segmentation/laomuji/BiSeNet/torch2trt/torch2trt/converters/cat.py", line 14, in convert_cat
>     trt_inputs = [trt_(ctx.network, i) for i in inputs]
>   File "/home/segmentation/laomuji/BiSeNet/torch2trt/torch2trt/converters/cat.py", line 14, in <listcomp>
>     trt_inputs = [trt_(ctx.network, i) for i in inputs]
>   File "/home/segmentation/laomuji/BiSeNet/torch2trt/torch2trt/torch2trt.py", line 115, in trt_
>     num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
> ValueError: __len__() should return >= 0

What's wrong with it?

**Comment by marooncn** [comment]
I just squeeze the input, and _convert_cat_ can work now, but here comes another error:

> Traceback (most recent call last):
>     model_trt = torch2trt(model, [x])
>   File "/home/segmentation/laomuji/BiSeNet/torch2trt/torch2trt/torch2trt.py", line 351, in torch2trt
>     ctx.mark_outputs(outputs, output_names)
>   File "/home/segmentation/laomuji/BiSeNet/torch2trt/torch2trt/torch2trt.py", line 272, in mark_outputs
>     trt_tensor = torch_output._trt
> AttributeError: 'Tensor' object has no attribute '_trt'

**Comment by marooncn** [comment]
I just do a little change:
```
model = BiSeNet(12, 'resnet18').cuda().half().eval()
x = torch.ones((1, 3, 720, 960)).cuda().half()
model_trt = torch2trt(model, [x], fp16_mode=True)
```
and the model can work now, and it can print out the result, but there is still an error:
> [TensorRT] ERROR: INVALID_ARGUMENT: Can not find binding of given name

Does the error matter?

**Comment by SrivastavaKshitij** [comment]
Same issue here as well. I have a model that is giving the same error. However, I am unable to reproduce the error !!

```
all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at input 1 at index 1. Input 0 shape: [1,256,228,480], Input 1 shape: [1,64,228,480]
Traceback (most recent call last):
  File "inference_modified.py", line 283, in <module>
    main()
  File "inference_modified.py", line 279, in main
    trt_fp16=args.trt_fp16)
  File "inference_modified.py", line 197, in run_inference
    model = torch2trt(model,[input_t])
  File "/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 347, in torch2trt
    outputs = module(*inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/work/pytorch_segmentation_model/model/resnet_ssis_model_modified.py", line 134, in forward
    return self.fwd_model(volume)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/work/pytorch_segmentation_model/model/resnet_ssis_model_modified.py", line 111, in forward
    volume_ss_cat = self.refine(volume_ss_cat)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/work/pytorch_segmentation_model/model/resnet_atoms_modified.py", line 97, in forward
    out = self.conv1(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 198, in wrapper
    converter(ctx)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt/converters/Conv2d.py", line 9, in convert_Conv2d
    input_trt = trt_(ctx.network, input)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 115, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
ValueError: __len__() should return >= 0

```

**Comment by jaybdub** [comment]
Hi @SrivastavaKshitij ,

Does this error occur if you build torch2trt with plugins?

Best,
John

**Comment by SrivastavaKshitij** [comment]
@jaybdub : thanks for the quick response:

Two things:

1. Yes, the error goes away for the repro script. 
2. Something strange has happened with our internal model.

Earlier I was getting an error:
```
[TensorRT] ERROR: (Unnamed Layer* 345) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at input 1 at index 1. Input 0 shape: [1,256,228,480], Input 1 shape: [1,64,228,480]
```

However, after i build torch2trt with plugin support, it gives me a different error (probably the right one):

```
[TensorRT] ERROR: (Unnamed Layer* 345) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at input 1 at index 1. Input 0 shape: [1,228,480,0], Input 1 shape: [1,64,228,480]

```

Interesting thing is that I printed the tensor sizes just before they were fed into the `concat` op (and after the upsampling op) in the forward pass of pytorch model def and the sizes are:

```
torch.Size([1, 256, 228, 480]) torch.Size([1, 64, 228, 480])
```
Somehow , `[1, 256, 228, 480]` becomes ` [1,228,480,0]`. 

I dont know how to go about this problem.

**Comment by SrivastavaKshitij** [comment]
Hi @jaybdub : Thanks. it worked. !

**Comment by satabios** [comment]
> I just squeeze the input, and _convert_cat_ can work now, but here comes another error:
> 
> > Traceback (most recent call last):
> > model_trt = torch2trt(model, [x])
> > File "/home/segmentation/laomuji/BiSeNet/torch2trt/torch2trt/torch2trt.py", line 351, in torch2trt
> > ctx.mark_outputs(outputs, output_names)
> > File "/home/segmentation/laomuji/BiSeNet/torch2trt/torch2trt/torch2trt.py", line 272, in mark_outputs
> > trt_tensor = torch_output._trt
> > AttributeError: 'Tensor' object has no attribute '_trt'

How did you solve " ValueError: __len__() should return >= 0", Could you explain it in detail?
I'm attaching my outputs for your reference: [https://indianinstituteofscience-my.sharepoint.com/:f:/g/personal/sathyaprakas_iisc_ac_in/EhROPfteUk9ArcI_7ycC3D8BSusZSIwrFQ4TycV0RQhKjg?e=AEuR2s](url)

**Comment by xieydd** [comment]
@jaybdub I also meet the problem `[TensorRT] ERROR: INVALID_ARGUMENT: Can not find binding of given name`, when  i build  `trt_net = torch2trt(net, inputs, fp16_mode=fp16,max_workspace_size=1 << 25)` no error. But when i want get the output `preds_trt = trt_net(image)` will cause a error.
