### ISSUE TITLE
[Enhancement] Verbose Conversion Option

### ISSUE THREAD

**Issue by SrivastavaKshitij** [NVIDIA-AI-IOT/torch2trt#130]
Hi @jaybdub 

Is it possible to have a verbose option when torch2trt converts layers into trt format. This way we can see which layers were not converted to trt op (missing plugin etc.) and will be very helpful for debugging. Also, @Is there any other way to check which layers were not converted ?

thanks

**Comment by alsrgv** [comment]
@SrivastavaKshitij, I was just doing this kind of debugging and found it helpful to dump layer-by-layer progress and then compare with the model structure.  [Here](https://github.com/maka-autonomous-robotic-systems/torch2trt/commit/22d1a42bbc99f29d7e6324632eb5763b87ad71de#diff-49b77ee88cfa5a65319341980068d292R202) is an example enhancement to trace the model structure.  It's super hacky at this point, if somebody has any idea how to make this more generic that'd be sweet :-)

**Comment by SrivastavaKshitij** [comment]
@alsrgv : Hey thanks for link. So we are collaborating again :-) . Let me look at the link and yeah we can even create a pull request for this feature.

**Comment by jaybdub** [comment]
Hi All,

Thanks for reaching out.

Currently torch2trt is not explicitly aware of unsupported operations.  This is something I'm considering how to best address.  Perhaps debugging utilities like

1.  Logging called converters
    1.  Method name
    2.  Current module scope (ie ``MyModel.ModuleA.ModuleB``)
2.  Logging calls where TensorRT constants are added. 

FYI, not sure if this helps here but I've recently added a utility to visualize the constructed TensorRT network with graphviz

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/utils.py#L4

You can access the network after optimization

```python
model_trt = torch2trt(model, [data], keep_network=True)
```

And visualize it by calling

```python
from torch2trt.utils import trt_network_to_dot_graph

dot = trt_network_to_dot_graph(model.network)
dot.render('model_network.gv', view=True)  
```

This will generate a PDF ``model_network.gv.pdf``.

Please let me know if this helps, or if you have any feedback.

Best,
John

**Comment by SrivastavaKshitij** [comment]
Hi @jaybdub : Its a good visualizing tool. however, when the model fails , the program just exists and the visualizer is not called. So again, in a deep network, I wont know which layer was not converted. 

I have played for torch2trt for a while to understand that the below mentioned error appears because one of the layers in my network was not converted properly but I have to dig deeper to figure out which one. 

```
/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:2479: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
<class 'torch.Tensor'> <class 'torch.Tensor'> torch.Size([1, 256, 228, 480]) torch.Size([1, 64, 228, 480])
[TensorRT] ERROR: (Unnamed Layer* 345) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at input 1 at index 1. Input 0 shape: [1,64,228,480], Input 1 shape: [1,228,480,-4057488]
Traceback (most recent call last):
  File "inference.py", line 286, in <module>
    main()
  File "inference.py", line 282, in main
    trt_fp16=args.trt_fp16)
  File "inference.py", line 197, in run_inference
    model = torch2trt(model,[input_t],keep_network=True)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 360, in torch2trt
    outputs = module(*inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/work/model/resnet_ssis_model_modified.py", line 134, in forward
    return self.fwd_model(volume)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/work/model/resnet_ssis_model_modified.py", line 111, in forward
    volume_ss_cat = self.refine(volume_ss_cat)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/work/model/resnet_atoms_modified.py", line 97, in forward
    out = self.conv1(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 198, in wrapper
    converter(ctx)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt/converters/Conv2d.py", line 9, in convert_Conv2d
    input_trt = trt_(ctx.network, input)
  File "/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 115, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
ValueError: __len__() should return >= 0

```

**Comment by SrivastavaKshitij** [comment]
We need something what @alsrgv has shown. So that as the conversion is happening, we know what types of layers are being skipped.

**Comment by jaybdub** [comment]
Hi All,

One solution that I've come up with so far is to create a large list of known torch methods.  If these methods are encountered, a warning is thrown if no converter is found. 

Currently this feature is in staged in this pull request

https://github.com/NVIDIA-AI-IOT/torch2trt/pull/138

This approach has it's limitations, but I think should be helpful for now. 

Please try this branch out and let me know if it is sufficient for your use cases, or if you have any feedback.

Best,
John

**Comment by alsrgv** [comment]
@jaybdub, thanks for the enhancement!  I think it will help in certain situations, but there are many other situations where it won't work.  One example is models using tuples or dicts, like [this](https://github.com/pytorch/vision/blob/master/torchvision/models/segmentation/_utils.py#L20).

It seems that debug output of converted layers + errors for explicitly unsupported layers could complement each other.

**Comment by SherlockHua1995** [comment]
> Hi @jaybdub : Its a good visualizing tool. however, when the model fails , the program just exists and the visualizer is not called. So again, in a deep network, I wont know which layer was not converted.
> 
> I have played for torch2trt for a while to understand that the below mentioned error appears because one of the layers in my network was not converted properly but I have to dig deeper to figure out which one.
> 
> ```
> /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:2479: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
>   "See the documentation of nn.Upsample for details.".format(mode))
> <class 'torch.Tensor'> <class 'torch.Tensor'> torch.Size([1, 256, 228, 480]) torch.Size([1, 64, 228, 480])
> [TensorRT] ERROR: (Unnamed Layer* 345) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at input 1 at index 1. Input 0 shape: [1,64,228,480], Input 1 shape: [1,228,480,-4057488]
> Traceback (most recent call last):
>   File "inference.py", line 286, in <module>
>     main()
>   File "inference.py", line 282, in main
>     trt_fp16=args.trt_fp16)
>   File "inference.py", line 197, in run_inference
>     model = torch2trt(model,[input_t],keep_network=True)
>   File "/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 360, in torch2trt
>     outputs = module(*inputs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/workspace/work/model/resnet_ssis_model_modified.py", line 134, in forward
>     return self.fwd_model(volume)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/workspace/work/model/resnet_ssis_model_modified.py", line 111, in forward
>     volume_ss_cat = self.refine(volume_ss_cat)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/workspace/work/model/resnet_atoms_modified.py", line 97, in forward
>     out = self.conv1(x)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 198, in wrapper
>     converter(ctx)
>   File "/opt/conda/lib/python3.6/site-packages/torch2trt/converters/Conv2d.py", line 9, in convert_Conv2d
>     input_trt = trt_(ctx.network, input)
>   File "/opt/conda/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 115, in trt_
>     num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
> ValueError: __len__() should return >= 0
> ```

Hello, I met the same error as yours.Have you solved this?

**Comment by SrivastavaKshitij** [comment]
@SherlockHua1995 : you are using a layer that was not converted to trt layer before concat op kicked in.

**Comment by SherlockHua1995** [comment]
Thanks for your reply.
How to distinguish which layer is not supported for trt conversion?
Or which layer is not converted successfully?
Thanks.

**Comment by SrivastavaKshitij** [comment]
when u r converting the model, it should show a list of unsupported ops encountered or just open `converters` folder under torch2trt and manually see

**Comment by SherlockHua1995** [comment]
Thanks.
I've check the converters in /torch2trt/converters and found the {add} operation instead of {concatenation}.

**Comment by SrivastavaKshitij** [comment]
there is concatenation operation: `https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/converters/cat.py`
