### ISSUE TITLE
C++ API?

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA-AI-IOT/torch2trt#132]
Hi, I got 2 questions:

1. What's this trt different with tensorrt engine? (which commonly used when convert onnx model to tensorrt engine)
2. How using C++ api?

**Comment by jaybdub** [comment]
Hi jinfagang,

Thanks for reaching out!

The primary difference is that

1.  This repository converts directly from PyTorch -> TensorRT (no intermediate file representation)

2.   This repository provides utilities, like ``TRTModule``, which behaves similar to a PyTorch module.  So you can rapidly prototype your application / test against TensorRT.

Under the hood, the result is the same, an optimized TensorRT _engine_.  You can use this engine in C++ by serializing it.

For example, assuming you have a working ``TRTModule`` returned from ``torch2trt``, you can save the serialized engine by calling

```python
with open('model.engine', 'wb') as f:
    f.write(model_trt.engine)
```

This can be used like any other serialized TensorRT engine in C++.

Best,
John

**Comment by jinfagang** [comment]
@jaybdub  Does it supported some large models such as MaskRCNN? If not, how many ops estimated to be lack of？

**Comment by xsacha** [comment]
From the docs, engines are optimised from the device they are created on. Hence, we can't actually export this model for inference on any device.
Is there a way to export/serialise a more generic version that gets optimised later?

**Comment by attashe** [comment]
I think you need add serialize() function

`
with open('model.engine', 'wb') as f:
    f.write(model_trt.engine.serialize())
`

**Comment by attashe** [comment]
@jaybdub 
Maybe include code for this question in readme.md? 
I think it useful information.

**Comment by MaratZakirov** [comment]
Could please anyone provide selfcontatning example of serializing and loading in C++ trt engne
