### ISSUE TITLE
Big error after conversion

### ISSUE THREAD

**Issue by marooncn** [NVIDIA-AI-IOT/torch2trt#134]
Hi, I convert pretrained [BiseNet](https://github.com/ooooverflow/BiSeNet/blob/master/model/build_BiSeNet.py) model to tensorrt.
```
from model.build_BiSeNet import BiSeNet
model = BiSeNet(12, 'resnet18').cuda().half()
model.module.load_state_dict(torch.load('best_dice_loss_miou_0.655.pth'))
x = torch.ones((1, 3, 720, 960)).cuda().half()
model_trt = torch2trt(model, [x], fp16_model=True)
y = model(x)
y_trt = model_trt(x)
print(torch.max(torch.abs(y - y_trt)))
```
the result is reasonable

> 0.015600

But then I input image data to do comparison, the result is quite bad
> 51.218750

and I pay attention that when I use this tested image to generate  _model_trt_, then the result is also good, but only good for itself.
I print out the result, finding that the result of _model_trt_ is always the same whatever the input is. 
It's so weird and is there something I don't make clear?

**Comment by jaybdub** [comment]
Hi marooncn,

It seems like this model should fail to convert as-is, but is succeeding for some reason.

I have a guess to why this is, but I will need to look into it further.

Hope to get back to you soon.

Best,
John

**Comment by JarveeLee** [comment]
I have the same error , when load trained state dict then feed new input .

**Comment by JarveeLee** [comment]
I realize that the error is the same as torch.nn.functional.interpolate(scale_factor = 2) not correctly install , but I am confused around the long discussion in #20 , #17  , did as their words still wrong , what is the clear pipline to fix this bug ... ?

**Comment by jaybdub** [comment]
Hi @marooncn,

By calling ``model = model.eval()`` before converting with ``torch2trt`` I was able to convert the model that you shared.

The results seem consistent with PyTorch.

Please let me know if this works for you.

Best,
John

**Comment by marooncn** [comment]
Hi, @jaybdub 
It can't work for me, actually in my test script, I have called .eval() to do evaluation. My test scripts like this:
```
import torch
from torch2trt.torch2trt import *
from torch2trt import tensorrt_converter

@tensorrt_converter('torch.cat')
def convert_cat(ctx):
    inputs = ctx.method_args[0]
    #print(ctx.method_kwargs)
    if 'dim' in ctx.method_kwargs:
        dim = ctx.method_kwargs['dim']
    else:
        dim = ctx.method_args[1] 

    #print(dim)
    output = ctx.method_return
    trt_inputs = [trt_(ctx.network, i.squeeze(0)) for i in inputs]

    layer = ctx.network.add_concatenation(inputs=trt_inputs) 
    layer.axis = dim - 1
    output._trt = layer.get_output(0)

from model.build_BiSeNet import BiSeNet
model = BiSeNet(12, 'resnet18').cuda().half().eval()
model.load_state_dict(torch.load('./checkpoints/best_dice_loss_miou_0.655.pth'))
x = torch.ones((1, 3, 720, 960)).cuda().half()
model_trt = torch2trt(model, [x], fp16_mode=True)

x = torch.randn((1, 3, 720, 960)).cuda().half()
y = model(x)
y_trt = model_trt(x)
print('max error: %f' % float(torch.max(torch.abs(y - y_trt))))
```

You can run this script to check the max error, it's 47.68 for me.

**Comment by jaybdub** [comment]
Do you also witness this error with the default “torch.cat” converter?  trt_ method will actually create a constant if the TensorRT attribute is not found.  So I would guess by calling i.squeeze, it’s actually creating a constant rather than using the computed Tensor.

Best,
John

**Comment by marooncn** [comment]
Hi, @jaybdub 
I make clear why it is. But if I don't  override _convert_cat(ctx)_ there will be another error because of the size:

> ValueError: __len__() should return >= 0

Is there a method to avoid this error by not calling i.squeeze?

**Comment by marooncn** [comment]
Hi, @jaybdub
Pay attention to you attachment at #130, I try out the new version, it still can't work.

**Comment by ShangxuanWu** [comment]
> I have the same error , when load trained state dict then feed new input . The error will be quite large. If do not load weight , just use init weight error will still be small.
> 
> And I find that this error only happen if a model has torch.nn.functional.interpolate(scale_factor = 2). I compare the encoder's feature , that is still the same , but features from decoder during upsample changes quite a lot .

I met the exact same issue. When I was not loading the pretrained weights, the TRT model and raw model was outputting very similar results (~120 pSNR). But after loading pretrained weights, the inference result was very different (~30 pSNR). We didn't use `interpolate` layer, but we used `nn.Upsample` layer. Any idea what's happening?
