### ISSUE TITLE
non-leaf tensors

### ISSUE THREAD

**Issue by satabios** [NVIDIA-AI-IOT/torch2trt#141]
I'm trying to compile a mobilenet PyTorch variant to TensorRT. I'm attaching the [https://drive.google.com/drive/folders/158BjwnsDb5P6eUOuEl0BvCQH1_7dt9a6?usp=sharing](url) which contains the code and the weight files. I'm testing this on NVIDIA TX2.
I was successfully able to compile ResNet, but however when I try to compile my model it throws and error:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-52-7dd60ac48df0> in <module>
     11 
     12 
---> 13 model_trt = torch2trt(model, [data], fp16_mode=True)

/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py in torch2trt(module, inputs, input_names, output_names, log_level, max_batch_size, fp16_mode, max_workspace_size, strict_type_constraints, keep_network)
    361         ctx.add_inputs(inputs, input_names)
    362 
--> 363         outputs = module(*inputs)
    364 
    365         if not isinstance(outputs, tuple) and not isinstance(outputs, list):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

<ipython-input-50-6659e612bc7d> in forward(self, x)
    160 
    161         y3c = torch.cat((x3,y4),1)
--> 162         y3i = F.relu(self.atrous3_bn1(self.atrous3_conv1(y3c)))
    163         y3a = torch.cat((y3i,
    164                        F.relu(self.atrous3_bn3(self.atrous3_conv3(y3i))),

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py in wrapper(*args, **kwargs)
    199 
    200 #             print('%s' % (converter.__name__,))
--> 201             converter['converter'](ctx)
    202 
    203             # convert to None so conversion will fail for unsupported layers

/usr/local/lib/python3.6/dist-packages/torch2trt/converters/Conv2d.py in convert_Conv2d(ctx)
      7     module = ctx.method_args[0]
      8     input = ctx.method_args[1]
----> 9     input_trt = trt_(ctx.network, input)
     10     output = ctx.method_return
     11 

/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py in trt_(network, *tensors)
    113                 num_dim = len(t.shape) # don't exclude batch for constants
    114             else:
--> 115                 num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
    116             if num_dim > broadcast_num_dim:
    117                 broadcast_num_dim = num_dim

ValueError: __len__() should return >= 0
`
Any guidance is appreciated. Thanks in advance.

**Comment by rudy3742** [comment]
same problem here

File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 201, in wrapper
    converter['converter'](ctx)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/converters/relu.py", line 11, in convert_relu
    convert_ReLU(ctx)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/converters/ReLU.py", line 7, in convert_ReLU
    input_trt = trt_(ctx.network, input)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 115, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
ValueError: __len__() should return >= 0

convert self-designed network to tensorRT, input is one-dimension tensor for numerical learning
