### ISSUE TITLE
How can you set precision? 

### ISSUE THREAD

**Issue by ryanmeasel** [NVIDIA-AI-IOT/torch2trt#142]
Is there a way to specify precision (FP32, FP16 or INT8) of the conversion?

**Comment by jaybdub** [comment]
Hi ryanmeasel,

Currently yes for FP16.  You can allow the TensorRT optimization process to use FP16 layers by passing ``fp16_mode = True``

```python
model_trt = torch2trt(model, [data], fp16_mode=True)
```

The optimizer will automatically select FP16 or FP32 layers based off of performance.  The input and output data types will remain the same.  They will match the type of ``data``.  

Please let me know if this helps or you have any other questions.

Best,
John

**Comment by jaybdub** [comment]
Hi ryanmeasel,

Currently yes for FP16.  You can allow the TensorRT optimization process to use FP16 layers by passing ``fp16_mode = True``

```python
model_trt = torch2trt(model, [data], fp16_mode=True)
```

The optimizer will automatically select FP16 or FP32 layers based off of performance.  The input and output data types will remain the same.  They will match the type of ``data``.  

Please let me know if this helps or you have any other questions.

Best,
John
