### ISSUE TITLE
adding two tensor seems to lead to a change on shape?

### ISSUE THREAD

**Issue by xinyang-go** [NVIDIA-AI-IOT/torch2trt#145]
I try to add a tensor A and a fixed tensor B together, and test it in a simple way.
```python
import torch
from torch2trt import torch2trt
class test(torch.nn.Module):
    def __init__(self):
        super(test, self).__init__()
        self.v = torch.randn([1, 3, 320, 640]).cuda()
    def forward(self, x):
        x = x + self.v
        return x
b = test()
x = torch.randn([1, 3, 320, 640]).cuda()
y = b(x)
b_trt = torch2trt(b, (x, ))
y_trt = b_trt(x)
print(y.shape)
print(y_trt.shape)
```
here is the result:
```
torch.Size([1, 3, 320, 640])
torch.Size([1, 1, 3, 320, 640])
```

**Comment by jaybdub** [comment]
Hi xinyang-go,

I believe this has to do with assumptions that torch2trt currently makes about constants.  Currently, torch2trt assumes that constants do not have a batch dimension.  

Do you witness this behavior if ``v = torch.randn([3, 320, 640])``?  In PyTorch, this will be broadcast identically to what you shared, but should work with torch2trt.

While we currently make the above assumption, perhaps there is a way we can more robustly trace if a dimension in a constant is a batch dimension to handle this scenario.

Please let me know if this helps.

Best,
John

**Comment by xinyang-go** [comment]
Thanks a lot, it does work.
