### ISSUE TITLE
Model converted on a AWS machine doesn't work on a Jeston Nano

### ISSUE THREAD

**Issue by gristovski** [NVIDIA-AI-IOT/torch2trt#149]
I tried converting models on an AWS machine, then copied them over to a Jeston Nano, to the following error:
python3: engine.cpp:1104: bool nvinfer1::rt::Engine::deserialize(const void*, std::size_t, nvinfer1::IGpuAllocator&, nvinfer1::IPluginFactory*): Assertion `size >= bsize && "Mismatch between allocated memory size and expected size of serialized engine."' failed.

Using the exact same code to do the conversion directly on the Nano resulted in a model (whose file size is ~25% less than the AWS one) that could be loaded without issues.

Does the torch2trt conversion/optimization create a model that can only be run on the hardware where it was converted? Is there a way to specify the hardware somewhere?

**Comment by xsacha** [comment]
@gristovski Yes, the engine is optimised for the hardware it was generated on which is something I am looking for a solution for as well
