### ISSUE TITLE
Unsupported method torch.arange/repeat/from_numpy/tensor?

### ISSUE THREAD

**Issue by Xianqi-Zhang** [NVIDIA-AI-IOT/torch2trt#151]
Hi,
  I try to convert my model to tensorrt, but meet the problem like this:

Warning: Encountered known unsupported method torch.arange
Warning: Encountered known unsupported method torch.Tensor.repeat

My Code:
grid_x = torch.arange(nGw).repeat((nGh, 1)).view((1, 1, nGh, nGw)).float()
grid_y = torch.arange(nGh).repeat((nGw, 1)).transpose(0,1).view((1, 1, nGh, nGw)).float()
 
So I changed it to:
grid_x = torch.from_numpy(np.tile(np.arange(nGw), nGh).reshape((nGh, -1))).view((1, 1, nGh, nGw)).float()
grid_y = torch.from_numpy(np.tile(np.arange(nGh), nGw).reshape((nGw, -1))).transpose(0, 1).view((1, 1, nGh, nGw)).float()

and meet the problem:
Warning: Encountered known unsupported method torch.from_numpy

So I changed to torch.tensor(), and meet this
Warning: Encountered known unsupported method torch.tensor

It neally drive me crazy...Do you have any ideas?

Thank you for your any reply!!!

**Comment by jaybdub** [comment]
Hi Xianqi,

Thanks for reaching out!  This has to do with the search pattern we use to suggest possible torch operations that are not supported.  Perhaps it would be better to disable these warnings by default.

That said, for your use case, are ``grid_x`` and ``grid_y`` dependent on input values to the torch module, or are they constant?  If they are constant, it may be good to place them as class members of their respective module.  This will avoid calling the methods that are not supported.

Please let me know if you have any questions.

Best,
John

**Comment by Xianqi-Zhang** [comment]
> Hi Xianqi,
> 
> Thanks for reaching out! This has to do with the search pattern we use to suggest possible torch operations that are not supported. Perhaps it would be better to disable these warnings by default.
> 
> That said, for your use case, are `grid_x` and `grid_y` dependent on input values to the torch module, or are they constant? If they are constant, it may be good to place them as class members of their respective module. This will avoid calling the methods that are not supported.
> 
> Please let me know if you have any questions.
> 
> Best,
> John

Hi, John
  Thank you for your reply!
  I think i really need a method to create tensor because grid_x and grid_y is related to the input values, and really need some repeat and arange method! Do you have any ideas?

Best,
Xianqi

**Comment by jcarre110** [comment]
Was this resolved in any way? I am having a similar issue

**Comment by yuzhiyiliu** [comment]
grid_x = torch.FloatTensor([list(range(nGw))]*nGh).view([1, 1, nGh, nGw])
grid_y = torch.FloatTensor([[x] * nGw for x in range(nGh)]).view([1, 1, nGh, nGw])
