### ISSUE TITLE
No module named 'tensorrt'

### ISSUE THREAD

**Issue by mathpopo** [NVIDIA-AI-IOT/torch2trt#152]
git clone https://github.com/NVIDIA-AI-IOT/torch2trt
cd torch2trt
sudo python setup.py install

complete this,run  ./test.sh TEST_OUTPUT.md
from .torch2trt import *
ModuleNotFoundError: No module named 'tensorrt'

**Comment by bfortuner** [comment]
Remember to download tensorrt first if you haven't, and make sure it's accessible in your python env or virtualenv

https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html

**Comment by mathpopo** [comment]
@bfortuner very thanks!it work.

**Comment by mathpopo** [comment]
it just entry python folder .python setup.py install

**Comment by colorjam** [comment]
@mathpopo Hi, I noticed that you have run `sudo python setup.py install`,  what is that mean `just entry python folder .python setup.py install`

**Comment by shoebNTU** [comment]
Sorry for the naive question. I am facing a similar error. I have successfully installed tensorrt following the steps listed here - https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html (debian installation, verified cuda version and so on, installation succeeds as per the steps listed in the guide up until grp). As far as adding path in environment is concerned, I am setting pythonpath to /usr/lib/python3.6/dist-packages (as per this link - http://www.bojankomazec.com/2019/12/how-to-install-tensorrt-python-package.html). However, the error still persists :(, when trying to import tensorrt. Thanks for your help.

**Comment by ganjbakhshali** [comment]
for me this worked:
`pip install nvidia-tensorrt`

**Comment by lqr41710085** [comment]
> for me this worked: `pip install nvidia-tensorrt`

i ran this command and got an error:  no space left on device, how can i solve this

**Comment by mxsurui** [comment]
This package can be installed as:
    ```
    $ pip install nvidia-pyindex
    $ pip install nvidia-tensorrt
    ```
