### ISSUE TITLE
contiguous() and [TensorRT] ERROR: (Unnamed Layer* 504) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis

### ISSUE THREAD

**Issue by luthfianto** [NVIDIA-AI-IOT/torch2trt#163]
Hi, when i tried to convert my model, it gives error on line:

`loc.append(loc_x.permute(0, 2, 3, 1).contiguous())`

So I decided to break it line by line to:

```python
        locp=loc_x.permute(0, 2, 3, 1)
        locpc=locp.contiguous()
        loc.append(locpc)
```

But it still errors:

```python
$ python demo.py 
/home/username/.local/lib/python3.6/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
[TensorRT] ERROR: (Unnamed Layer* 504) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis
Traceback (most recent call last):
  File "demo.py", line 135, in <module>
    dt = detect(net, path, args.thresh, -1, -1)
  File "demo.py", line 85, in detect
    net_trt = torch2trt(net, [x])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 363, in torch2trt
    outputs = module(*inputs)
  File "/home/username/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/username/cv/EXTD_Pytorch/EXTD_64.py", line 171, in forward
    locpc=locp.contiguous()
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 201, in wrapper
    converter['converter'](ctx)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/converters/identity.py", line 10, in convert_identity
    input_trt = trt_(ctx.network, input)
  File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 115, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
ValueError: __len__() should return >= 0
```

Does the contiguous causes the error? and what can I do to solve this? Thanks

This is the model and the corresponding line https://github.com/clovaai/EXTD_Pytorch/blob/master/EXTD_64.py#L176

It runs fine without TensorRT

**Comment by xieydd** [comment]
Me too.

**Comment by secretdragon** [comment]
> Hi, when i tried to convert my model, it gives error on line:
> 
> `loc.append(loc_x.permute(0, 2, 3, 1).contiguous())`
> 
> So I decided to break it line by line to:
> 
> ```python
>         locp=loc_x.permute(0, 2, 3, 1)
>         locpc=locp.contiguous()
>         loc.append(locpc)
> ```
> 
> But it still errors:
> 
> ```python
> $ python demo.py 
> /home/username/.local/lib/python3.6/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
>   "See the documentation of nn.Upsample for details.".format(mode))
> [TensorRT] ERROR: (Unnamed Layer* 504) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis
> Traceback (most recent call last):
>   File "demo.py", line 135, in <module>
>     dt = detect(net, path, args.thresh, -1, -1)
>   File "demo.py", line 85, in detect
>     net_trt = torch2trt(net, [x])
>   File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 363, in torch2trt
>     outputs = module(*inputs)
>   File "/home/username/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/username/cv/EXTD_Pytorch/EXTD_64.py", line 171, in forward
>     locpc=locp.contiguous()
>   File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 201, in wrapper
>     converter['converter'](ctx)
>   File "/usr/local/lib/python3.6/dist-packages/torch2trt/converters/identity.py", line 10, in convert_identity
>     input_trt = trt_(ctx.network, input)
>   File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 115, in trt_
>     num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
> ValueError: __len__() should return >= 0
> ```
> 
> Does the contiguous causes the error? and what can I do to solve this? Thanks
> 
> This is the model and the corresponding line https://github.com/clovaai/EXTD_Pytorch/blob/master/EXTD_64.py#L176
> 
> It runs fine without TensorRT

may be you can try transpose
