### ISSUE TITLE
num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from 

### ISSUE THREAD

**Issue by ma-siddiqui** [NVIDIA-AI-IOT/torch2trt#165]
While converting mask rcnn pytorch model into trt, i am facing below error. The weird thing is sometimes it does not occur but most of the time I receive this exception.

File "/home/muhammadsiddiqui/anaconda3/envs/panet/lib/python3.6/site-packages/torch2trt/torch2trt.py", line 115, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
ValueError: __len__() should return >= 0
Terminated

Here is code for that function:

def trt_(network, *tensors):
    """Creates missing TensorRT tensors and adds shuffle layers to make tensors broadcastable"""
    trt_tensors = [None] * len(tensors)
    
    dtype = check_torch_dtype(*tensors)
    
    # get broadcast dimension
    broadcast_num_dim = 0
    for t in tensors:
        if isinstance(t, torch.Tensor):
            if not hasattr(t, '_trt'):
                num_dim = len(t.shape) # don't exclude batch for constants
            else:
                num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
            if num_dim > broadcast_num_dim:
                broadcast_num_dim = num_dim
    ...........................
......................

**Comment by ma-siddiqui** [comment]
More digging into the issue. this call comes from:

@tensorrt_converter('torch.nn.Linear.forward')
def convert_Linear(ctx):
    module = ctx.method_args[0]
    input = ctx.method_args[1]
    input_trt = trt_(ctx.network, input)


Thanks,

**Comment by Akababa** [comment]
I found this is usually caused by the `__getitem__` converter leaving an output._trt with a corrupt shape attribute.
