### ISSUE TITLE
run python3 -m torch2trt.test --name=interpolate wrong

### ISSUE THREAD

**Issue by DocF** [NVIDIA-AI-IOT/torch2trt#166]
@jaybdub I built torch2trt successfully, but got error run `python3 -m torch2trt.test --name=interpolate`. I have tried many methods, such as rebuilding pytorch with gcc, changing the gcc version, and using the latest version of protobuf, but still not successful. Could you give me some suggestions？Thx a lot.
System: Ubuntu 18.04
torch version: 1.3.1
conda python envs: 3.6.9 （conda python envs GCC 7.3.0 ）
cuda version: 10.0.130
protobuf version: 3.10.1
tensorrt version: 6.0.1.5

**Comment by peasant98** [comment]
Hmm... maybe check out this: https://github.com/NVIDIA-AI-IOT/torch2trt/issues/119
I had a similar error, and it ultimately came down to how I compiled things. Here's my response from that issue.

> I also had this issue; for me, the issue was with Pytorch (that I had installed via pip). So, I installed it from source. I read that the Libtorch binaries should compiled with flag _GLIBCXX_USE_CXX11_ABI = 1, so I did that.
> 
> Also, in the rule cxx in `build.py`, instead of `g++`, I did `g++ -D_GLIBCXX_USE_CXX11_ABI=1`. Then I was able to have the build step (`sudo python3 setup.py install --plugins`) run fine. Also, after this, you can try the command `ldd -r libtorch2trt.so`, and if there _aren't_ undefined symbols, that is good.

Also, here is another guy's response:

> I ended up solving this issue by compiling PyTorch from source with g++7. Didn't have to touch any additional settings during the compilation of both PyTorch and `build.py`

I would try both methods.

**Comment by DocF** [comment]
Hi @peasant98 ,thank you a lot. I tried both methods that you mentioned, but it still didn't work. This problem has troubled me for several days.

**Comment by DocF** [comment]
Hi @jaybdub , it seems protobuf problem. My conda python envs have an anthor version protobuf. After I uninstalled protobuf in conda python envs, ran `python3 -m torch2trt.test --name=interpolate`  again without error, but there was **nothing** to output. What puzzles me is that the result of this command is just not output？ And I created a simple network including  interpolate operation，but got this warnning` Encountered known unsupported method torch.nn.functional.interpolate` . 
Did I install this module correctly？

**Comment by Raneee** [comment]
hello @DocF , have you solve your problem? I also meet the same problem with you. I have rebuilt pytorch1.3.1 with no torch. I built torch2trt with no error, when i run 'python -m torch2trt.test --name=interpolat', there is noting to show. when i run a model with interpolate layer, there turn out a warning: "Encountered known unsupported method torch.nn.functional.interpolate" and the results of my model was wrong. 

@peasant98  can you tell more detail about you process, Thx very much!

**Comment by peasant98** [comment]
Hi @Raneee,


I think that error might mean you didn't run `sudo python3 setup.py install --plugins`. When I ran that command, the method was known, but I had some other errors with linking. I would first try that first, then here's what I did:

I had to install Pytorch from source. I read that the Libtorch binaries should compiled with flag `_GLIBCXX_USE_CXX11_ABI = 1`,. which you should do. This later comes into play with linking files.

   Also, in the rule `cxx` in `build.py`, instead of `g++`, I did `g++ -D_GLIBCXX_USE_CXX11_ABI=1` (pretty much adding a flag). 

Then I was able to have the build step (`sudo python3 setup.py install --plugins`) run fine.

**Comment by DocF** [comment]
@Raneee I referenced issue #53  and solved the problem, you can also try it. But unlike issue #53 , I did `g++ -D_GLIBCXX_USE_CXX11_ABI=1` just like peasant98 recommended. 

You can check the problem with the following command：
        `ldd -r libtorch2trt.so`

**Comment by Raneee** [comment]
Thx all I also solve the problom!
