### ISSUE TITLE
Conversion TypeError: pybind11::init(): factory function returned nullpt

### ISSUE THREAD

**Issue by thepuremind** [NVIDIA-AI-IOT/torch2trt#167]
Hello!
When trying to convert:

`import torchvision
import torch
from torch2trt import torch2trt

model = torchvision.models.resnet18(pretrained=True).cuda().half().eval())
data = torch.randn((1, 3, 224, 224)).cuda().half()

model_trt = torch2trt(model, [data], fp16_mode=True)

An error has occurred:

`TypeError                                 Traceback (most recent call last)
<ipython-input-4-12e18b8b1f96> in <module>
      1 from torch2trt import torch2trt
      2 
----> 3 model_trt = torch2trt(model, [data], fp16_mode=True)

/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py in torch2trt(module, inputs, input_names, output_names, log_level, max_batch_size, fp16_mode, max_workspace_size, strict_type_constraints, keep_network)
    350 
    351     logger = trt.Logger(log_level)
--> 352     builder = trt.Builder(logger)
    353     network = builder.create_network()
    354 

TypeError: pybind11::init(): factory function returned nullptr`

**Comment by suruoxi** [comment]
This may be caused by mismatch of cuda version and tensorRT version.

**Comment by rawar** [comment]
I've got the same error after I installed 'nv-tensorrt-repo-ubuntu1804-cuda10.2-trt7.0.0.11-ga-20191216_1-1_amd64.deb'

**Comment by ashish10alex** [comment]
I have the same error - `TypeError: pybind11::init(): factory function returned nullptr`
My cuda version is - 11.0
Please help.
