### ISSUE TITLE
[TensorRT] ERROR: INVALID_ARGUMENT: Can not find binding of given name

### ISSUE THREAD

**Issue by xieydd** [NVIDIA-AI-IOT/torch2trt#173]
hey @marooncn @xsacha I meet the problem `[TensorRT] ERROR: INVALID_ARGUMENT: Can not find binding of given name`, when  i build  `trt_net = torch2trt(net, inputs, fp16_mode=fp16,max_workspace_size=1 << 25)` no error. But when i want get the output in 
 execute phase`preds_trt = trt_net(image)` will cause a error.

When i check the output size , it is wired:
```
def forward():
   ...
   print(output.size(), output._trt.size()) # torch.Size([50, 1, 37]) torch.float32 (1, 37)
   return output

preds_trt = trt_net(image)
print(preds_trt.size()) # torch.Size([1, 1, 37])
```
@jaybdub Can  you have a look at the error?

**Comment by jaybdub** [comment]
Hi xieydd,

Thanks for reaching out!  Are you able to share the model that you're attempting to convert?

This will help greatly in troubleshooting this issue :)

Best,
John

**Comment by xieydd** [comment]
@jaybdub I use the crnn model for text recognition, the model definition is [here](https://github.com/meijieru/crnn.pytorch); And i notice the code https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/torch2trt.py#L278 it will only  one output.

**Comment by jaybdub** [comment]
Hi xieydd,

Thanks for sharing.

I looked at the model.  It may be a bit tricky to convert this model _entirely_ to TensorRT.  One reason, is that the batch dimension is permuted.

https://github.com/meijieru/crnn.pytorch/blob/master/models/crnn.py#L74

In TensorRT, the batch is treated separately from Tensor dimensions.  Perhaps there is a way around this, (ie: by using batch_first=True property of LSTM in torch along with other modifications), but I need to investigate this further.

**For now**

It should be straightforward to convert the CNN portion of the model to run with TensorRT.  

```python
new_cnn = torch2trt(model.cnn, [data])

model.cnn = new_cnn   # for illustrative purposes, you may do this differently
```

This may offer some performance improvements.

Please let me know if this helps.  I hope to look more into RNN based models soon.

Best,
John

**Comment by xieydd** [comment]
@jaybdub I have tested the crnn, every thing  is good, i solve the lstm without batch_first=first via permute .but the output bindings only get first output.i think it is the bug of the  https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/torch2trt.py#L278.
