### ISSUE TITLE
undefined symbol: libtorch2trt.so 

### ISSUE THREAD

**Issue by ma-siddiqui** [NVIDIA-AI-IOT/torch2trt#174]
Hi,

I am facing below errors when run the following command. I believe I am missing some library. Kindly guide me. 

ldd -r ./torch2trt/libtorch2trt.so 

undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE	(./torch2trt/libtorch2trt.so)
undefined symbol: _ZN2at4cuda20setCurrentCUDAStreamENS0_10CUDAStreamE	(./torch2trt/libtorch2trt.so)
undefined symbol: _ZN2at4cuda17getStreamFromPoolEbs	(./torch2trt/libtorch2trt.so)
undefined symbol: _ZN2at7getTypeERKNS_6TensorE	(./torch2trt/libtorch2trt.so)
undefined symbol: _ZNK2at4cuda10CUDAStream6streamEv	(./torch2trt/libtorch2trt.so)
undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(./torch2trt/libtorch2trt.so)
undefined symbol: _ZN2at7getTypeENS_13TensorOptionsE	(./torch2trt/libtorch2trt.so)
undefined symbol: _ZN2at4cuda20getCurrentCUDAStreamEs	(./torch2trt/libtorch2trt.so)

**Comment by xieydd** [comment]
@ma-siddiqui you can install torch2trt add flags `--cuda-dir=/usr/local/cuda-10.1/`

**Comment by nan0755** [comment]
You can specify your `cuda` and `tensorrt` package path by setting: [build.py](https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/build.py#L28).
For example, mine is as below
```
def build(cuda_dir="/usr/local/cuda",
          torch_dir=imp.find_module('torch')[1],
          trt_inc_dir="/usr/local/include/tensorrt/include",
          trt_lib_dir="/usr/lib"):
......
```

**Comment by ma-siddiqui** [comment]
Thank you for the response. I a, still getting the errors.

undefined symbol: _ZN3c1014DeviceTypeNameB5cxx11ENS_10DeviceTypeEb	(./torch2trt/libtorch2trt.so)
undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(./torch2trt/libtorch2trt.so)
undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(./torch2trt/libtorch2trt.so)

Here us my build.py

import imp
import subprocess
import os
from string import Template

PLUGINS = [
    'interpolate',
]

BASE_FOLDER = 'torch2trt/converters'

NINJA_TEMPLATE = Template((
    "rule link\n"
    "  command = g++ -shared -o $$out $$in -L/usr/local/lib -L$torch_dir/lib -L$cuda_dir/lib64 -L$trt_lib_dir -lc10 -lc10_cuda -ltorch -lcudart -lprotobuf -lprotobuf-lite -lpthread -lnvinfer\n"
    "rule protoc\n"
    "  command = protoc $$in --cpp_out=. --python_out=.\n"
    "rule cxx\n"
    "  command = g++ -c  -fPIC $$in -I$cuda_dir/include -I$torch_dir/include -I$torch_dir/include/torch/csrc/api/include -I. -std=c++11 -I$trt_inc_dir\n"
))

PLUGIN_TEMPLATE = Template((
    "build $plugin_dir/$plugin.pb.h $plugin_dir/$plugin.pb.cc $plugin_dir/${plugin}_pb2.py: protoc $plugin_dir/$plugin.proto\n"
    "build $plugin.pb.o: cxx $plugin_dir/$plugin.pb.cc\n"
    "build $plugin.o: cxx $plugin_dir/$plugin.cpp\n"
))


def build(cuda_dir="/usr/local/cuda-10.0",#"/usr/local/cuda",
          torch_dir=imp.find_module('torch')[1],
          trt_inc_dir="/home/muhammadsiddiqui/TensorRT-6.0.1.5.Ubuntu-18.04.x86_64-gnu.cuda-10.0.cudnn7.6/TensorRT-6.0.1.5/include", #"/usr/include/aarch64-linux-gnu",
          trt_lib_dir= "/home/muhammadsiddiqui/TensorRT-6.0.1.5.Ubuntu-18.04.x86_64-gnu.cuda-10.0.cudnn7.6/TensorRT-6.0.1.5/lib"): #"/usr/lib/aarch64-linux-gnu"):

    global PLUGINS, BASE_FOLDER, NINJA_TEMPLATE, PLUGIN_TEMPLATE

    NINJA_STR = NINJA_TEMPLATE.substitute({
        'torch_dir': torch_dir,
        'cuda_dir': cuda_dir,
        'trt_inc_dir': trt_inc_dir,
        'trt_lib_dir': trt_lib_dir,
    })


    plugin_o_files = []
    for plugin in PLUGINS:
        NINJA_STR += \
            PLUGIN_TEMPLATE.substitute({
                'plugin': plugin,
                'plugin_dir': os.path.join(BASE_FOLDER, plugin),
            })
        plugin_o_files += [plugin + '.pb.o', plugin + '.o']

    NINJA_STR += Template((
        "build torch2trt/libtorch2trt.so: link $o_files\n"
    )).substitute({'o_files': ' '.join(plugin_o_files)})

    with open('build.ninja', 'w') as f:
        f.write(NINJA_STR)

    subprocess.call(['ninja'])
