### ISSUE TITLE
Interpolate plugin is not working while loading libtorch2trt.so.

### ISSUE THREAD

**Issue by nan0755** [NVIDIA-AI-IOT/torch2trt#176]
I have built torch2trt using commond: `python setup.py install --plugin`, and I notice the `libtorch2trt.so` has been generated. Then I add some debug code in [torch2trt/\_\_init\_\_.py](https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/__init__.py) as below:
```
from .torch2trt import *
from .converters import *
import tensorrt as trt


def load_plugins():
    print("---------------- before -----------------")
    registry = trt.get_plugin_registry()
    # test
    for plugin in registry.plugin_creator_list:
        print("AA: ", plugin.name, plugin.plugin_namespace)

    import os
    import ctypes
    ctypes.CDLL(os.path.join(os.path.dirname(__file__), 'libtorch2trt.so'))

    print("---------------- after -----------------")
    registry = trt.get_plugin_registry()
    # test
    for plugin in registry.plugin_creator_list:
        print("BB: ", plugin.name, plugin.plugin_namespace)


    torch2trt_creators = [c for c in registry.plugin_creator_list if c.plugin_namespace == 'torch2trt']
    for c in torch2trt_creators:
        registry.register_creator(c, 'torch2trt')


try:
    load_plugins()
    PLUGINS_LOADED = True
except OSError:
    PLUGINS_LOADED = False

print("PLUGINS_LOADED: ", PLUGINS_LOADED)
```

when I run `test.py`:
```
import torch2trt
```
I got this:
```sh
---------------- before -----------------
AA:  RnRes2Br1Br2c_TRT 
AA:  CgPersistentLSTMPlugin_TRT 
AA:  RnRes2Br2bBr2c_TRT 
AA:  SingleStepLSTMPlugin 
AA:  FancyActivation 
AA:  ResizeNearest 
AA:  Split 
AA:  InstanceNormalization 
PLUGINS_LOADED:  False
Process finished with exit code 0
```
All the `before` plugins are insterted by TensorRT as default, but I dont know why the `after` sentence does not come out after loading `libtorch2trt.so`.
And `PLUGINS_LOADED:  False` means loading try is failed.

**Comment by nan0755** [comment]
After loading this [TensorRT sample build .so](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#example2_add_custlay_c), the `PLUGINS_LOADED: True` printed.
```
from .torch2trt import *
from .converters import *
import tensorrt as trt


def load_plugins():
    import os
    import ctypes
    ctypes.CDLL(os.path.join(os.path.dirname(__file__), 'libtorch2trt.so'))
    # ctypes.CDLL("TensorRT-6.0.1.5/samples/python/uff_custom_plugin/build/libclipplugin.so")

    print("---------------- after -----------------")
    registry = trt.get_plugin_registry()
    # test
    for plugin in registry.plugin_creator_list:
        print("BB: ", plugin.name, plugin.plugin_namespace)

    registry = trt.get_plugin_registry()
    torch2trt_creators = [c for c in registry.plugin_creator_list if c.plugin_namespace == 'torch2trt']
    for c in torch2trt_creators:
        registry.register_creator(c, 'torch2trt')


try:
    load_plugins()
    PLUGINS_LOADED = True
except OSError:
    PLUGINS_LOADED = False

print("PLUGINS_LOADED: ", PLUGINS_LOADED)
```
I get this:
```sh
---------------- after -----------------
BB:  RnRes2Br1Br2c_TRT 
BB:  CgPersistentLSTMPlugin_TRT 
BB:  RnRes2Br2bBr2c_TRT 
BB:  SingleStepLSTMPlugin 
BB:  FancyActivation 
BB:  ResizeNearest 
BB:  Split 
BB:  InstanceNormalization 
BB:  CustomClipPlugin 
PLUGINS_LOADED:  True

Process finished with exit code 0
```
So the loading issue maybe caused by the building enviorment.

**Comment by StanMalorodov** [comment]
I can observe the same behavior. When building on a desktop computer, the plugins do not load. We tried to build it on a Jetson AGX yesterday, that worked without problems. 
I also saw, that in the build.py the lib and include path are set to the ARM version of linux. 
This has to be changed to /usr/include/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu on a non-ARM computer. But still it doesn't change anything. Still can't load the plugin :/

**Comment by aininot260** [comment]
> I can observe the same behavior. When building on a desktop computer, the plugins do not load. We tried to build it on a Jetson AGX yesterday, that worked without problems.
> I also saw, that in the build.py the lib and include path are set to the ARM version of linux.
> This has to be changed to /usr/include/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu on a non-ARM computer. But still it doesn't change anything. Still can't load the plugin :/

Me too.It works well on my AGX Xavier.When I try to load it on a x86_64 computer.It throws link errors like:

`undefined symbol: _ZN3c1014DeviceTypeNameB5cxx11ENS_10DeviceTypeEb`

**Comment by StanMalorodov** [comment]
Where do you get this Error ? I dont get any compilation Errors, it just
fails to load the Plugin. I also tried to put the Plugin in the trt sample
folder where this clipping Plugin is built. But the same, it compiles but
it cant be loaded.

aininot260 <notifications@github.com> schrieb am Sa., 7. Dez. 2019, 03:12:

**Comment by aininot260** [comment]
After installed,modify the __init__.py in interpolate folder from the python installing site like this:

try:

except OSError:

to

try:

except OSError as e:
    print(e)

**Comment by nan0755** [comment]
> After installed,modify the **init**.py in interpolate folder from the python installing site like this:
> 
> try:
> 
> except OSError:
> 
> to
> 
> try:
> 
> except OSError as e:
> print(e)

I can't find this line in interpolate/ \_\_init\_\_.py

**Comment by aininot260** [comment]
Sorry,here:
(tensorrt) nvidia@Dell:~/anaconda3/envs/tensorrt/lib/python3.6/site-packages/torch2trt$ 
vim __init__.py

modify:
try:
    load_plugins()
    PLUGINS_LOADED = True
except OSError as e:
    print(e)
    PLUGINS_LOADED = False
@nan0755

**Comment by nan0755** [comment]
> After installed,modify the **init**.py in interpolate folder from the python installing site like this:
> 
> try:
> 
> except OSError:
> 
> to
> 
> try:
> 
> except OSError as e:
> print(e)

I got this: `libtorch2trt.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev`

**Comment by aininot260** [comment]
That's another linking error about protobuf......

**Comment by massir-rpi** [comment]
Was the `libtorch2trt.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev` error solved? I'm getting the same issue.

**Comment by azuryl** [comment]
> After installed,modify the **init**.py in interpolate folder from the python installing site like this:
> 
> try:
> 
> except OSError:
> 
> to
> 
> try:
> 
> except OSError as e: print(e)
excuse me .didi you fix it ?
