### ISSUE TITLE
which version of trt is used when perform benchmark?

### ISSUE THREAD

**Issue by yoershine** [NVIDIA-AI-IOT/torch2trt#178]

**Comment by jaybdub** [comment]
Hi yoershine,

Thanks for reaching out!

I believve, the TensorRT version for the benchmarks listed in the README was 5.0.  The benchmarks in the [benchmarks](https://github.com/NVIDIA-AI-IOT/torch2trt/tree/master/benchmarks) is 5.0 or 5.1.

Hope that helps, please let me know if you have any questions.

Best,
John

**Comment by yoershine** [comment]
Thanks @jaybdub
