### ISSUE TITLE
resnet18 problem

### ISSUE THREAD

**Issue by QZ-cmd** [NVIDIA-AI-IOT/torch2trt#188]
hello，
       
I run resnet18 according to your torch2trt method. I can't reach 90fps in your benchmarks. I can only reach 75fps. i use jetson nano cuda10.0，TRT5.0.1...I want to ask what environment you used to run out of,looking forward to you reply.thanks

**Comment by jaybdub** [comment]
Hi QZ-cmd,

Thanks for reaching out

Do you mind also sharing

* PyTorch Version
* [torchvision](https://github.com/pytorch/vision) version
* Power mode of Jetson Nano (5W or MAXN)
* Whether ``jetson_clocks`` is called
* Commands used to benchmark resnet18

Best,
John

**Comment by QZ-cmd** [comment]
hi John，
Thank you for your reply, I opened jetson_clocks, it can achieve 90fps, thank you again。
Best wishes，
QZ-cmd
