### ISSUE TITLE
Bug of Linear

### ISSUE THREAD

**Issue by xieydd** [NVIDIA-AI-IOT/torch2trt#191]
The default of torch2trt Linear input`s shape is [Batch,feature_in], the most of situation is [Batch,*,feature_in] in [pytorch api](https://pytorch.org/docs/stable/nn.functional.html#torch.nn.functional.linear), if add a test in 
```
@add_module_test(torch.float32, torch.device('cuda'), [(1, 10,10)])
```
it will be a error, i think this is a bug, @jaybdub Can you take a look at it.
same error in #161

**Comment by jaybdub** [comment]
Hi xieydd,

Thanks for sharing!  

Yes, I'll take a look soon.

Best,
John

**Comment by jaybdub** [comment]
This is now fixed in this PR

**Comment by ma-siddiqui** [comment]
Thank you very much. Really appreciate it.
I cloned the latest repo and run the code. Unfortunately it is throwing exceptions in Linear converter with the below errors. But If I comment the line#43 (**from .view import ***)  in converters __init__ then code is executed successfully.

[TensorRT] ERROR: (Unnamed Layer* 1168) [Shuffle]: uninferred dimensions are not an exact divisor of input dimensions, so inferred dimension cannot be calculated
Traceback (most recent call last):
File "/home/muhammadsiddiqui/anaconda3/envs/mcc-dev/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 202, in wrapper
    converter['converter'](ctx)
  File "..python3.7/site-packages/torch2trt/converters/Linear.py", line 9, in convert_Linear
    input_trt = trt_(ctx.network, input)
  File "...python3.7/site-packages/torch2trt/torch2trt.py", line 116, in trt_
    num_dim = len(t._trt.shape) # non-leaf tensors must already have _trt, get shape from that
ValueError: __len__() should return >= 0
Terminated

**Comment by ma-siddiqui** [comment]
Also it seems some issue in function { def num_slice_types(slices): }

File "python3.7/site-packages/torch2trt/converters/getitem.py", line 18, in num_slice_types
    for s in slices:
TypeError: 'int' object is not iterable

**Comment by xieydd** [comment]
@jaybdub It works, thanks a lot.
