### ISSUE TITLE
int8 conversion didn't accelerate latency wrt fp16

### ISSUE THREAD

**Issue by anuar12** [NVIDIA-AI-IOT/torch2trt#201]
Not sure whether I am enabling int8 correctly, but I tried it on Resnet-18 and Densenet-121 from trt_pose and only got very small improvement in latency in comparison to fp16, the output on one example was correct though. Perhaps would be great if you could provide a minimal example similar to https://github.com/NVIDIA-AI-IOT/trt_pose/blob/master/tasks/human_pose/live_demo.ipynb.

As far as I understand `int8_calib_dataset` only takes one image, so having it doesn't make a difference. I tried increasing workspace_size but that didn't help. I also tried both Entropy algorithms and didn't see a difference.
```
model_trt = torch2trt.torch2trt(model, [data], fp16_mode=True, int8_mode=True,
                                    int8_calib_dataset=int8_dataset,
                                    max_batch_size=BATCH_SIZE,
                                    max_workspace_size=1<<28)
```
Xavier, Jetpack 4.2, Pytorch 1.1, TensorRT 5.1.6, Torchvision 0.4.1.
Thanks!

**Comment by jaybdub** [comment]
Hi anuar12,

Thanks for reaching out.

### Regarding performance

It's possible that the performance improvements aren't as significant in some scenarios.  Perhaps the effect may be more dramatic for larger batch sizes, etc. Where overhead is less significant. 

### Regarding int8 usage / calibration

Sorry for not having documented this more clearly.

There are some usage instructions in the comment for the PR enabling int8 support

https://github.com/NVIDIA-AI-IOT/torch2trt/pull/168#issue-345987154

This shows how to provide a calibration dataset, which is likely necessary.  The calibration dataset is responsible for _providing_ images for calibration.  You'll need to implement the ``__len__`` and ``__getitem__`` methods.

I'll consider adding an example notebook to this repository for int8 usage.

Please let me know if this helps, or you have any questions. 


Best,
John

**Comment by anuar12** [comment]
Great, thanks for concise response. I will try and report back.

**Comment by anuar12** [comment]
So, I tried the following on Jetson Xavier:
- Int8 Tochvision's models (resnet-family) works very well and accelerates as expected!
- I tried Int8 of TRT-pose's Resnet model and it _only accelerate 10-15% wrt fp16_. Since it's using the same backbone, it should've been something in the output cmap/paf heads (i.e. Transposed Convolution probably). I tried both models with attention and without it and saw only 10-15% acceleration wrt fp16.

**Comment by thancaocuong** [comment]
Hi @anuar12 , can you share me the source to convert trt_pose model to int8? I did convert it on RTX2080Ti but the model can not estimate the keypoints.

**Comment by anuar12** [comment]
Unfortunately I can't easily get the code, but it was mostly simply changing the int8 argument: https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/torch2trt.py#L392
Also sometimes turning on fp16=True at the same time helps because some kernels might run on fp16 (instead of fp32) if they cannot be run on int8.

**Comment by thancaocuong** [comment]
@anuar12  I did it but still get worse result (predicted heatmaps change dramatically)
