### ISSUE TITLE
How to properly install this package?

### ISSUE THREAD

**Issue by MaratZakirov** [NVIDIA-AI-IOT/torch2trt#203]
from torch2trt.module_test import add_module_test
ModuleNotFoundError: No module named 'torch2trt.module_test

**Comment by MaratZakirov** [comment]
Sorry I close the issue

**Comment by adizhol** [comment]
@MaratZakirov 
Having the same issue.
How did you solve it?

**Comment by MaratZakirov** [comment]
> @MaratZakirov
> Having the same issue.
> How did you solve it?

python setup.py

Read project readme :)
