### ISSUE TITLE
TensorRT assertation due to batch_size > 1 in my case, why?

### ISSUE THREAD

**Issue by MaratZakirov** [NVIDIA-AI-IOT/torch2trt#208]
When I use batch_size > 1 I always get 

`[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::451, condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize()`

```
from torch2trt import torch2trt
from torch import nn

# create some regular pytorch model...
# support route shortcut and reorg
class DummyNet(nn.Module):
    def __init__(self):
        super(DummyNet, self).__init__()

    def forward(self, x):
        return x + 1

    model = DummyNet().cuda()
    x = torch.rand(2, 3, 8, 16).cuda()  <<<<<<<<<<----- Batch bigger than 1 does not work due to dissertation in TensoRT

# convert to TensorRT feeding sample data as input
model.eval() # super important for bn
model_trt = torch2trt(model, [x])

y_trt = model_trt(x)

# check the output against PyTorch
y = model(x)
print()
print(y.shape, y_trt.shape)
print(torch.max(torch.abs(y - y_trt)))
```

**Comment by MaratZakirov** [comment]
Sorry for that... I have just find option for batch size

**Comment by QZ-cmd** [comment]
Hello is there any way to set the batchsize greater than 1？

**Comment by reyuwei** [comment]
> Hello is there any way to set the batchsize greater than 1？

Set the parameter _max_batch_size_ in [def torch2trt](https://github.com/NVIDIA-AI-IOT/torch2trt/blob/b9d9e73ca5f510e9be99ac2a9363f7b29cf03233/torch2trt/torch2trt.py#L482).
