### ISSUE TITLE
why interpolate implemented by plugin not IResizeLayer?

### ISSUE THREAD

**Issue by allenling** [NVIDIA-AI-IOT/torch2trt#210]
there is IResizeLayer in trt could do interpolate, why make interpolate plugin here?

just for demonstrating plugin usage?

**Comment by jaybdub** [comment]
Hi allenling,

Thanks for reaching out!

One reason is that IResizeLayer was not introduced until TensorRT 6.0.  torch2trt was originally targeting TensorRT 5.0.  

Another reason is that I believe cubic interpolation is not supported without a plugin.  

It may make sense to update this layer with version / argument checking to pick the most suitable implementation.

For now, it is possible to override the interpolate converter.  I believe some users have successfully done this.  

Please let me know if you have any questions.

Best,
John

**Comment by allenling** [comment]
thanks for reply!

and yes, i tryed to add IResizeLayer into interpolate converter implementation, but something seems go wrong. 

i got a error result campared to torch interpolate bilinear function with align_corners=False

you can check out this  https://github.com/NVIDIA/TensorRT/issues/273

looking forward to reply!
