### ISSUE TITLE
IncompatibleKeys with model conversion and issues loading TRT model

### ISSUE THREAD

**Issue by marvision-ai** [NVIDIA-AI-IOT/torch2trt#211]
When trying to use starter classification notebook and run the resnet18 conversion, I get the following error:

`Warning: Encountered known unsupported method torch.Tensor.flatten`

Then when I try to load the TRT model:
`IncompatibleKeys(missing_keys=[], unexpected_keys=[])
`

Is there something that I am not doing correctly? I have not touched any of the starter notebooks at all. 

Thanks!

**Comment by karansomaiah** [comment]
I am facing a similar issue and getting the same warning. Let me know if you were able to find a fix
