### ISSUE TITLE
Error when converting jit trace with torch2trt

### ISSUE THREAD

**Issue by vivanov879** [NVIDIA-AI-IOT/torch2trt#22]
Hi. Can't convert a model loaded with jit trace. However, the same model can be converted when not in trace mode. 

```
model = torch.jit.load(str(checkpoint_fn), map_location="cpu")
model = torch2trt(model, [x])
```

errors with 

```
File "/usr/local/lib/python3.7/dist-packages/torch2trt/torch2trt.py", line 256, in torch2trt
    ctx.mark_outputs(outputs, output_names)
  File "/usr/local/lib/python3.7/dist-packages/torch2trt/torch2trt.py", line 171, in mark_outputs
    trt_tensor = torch_output._trt
AttributeError: 'Tensor' object has no attribute '_trt'


```

**Comment by jaybdub** [comment]
Hi vivanov879,

Thanks for reaching out.  Unfortunately, the converter is not designed to parse TorchScript graphs, but rather the raw Python code.

I'm curious, what is the reason that you would like to parse the TorchScript trace rather than the raw Python module?  

Best,
John

**Comment by vivanov879** [comment]
Thanks, John. I am using TorchScript solely for ease of serialization.

**Comment by baheytharwat** [comment]
Hi @jaybdub,
Do you know if I can inverse these two operations? I mean converting to trt first, then script or trace the trt model.
