### ISSUE TITLE
No module named torch2trt.converters.Identity

### ISSUE THREAD

**Issue by DCC77** [NVIDIA-AI-IOT/torch2trt#221]
after install torch2trt, No module named torch2trt.converters.Identity was encountered

**Comment by lrh454830526** [comment]
> after install torch2trt, No module named torch2trt.converters.Identity was encountered
Hey,have you solved the probleam,I have met the issue too.

**Comment by DCC77** [comment]
I found the problem. I unzipped the installation package in Windows 7. Some .py scripts with the same file name (only the initial letter size is not the same), which will be covered during the decompression process, you should try to directly install in Ubuntu.
