### ISSUE TITLE
'tensorrt.tensorrt.ActivationType' has no attribute 'LEAKY_RELU'

### ISSUE THREAD

**Issue by zhouyongxyz** [NVIDIA-AI-IOT/torch2trt#226]
when i use torch2trt to accelerate yolov3 . output error.

AttributeError: type object 'tensorrt.tensorrt.ActivationType' has no attribute 'LEAKY_RELU'

**Comment by Arcadia-1** [comment]
I met the same error but I cannot fix it. 

There does exist 'LEAKY_RELU' in the file 'torch2trt/converters/activation.py'.

**Comment by ch98road** [comment]
my Traceback log is 'tensorrt.tensorrt.ActivationType' has no attribute 'LEAKY_RELU' ,and my tensorrt version is 5.0

**Comment by ch98road** [comment]
https://blog.csdn.net/symuamua/article/details/104457170

**Comment by ch98road** [comment]
Something  I have found in doc：jetpack-tensorRT5.0 does not have ActicationType LEAKY_RELU ,but tensorRT6.0、7.0  does，so i update to jetpack 4.3-tensorRT6.0 ,it works
more info:https://blog.csdn.net/symuamua/article/details/104457170
