### ISSUE TITLE
Why slicing operation will become different after calling torch2trt?

### ISSUE THREAD

**Issue by zwqnju** [NVIDIA-AI-IOT/torch2trt#234]
This bug can be reproduced like this.

If you run the following code:

**import torch
a = torch.ones((1, 3))
keep = torch.ones((1,), dtype=torch.bool)
print(a[keep].shape)**

The output will be [1,3]

But after calling torch2trt like your sample code:

**from torch2trt import torch2trt
from torchvision.models.alexnet import alexnet
model = alexnet(pretrained=True).eval().cuda()
x = torch.ones((1, 3, 224, 224)).cuda()
model_trt = torch2trt(model, [x])**

Then run the first piece of code again, the output will become [1, 1, 3]

Why? The two pieces of code seem irrelevant.

This bug will influence my existing code. When I perform similar slicing operation, I have to check if torch2trt has been called, and make different process dependently. Anyway, this bug makes me very confused.

**Comment by Akababa** [comment]
torch2trt assumes implicit batch dimension everywhere, so when you call __getitem__ it drops the first dimension of the slice. But it's still weird how it has side effects on torch module.

**Comment by jaybdub** [comment]
Hi @zwqnju,

Thanks for reaching out!

``torch2trt`` works by modifying existing methods, attaching conversion hooks.  It's possible there is a bug in one of the conversion hooks.  

These hooks should be removed after ``torch2trt`` has finished, so it is odd the behavior is not identical.  

I hope to look into this soon.

Do you mind sharing

1. PyTorch Version
2. TensorRT Version
3. Torchvision Version
4. Platform (ie: Jetson Xavier)

Best,
John

**Comment by zwqnju** [comment]
>     4\. Jetson Xavier

Thank you for your reply!

1. PyTorch: 1.2.0 
2. TensorRT: 7.0.0.11
3. Torchvision: 0.4.2
4. Platform: Ubuntu 16.04, CUDA 10.0, cudnn 7.6.4, Python 2.7 

I don't think that this issue is related to the above environment. I also try in PyTorch 1.3.1+ Python 3.7, and get the same result.

**Comment by Sanster** [comment]
I have the same issue. And I tested using TRTModule() to load a converted `_trt` model, the output of `a[keep].shape` is right.

**Comment by Jonghu** [comment]
As @Sanster said,

1. Make a new file(process) that convert and save model and then exit (to swipe out context which is buggy, so leads to slicing problem)
2. In another process where to use the model, load the saved model (make sure `torch2trt` function is not called)

This worked for me.

**Comment by zwqnju** [comment]
@Jonghu Your method also works for me. Thanks!
