### ISSUE TITLE
Implicit batch dimension?

### ISSUE THREAD

**Issue by Akababa** [NVIDIA-AI-IOT/torch2trt#235]
I noticed all of the code removes the first dimension (`tuple(input._trt.shape) == tuple(input.shape[1:])`) except for constants. Does this mean it assumes implicit batch dimension for the network, so it needs to be modified for explicit batch flag?

**Comment by kallivad** [comment]
The same question from my side. Or there is another way of how to convert this model inn order to inference with batches?

**Comment by kallivad** [comment]
Thanks, found in previous posts: https://github.com/NVIDIA-AI-IOT/torch2trt/issues/63
