### ISSUE TITLE
Warning: Encountered known unsupported method torch.nn.functional.interpolate

### ISSUE THREAD

**Issue by GYxiaOH** [NVIDIA-AI-IOT/torch2trt#242]
i install torch2trt with plugin and install successfully, but i run python -m torch2trt.test --name=interpolate,there is nothing to show, and i run torch2trt,it shows:
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Traceback (most recent call last):
  File "../PAN.pytorch/t2trt.py", line 42, in <module>
    convert_trt(model_path)
  File "../PAN.pytorch/t2trt.py", line 26, in convert_trt
    model_trt = torch2trt(torch_model, [dummy_input])
  File "/search/odin/hongyuan/anaconda3/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 381, in torch2trt
    ctx.mark_outputs(outputs, output_names)
  File "/search/odin/hongyuan/anaconda3/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 282, in mark_outputs
    trt_tensor = torch_output._trt
AttributeError: 'Tensor' object has no attribute '_trt'
i try to run ldd -r libtorch2trt, it all right:
	linux-vdso.so.1 =>  (0x00007fff1f751000)
	libc10.so => /search/odin/hongyuan/libtorch/lib/libc10.so (0x00007f24297a6000)
	libc10_cuda.so => /search/odin/hongyuan/libtorch/lib/libc10_cuda.so (0x00007f2429578000)
	libtorch.so => /search/odin/hongyuan/libtorch/lib/libtorch.so (0x00007f23de7d4000)
	libcudart.so.10.0 => /usr/local/cuda-10.0/lib64/libcudart.so.10.0 (0x00007f23de55a000)
	libprotobuf.so.22 => /usr/local/protobuf3.11.2/lib/libprotobuf.so.22 (0x00007f23de0b5000)
	libprotobuf-lite.so.22 => /usr/local/protobuf3.11.2/lib/libprotobuf-lite.so.22 (0x00007f23dde31000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f23ddc15000)
	libnvinfer.so.7 => /search/odin/hongyuan/tensorrt/TensorRT-7.0.0.11/lib/libnvinfer.so.7 (0x00007f23cff2f000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f2429d19000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f23cfc2c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f23cfa16000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f23cf649000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2429c4e000)
	libgomp-7c85b1e2.so.1 => /search/odin/hongyuan/libtorch/lib/libgomp-7c85b1e2.so.1 (0x00007f23cf41f000)
	libcudart-1b201d85.so.10.1 => /search/odin/hongyuan/libtorch/lib/libcudart-1b201d85.so.10.1 (0x00007f23cf1a0000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f23cef98000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f23ced94000)
	libnvToolsExt-3965bdd0.so.1 => /search/odin/hongyuan/libtorch/lib/libnvToolsExt-3965bdd0.so.1 (0x00007f23ceb8a000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f23ce974000)
	libcudnn.so.7 => /usr/local/cuda-10.0/lib64/libcudnn.so.7 (0x00007f23b7163000)
	libcublas.so.10.0 => /usr/local/cuda-10.0/lib64/libcublas.so.10.0 (0x00007f23b2bcd000)
	libmyelin.so.1 => /search/odin/hongyuan/tensorrt/TensorRT-7.0.0.11/lib/libmyelin.so.1 (0x00007f23b23bc000)
	libnvrtc.so.10.0 => /usr/local/cuda-10.0/lib64/libnvrtc.so.10.0 (0x00007f23b0da0000)
anyone can help me?

**Comment by anuar12** [comment]
compile with plugins

**Comment by czs1886** [comment]
Same problem here, is it solved?
