### ISSUE TITLE
I found that the model converted by torch2trt has some memory leak issure, any advice?

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA-AI-IOT/torch2trt#245]
I found that the model converted by torch2trt has some memory leak issure, any advice?

**Comment by jaybdub** [comment]
Hi Edwardmark,

Thanks for reaching out!  I haven't personally witnessed this so far.  Do you mind sharing the following information

* Model your converting
* PyTorch version
* TensorRT version
* Platform (ie: Jetson Nano, Jetson Xavier, etc.)

Best,
John

**Comment by Edwardmark** [comment]
@jaybdub  Thanks for your kind response. And I have found the error, it is not concered about this project but only a coding bug of my project.
