### ISSUE TITLE
Warning: Encountered known unsupported method torch.argmax

### ISSUE THREAD

**Issue by xinyang-go** [NVIDIA-AI-IOT/torch2trt#246]
Will argmax be supported in the future?

**Comment by jaybdub** [comment]
Hi xinyang-go,

Thanks for reaching out!  I hadn't considered this to date.

Do you mind sharing your use case for argmax?

Best,
John

**Comment by xinyang-go** [comment]
Thanks.
I just want to simplify the deployment of my network on c++. Otherwise I have to write it by myself on c++.
Aactually, it's not a matter.
