### ISSUE TITLE
About int8 throughput wrong  problem

### ISSUE THREAD

**Issue by QZ-cmd** [NVIDIA-AI-IOT/torch2trt#255]
hello，
I use your method to test the throughput of int8, which is too different from that of fp16。
resnet18 int8 throughput  44.09fps
               fp16 throughput  90.01fps(normal)
resnet18 int8  lantency     21.35ms
               fp16 lantency      12.15(normal)
code：
import torch
from torch2trt import torch2trt
import torchvision.models as models
from torch2trt import TRTModule
model=models.resnet18(pretrained=False).eval().cuda()
x=torch.randn(8,3,244,244).cuda()
model_trt=torch2trt(model,[x],int8_mode=True)
torch.save(model_trt.state_dict(), 'resnet18_trt_int8.pth')

I don't know what's wrong, please give me some advice。

**Comment by anuar12** [comment]
I tried both on 2080Ti and Jetson Xavier and saw almost double speed boost with Resnet models from torchvision...
Your GPU probably doesn't have support for int8 (or u have some specific TRT or torchvision versions which don't work together)
One can also try to enable `fp16_mode=True` too to make sure that some kernels can run in fp16 if they are not available in int8.

**Comment by QZ-cmd** [comment]
Thank you for your reply. I used the Jetson nano, fp16 = true test is ok. If it's convenient, can you reply to my email? I'd like to ask you some questions. Thank you very much.

**Comment by anuar12** [comment]
As far as I remember Nano is Maxwell architecture so it doesn't have support for int8 :)

**Comment by czs1886** [comment]
@QZ-cmd How did you calculate the throughput of your torch2trt model?
