### ISSUE TITLE
TRT 6 - Interpolate issue

### ISSUE THREAD

**Issue by skyler1253** [NVIDIA-AI-IOT/torch2trt#256]
I'm having issues getting the interpolate plugin to register in TRT6 on the Jetson Nano.

After running: sudo python3 setup.py install --plugins
Everything seems to install correctly

Running:
python3 -m torch2trt.test --name=interpolate

Results in:
Segmentation fault (core dumped)
 
I also get this error when trying to run the creator line in the interpolate.py file:

File "/torch2trt/torch2trt/converters/interpolate/interpolate.py", line 11, in get_interpolate_plugin
    creator = [c for c in registry.plugin_creator_list if c.name == PLUGIN_NAME and c.plugin_namespace == 'torch2trt'][0]
IndexError: list index out of range

I can get this to run fine on TRT5 on the Jetson Nano, but seem to be having issues with Jetpack 4.3 which has TRT 6.  Any thoughts @jaybdub ? Thanks!

**Comment by NTU-P04922004** [comment]
I have the same issues on TRT5, 6, 7 with Ubuntu 18.04, CUDA 10.0, CuDNN 7.4.2, PyTorch 1.3.1. Waiting for someone to rescue me. :hurtrealbad:

**Comment by ma-siddiqui** [comment]
Did you try torch interpolate instead of trt plugin?
Try in to include torch interpolate in converters__init__. py and comment .interpolate import * end the file.

**Comment by NTU-P04922004** [comment]
@ma-siddiqui 

Thanks for the advice.
I have tried to include torch.nn.functional.interpolate in converters__init__. py and comment .interpolate import * end the file, but the issue remains.

**Comment by Stephenfang51** [comment]
> @ma-siddiqui
> 
> Thanks for the advice.
> I have tried to include torch.nn.functional.interpolate in converters__init__. py and comment .interpolate import * end the file, but the issue remains.

Hi Sir , Did you solve the issue now ?

**Comment by ma-siddiqui** [comment]
Yes. I was able to do it. I made all protobuf version same and then build/installed plugin. Now a days I am facing an other issues. Once resolved it, will be back on this and see in detail.

**Comment by Stephenfang51** [comment]
> Yes. I was able to do it. I made all protobuf version same and then built/installed plugin. Now a days I am facing an other issue. Once it is resolved, I will be back on this and will look into further details.

Sir Would you please tell me how to build the plugin with `flag -D_GLIBCXX_USE_CXX11_ABI=1` ?
I installed the torch2trt with `python setup.py install --plugin`, where to put the flags?
