### ISSUE TITLE
Upgrade to TensorRT 6 or 7 to run on DLA through Python API.

### ISSUE THREAD

**Issue by anuar12** [NVIDIA-AI-IOT/torch2trt#258]
With TensorRT5.1 it's not possible to use DLA on Jetson Xavier with Python API, would be great if we update to TRT 6 or 7 for that.

**Comment by torstr** [comment]
What is the status on this? Have tried to find a way to utilize DLA with torch2trt, but cannot find anything about it. Inference should be run at a Xavier. Is it possible? Can someone point me in a direction?
Thanks

**Comment by charlielito** [comment]
Same question
