### ISSUE TITLE
_trt property disappears while calling data.cpu().numpy()

### ISSUE THREAD

**Issue by ma-siddiqui** [NVIDIA-AI-IOT/torch2trt#272]
By calling below line of code the _trt property disappears. I have to perform some functions on numpy when this code is executed the trt property attached to output.

scores = rpn_cls_prob.data.cpu().numpy()

Any solution?

Thanks,

**Comment by jaybdub** [comment]
Hi ma-siddiqui,

Thanks for reaching out!

This is expected behavior.  Torch2trt is not currently designed to handle Tensors living on CPU / numpy.

That said, the project is largely use-case driven, do you mind sharing how you're using this call inside your model?  

Best,
John

**Comment by ma-siddiqui** [comment]
Thank you for the response. I am trying to convert the below project (https://github.com/ShuLiu1993/PANet) and having issue at line#58 in file https://github.com/ShuLiu1993/PANet/blob/master/lib/modeling/generate_proposals.py

Thanks,
