### ISSUE TITLE
get_interpolate_plugin ERROR

### ISSUE THREAD

**Issue by duanxuandandan** [NVIDIA-AI-IOT/torch2trt#274]
hi! when I was converting fpn network which includes "interpolate" op, I got this error
File "XXXX/torch2trt/torch2trt/converters/interpolate/interpolate.py", line 11, in get_interpolate_plugin
creator = [c for c in registry.plugin_creator_list if c.name == PLUGIN_NAME and c.plugin_namespace == 'torch2trt'][0]
IndexError: list index out of range.

How can I solve it?

**Comment by PareshKamble** [comment]
@duanxuandandan @saulzar @jaybdub 
I am too facing the same issue.


Any luck so far?

**Comment by duanxuandandan** [comment]
How can I solve it?

**Comment by adizhol** [comment]
Same problem here
