### ISSUE TITLE
Could you please give me an example to use the serilized engine to do tensorRT cpp inference?

### ISSUE THREAD

**Issue by Edwardmark** [NVIDIA-AI-IOT/torch2trt#276]
Hi, your project is really great.
Could you please give me an example to use the serilized engine to do usual tensorRT cpp inference?

**Comment by jaybdub** [comment]
Hi edwardmark,

Thanks for the positive feedback!  You can export the serialized engine by calling

‘’’python
with open(“model.engine”, “wb”) as f:
    f.write(model_trt.engine.serialize())
‘’’

Then, you can load this engine in C++ using the TensorRT C++ API.  

The TensorRT documentation has more details on this part, but I’m happy to reiterate here if it helps.

Please let me know.

Best,
John

**Comment by Edwardmark** [comment]
@jaybdub I am new to TensorRT C++ API, could you please show me an easy eample when I got "model.engine", how can I do inference in TRT cpp api?
