### ISSUE TITLE
Warning: Encountered known unsupported method torch.nn.functional.interpolate

### ISSUE THREAD

**Issue by czs1886** [NVIDIA-AI-IOT/torch2trt#277]
I tested the interpolate plugin by "python3 -m torch2trt.test --name=interpolate" and no error occured. But when I run my tensorRT program this warning occures. Is it installed correctly?

**Comment by adizhol** [comment]
same here

**Comment by Jeffer-hua** [comment]
> I tested the interpolate plugin by "python3 -m torch2trt.test --name=interpolate" and no error occured. But when I run my tensorRT program this warning occures. Is it installed correctly?

I see the same problem , can you solve it

**Comment by czs1886** [comment]
> > I tested the interpolate plugin by "python3 -m torch2trt.test --name=interpolate" and no error occured. But when I run my tensorRT program this warning occures. Is it installed correctly?
> 
> I see the same problem , can you solve it

I solved this. You can modify the try and catch block in torch2trt/torch2trt/__init__.py and torch2trt/torch2trt/converters/__init__.py to check the problem.

For me, the direct cause is undefined symbol for libtorch2trt.so. `ldd -r libtorch2trt.so` to check if you have any undefined symbols. The root cause is I used different versions of gcc to compile protobuff and torch2trt. When I use gcc 4.8.5 to compile it , it works.
Below is my build.py, I changed some variables.
![image](https://user-images.githubusercontent.com/44554857/82319896-f2117b00-9a04-11ea-948d-66712a4b6f27.png)
