### ISSUE TITLE
inference slow on tx2

### ISSUE THREAD

**Issue by grimoire** [NVIDIA-AI-IOT/torch2trt#280]
I am working on deploy models in tx2
My model works fine on my desktop, with custom layer and batch support. take less than 40ms (vs pytorch 60ms+)
But when I use the engine builded on tx2, the model takes more time than pytorch(4times more than pytorch).
I also tried convert vgg and resnet from torchvision. Still slow.

Why did this happened and how do i fix it? 
Thanks

by the way, In order to support dynamic shape/batch support I did some modify on the torch2trt code, such as:
```

def torch2trt(module,
              inputs,
              input_names=None,
              output_names=None,
              log_level=trt.Logger.ERROR,
              max_batch_size=1,
              fp16_mode=False,
              max_workspace_size=0,
              opt_shape_param = None,
              strict_type_constraints=False,
              keep_network=True,
              int8_mode=False,
              int8_calib_dataset=None,
              int8_calib_algorithm=DEFAULT_CALIBRATION_ALGORITHM):
    inputs_in = inputs

    # copy inputs to avoid modifications to source data
    # inputs = [tensor.clone()[0:1]
    #           for tensor in inputs]  # only run single entry
    inputs = [tensor.clone() for tensor in inputs]

    logger = trt.Logger(log_level)
    builder = trt.Builder(logger)
    if support_dynamic_shape:
        EXPLICIT_BATCH = 1 << (int)(
            trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
        network = builder.create_network(EXPLICIT_BATCH)
    else:
        network = builder.create_network()

    with ConversionContext(network) as ctx:

        if isinstance(inputs, list):
            inputs = tuple(inputs)
        if not isinstance(inputs, tuple):
            inputs = (inputs, )
        ctx.add_inputs(inputs, input_names)

        outputs = module(*inputs)

        if not isinstance(outputs, tuple) and not isinstance(outputs, list):
            outputs = (outputs, )
        ctx.mark_outputs(outputs, output_names)

        torch.cuda.empty_cache()

        builder.max_workspace_size = max_workspace_size
        builder.fp16_mode = fp16_mode
        builder.max_batch_size = max_batch_size
        builder.strict_type_constraints = strict_type_constraints

        if support_dynamic_shape:
            config = builder.create_builder_config()
            config.max_workspace_size = max_workspace_size
            profile = builder.create_optimization_profile()

            if input_names is None:
                input_names = ['input_%d' % i for i in range(len(inputs))]
            for input_index, input_tensor in enumerate(inputs):
                if opt_shape_param is not None:
                    min_shape = tuple(opt_shape_param[input_index][0,:])
                    opt_shape = tuple(opt_shape_param[input_index][1,:])
                    max_shape = tuple(opt_shape_param[input_index][2,:])
                else:
                    opt_shape = tuple(input_tensor.shape)
                    min_shape = opt_shape
                    max_shape = opt_shape
                profile.set_shape(
                    input_names[input_index], min_shape, opt_shape, max_shape)
            config.add_optimization_profile(profile)

    if int8_mode:

        # default to use input tensors for calibration
        if int8_calib_dataset is None:
            int8_calib_dataset = TensorBatchDataset(inputs_in)

        builder.int8_mode = True

        # @TODO(jwelsh):  Should we set batch_size=max_batch_size?  Need to investigate memory consumption
        builder.int8_calibrator = DatasetCalibrator(
            inputs, int8_calib_dataset, batch_size=1, algorithm=int8_calib_algorithm)

    if support_dynamic_shape:
        engine = builder.build_engine(network, config)
    else:
        engine = builder.build_cuda_engine(network)

    module_trt = TRTModule(engine, ctx.input_names, ctx.output_names)

    if keep_network:
        module_trt.network = network

    return module_trt
```

and other modify(add batch dims/ custom layer etc).

**Comment by zhengjiawen** [comment]
Could you tell me in detail what can I do to support dynamic input?  Thanks very much.

**Comment by grimoire** [comment]
@zhengjiawen  

read https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#work_dynamic_shapes  for details.

Or you can try my branch https://github.com/grimoire/torch2trt , Tested on resnet backbone.
Not all operations support dynamic input. For example view, reshape etc. You can implement a custom layer using nvinfer1::IPluginV2DynamicExt  to support it. 
And, sorry I can't share my custom layer for now ...

**Comment by z-bingo** [comment]
@grimoire Hi, I want to accelerate my model by torch2trt tool and I'm excited to find your forked repo. Thus, whether you can help me what can I do for supporting the dynamic shape of 'view' and other layers?

**Comment by grimoire** [comment]
>  Thus, whether you can help me what can I do for supporting the dynamic shape of 'view' and other layers?

Hi, glad you like my repo!

There are two method to support dynamic shape.
1. use shape tensor(Recommend). A lot of buildin layer accept shape tensor as extra input. Such as shuffleLayer/SliceLayer etc. The shape tensor can be created with network.add_shape. You can read the converter in my repo such as https://github.com/grimoire/torch2trt_dynamic/blob/master/torch2trt/converters/unsqueeze.py as example. or read https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#exe_shape_tensors for more detail.
2. Create a cpp/cuda custom layer with nvinfer1::IPluginV2DynamicExt. Implement getOutputDimensions as the output shape , for example:
`DimsExprs BarPlugin::getOutputDimensions(int outputIndex, 
    const DimsExprs* inputs, int nbInputs, 
    IExprBuilder& exprBuilder)
{
    switch (outputIndex)
    {
    case 0: 
    {
        // First dimension of output is sum of input 
        // first dimensions.
        DimsExprs output(inputs[0]);
        output.d[0] = 
            exprBuilder.operation(DimensionOperation::kSUM, 
                inputs[0].d[0], inputs[1].d[0]);
	   return output;
    }
    case 1:
        return inputs[0];
    default:
         throw std::invalid_argument(“invalid output”);
}`
you also could combine multiple layer into one custom layer to further accelerate the model. Read my GroupNorm for example https://github.com/grimoire/torch2trt_dynamic/blob/master/torch2trt/converters/GroupNorm.py (Sorry I can not share the cpp code, or my boss might kill me.) .  read https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#example3_add_custlay_dynamic for detail.

By the way, could you share the layers/operations you need?

**Comment by z-bingo** [comment]
> > Thus, whether you can help me what can I do for supporting the dynamic shape of 'view' and other layers?
> 
> Hi, glad you like my repo!
> 
> There are two method to support dynamic shape.
> 
> 1. use shape tensor(Recommend). A lot of buildin layer accept shape tensor as extra input. Such as shuffleLayer/SliceLayer etc. The shape tensor can be created with network.add_shape. You can read the converter in my repo such as https://github.com/grimoire/torch2trt_dynamic/blob/master/torch2trt/converters/unsqueeze.py as example. or read https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#exe_shape_tensors for more detail.
> 2. Create a cpp/cuda custom layer with nvinfer1::IPluginV2DynamicExt. Implement getOutputDimensions as the output shape , for example:
>    `DimsExprs BarPlugin::getOutputDimensions(int outputIndex,  const DimsExprs* inputs, int nbInputs,  IExprBuilder& exprBuilder) { switch (outputIndex) { case 0:  { // First dimension of output is sum of input  // first dimensions. DimsExprs output(inputs[0]); output.d[0] =  exprBuilder.operation(DimensionOperation::kSUM,  inputs[0].d[0], inputs[1].d[0]); return output; } case 1: return inputs[0]; default: throw std::invalid_argument(“invalid output”); }`
>    you also could combine multiple layer into one custom layer to further accelerate the model. Read my GroupNorm for example https://github.com/grimoire/torch2trt_dynamic/blob/master/torch2trt/converters/GroupNorm.py (Sorry I can not share the cpp code, or my boss might kill me.) .  read https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#example3_add_custlay_dynamic for detail.
> 
> By the way, could you share the layers/operations you need?

Thanks your detailed reply, I would check your released codes seriously. In order to support the dynamic shape, in my view, layers such as 'view', 'cat', 'stack' are required due to they are highly depended on them.

**Comment by grimoire** [comment]
>  layers such as 'view', 'cat', 'stack' are required due to they are highly depended on them.

I updated 'cat', and 'stack' few days ago. dynamic test successed.  If these layer failed on your model, just share the script with me ~

'view' is a hard one. It is not easy to trace the input shape. I did add the dynamic support ... with some bugs(no negative shape support ,etc). You can try it, but custom converter might be a better choice. such as:

```
from torch2trt import tensorrt_converter

def custom_view(a, b):
    c = a.view(b.shape)
    return c


@tensorrt_converter('custom_view')
def convert_custom_view(ctx):
    input = ctx.method_args[0]
    other = ctx.method_args[1]
    input_trt = trt_(ctx.network, input)
    other_trt = trt_(ctx.network, other)
    output = ctx.method_return

    shape_trt = ctx.network.add_shape(other_trt).get_output(0)
    
    layer = ctx.network.add_shuffle(input_trt)
    layer.set_input(1, shape_trt)
    output._trt = layer.get_output(0)
```

Just an example, haven't tested.

**Comment by z-bingo** [comment]
> > layers such as 'view', 'cat', 'stack' are required due to they are highly depended on them.
> 
> I updated 'cat', and 'stack' few days ago. dynamic test successed. If these layer failed on your model, just share the script with me ~
> 
> 'view' is a hard one. It is not easy to trace the input shape. I did add the dynamic support ... with some bugs(no negative shape support ,etc). You can try it, but custom converter might be a better choice. such as:
> 
> ```
> from torch2trt import tensorrt_converter
> 
> def custom_view(a, b):
>     c = a.view(b.shape)
>     return c
> 
> 
> @tensorrt_converter('custom_view')
> def convert_custom_view(ctx):
>     input = ctx.method_args[0]
>     other = ctx.method_args[1]
>     input_trt = trt_(ctx.network, input)
>     other_trt = trt_(ctx.network, other)
>     output = ctx.method_return
> 
>     shape_trt = ctx.network.add_shape(other_trt).get_output(0)
>     
>     layer = ctx.network.add_shuffle(input_trt)
>     layer.set_input(1, shape_trt)
>     output._trt = layer.get_output(0)
> ```
> 
> Just an example, haven't tested.

Thanks very much, the operation of view, cat, stack can work now. By the way, the slice operations such as chunk, split cannot work better, do you know why these? And, I found a bug you can fix it, in ReLU6.py, input parameter '6' could be converted to the float.

**Comment by grimoire** [comment]
> the operation of view, cat, stack can work now. By the way, the slice operations such as chunk, split cannot work better, do you know why these? And, I found a bug you can fix it, in ReLU6.py, input parameter '6' could be converted to the float.

Thanks for the bug report.
 Relu6 has been fixed. And chunk support dynamic shape with some limit.

As for 'split' ... I guess there are nothing I can do.

There are some constrains (I guess) in tensorrt. such as:
The graph structure of the network must be fixed. That means the number of outputs is fixed for each layer. (In custom plugin, the getNbOutputs receive no Inputs.)
```
int DeformableConvPluginDynamic::getNbOutputs() const
{
    return 1;
}
```

Numbers of outputs of 'split' depends on the input shape, This will violate the constrain. (chunk has the same problem when shape[dim]%chunks != 0).
