### ISSUE TITLE
The influence by different batchsize with torch2trt

### ISSUE THREAD

**Issue by LossNAN** [NVIDIA-AI-IOT/torch2trt#281]
Thanks for this wonderful project!
We test on different models by different batchsize with torch2trt, then we found speed becomes slower as the batchsize increases on some models，specially on our YOLOV3 model，torch2trt only works when batchsize=1.
Here are some results(FPS):
1080Ti; 1000 step; image size 416;
```
| model_name   |      batchsize    |     pytorch    |    torch2trt   |
    alexnet              1                760.03           792.16
    alexnet              15               135.65           126.12
    resnet50             1                113.11           219.42
    resnet50             15               15.59            20.36
    YOLOV3               1                81.34            91.40
    YOLOV3               2                54.66            54.63
    YOLOV3               8                16.60            13.87
    YOLOV3               15               9.75             7.68
```
Could you please give me some suggestion?

Best,

**Comment by PressEtoRace** [comment]
I have the same question. I hope someone can answer it.Thanks!

**Comment by peter850421** [comment]
@LossNAN  Could you provide the throughput and latency?
