### ISSUE TITLE
ImportError: cannot import name 'torch2trt'

### ISSUE THREAD

**Issue by Stephenfang51** [NVIDIA-AI-IOT/torch2trt#283]
why ?

as the title
I sucessfully installed the torch2trt.

**Comment by chainfitness** [comment]
@Stephenfang51 @hxu296 Have you found any solutions to this ? I encountered the same problem.

**Comment by chainfitness** [comment]
@hxu296 I appreciate your prompt reply and share. I try it, but it was not worked. My problem was that "from torch2trt import torch2trt" was succeeded in python3 terminal but when running it in .py file, ImportError: cannot import name 'torch2trt' was acquired. could you help me, thanks in advance

**Comment by hxu296** [comment]
@chainfitness That exception never happened to me before, so sadly I can not help you. The situation you mentioned is really strange, as the same python executable shouldn't react differently for the same import statement. I would suggest checking the python runtime you used though: For the python3 terminal, `which python3` should give the path of the executable of the python shell (e.g. /home/user/bin/python3). For the .py file, add the line `import sys;print(sys.executable)` to .py should print the path of the executable that interprets the .py file. Are these 2 paths the same? If they aren't the same - then it's an easy fix, just make sure the .py file used the same python executable as the python3 terminal. If they are the same... Then you may have fallen into a rabbit hole...

**Comment by chainfitness** [comment]
@hxu296 I'm obliged to you for your assistance in my difficulty. The result is that I have fallen into a rabbit hole ... lol

**Comment by LordVoldemt** [comment]
cannot import name 'TRTModule' from 'torch2trt' (unknown location)
