### ISSUE TITLE
 No module named setuptools

### ISSUE THREAD

**Issue by justintime88** [NVIDIA-AI-IOT/torch2trt#286]
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by suhyung-code42** [comment]
@justintime88 could you share how did you resolve this issue?

**Comment by justintime88** [comment]
make sure you have all the Python packages installed (pip3, etc....)

**Comment by suhyung-code42** [comment]
@justintime88 thank you

**Comment by liguoyu666** [comment]
> @justintime88 thank you

Have you solved the problem? I met it too，and I installed the setuptools .

**Comment by justintime88** [comment]
Maybe try pip3 list, make sure setup tool is on the list. Try installing again.

**Comment by liguoyu666** [comment]
> Maybe try pip3 list, make sure setup tool is on the list. Try installing again.

Thank you, I installed successfully without 'sudo'.
