### ISSUE TITLE
nn.Sequential support

### ISSUE THREAD

**Issue by ma-siddiqui** [NVIDIA-AI-IOT/torch2trt#290]
Does torch2trt has implementation of nn.Sequential?

Thanks,

**Comment by jaybdub** [comment]
Hi ma-siddiqui,

Thanks for the question!

Yep!  ``nn.Sequential`` should be handled implicitly, assuming all of the child modules are supported. 

Please let me know if this helps, or you find this isn't the case.

Best,
John

**Comment by ma-siddiqui** [comment]
Thanks for the response. I cannot find its converter. Can you help me which file refers to its converter?

**Comment by jaybdub** [comment]
Actually, ``nn.Sequential`` doesn't explicitly need a converter.  The conversion depends on it's contents, so it's conversion is defined by the modules inside.  

The data flows through nn.Sequential layers, and each converter that does exist adds the appropriate TensorRT layers to network.  

Please let me know if this helps, or you're running into any issues.

Best,
John

**Comment by ma-siddiqui** [comment]
Thank you John. I really appreciate your quick response. Actually nn.sequential is not my actual problem. In fact it was my assumption,  may be my actual problem is due to this. In my case, the issue is, I am able to convert the pytorch model trt model. When I try to run inference it throws me follow errors which is problematic for me at the moment. Here is the errors:

[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0
[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_1
