### ISSUE TITLE
How to know which operations and layers not supported 

### ISSUE THREAD

**Issue by ma-siddiqui** [NVIDIA-AI-IOT/torch2trt#291]
Hi,

It would be great if some cal elaborate. How can someone find and identify layers/ops which are not supported or yet not implemented in torch2trt.

For example, I want to identify layers and ops which are not implemented in torch.
https://github.com/ShuLiu1993/PANet

**Comment by jaybdub** [comment]
Hi ma-siddiqui,

Do you mind sharing the code used to convert the model, as well as the output / error of the conversion?  

There are a few options for debugging, but right now, it's bit manual.  For some layers, this should be reported automatically.  Knowing what trouble you're facing may help guide any suggestions I have, and potentially help identify missing features of torch2trt.

Best,
John

**Comment by ma-siddiqui** [comment]
Thank you John. I converted the following project. (Before conversion I upgraded it  with Pytorch 1.2 and torchvision.ops.roi_align) It is working perfectly with pytorch 1.2. That code is not uploaded yet on github. 

In addition this, I am using following modified code (used from torch2trt) for conversion.

def add_inputs(ctx, torch_inputs, names=None):
    
    if names is None:
        names = ['input_%d' % i for i in range(len(torch_inputs))]
    ctx.input_names = names
    for indx, key in enumerate(torch_inputs):
        torch_input = torch_inputs[key]
        if not hasattr(torch_input, '_trt'):
            # input_shape = tuple(torch_input.shape)
            input_name = ctx.input_names[indx]
            trt_tensor = ctx.network.add_input(
                name=input_name,
                shape=tuple(torch_input.shape)[1:],
                dtype=torch_dtype_to_trt(torch_input.dtype),
            )
            trt_tensor.location = torch_device_to_trt(torch_input.device)
            torch_input._trt = trt_tensor
            torch_inputs[key] = torch_input

def mark_outputs(ctx, torch_outputs, names=None):
    
    torch_outputs_dict = {}
    for k, v in torch_outputs.items():
        if k == "blob_conv":
            torch_outputs_dict["output_0"] = v[0]
            torch_outputs_dict["output_1"] = v[1]
            torch_outputs_dict["output_2"] = v[2]
            torch_outputs_dict["output_3"] = v[3]
        elif k == "rois":
            torch_outputs_dict["output_4"] = v[0]
        elif k == "cls_score":
            torch_outputs_dict["output_5"] = v[0]
        elif k == "bbox_pred":
            torch_outputs_dict["output_6"] = v[0]
          
    ctx.output_names = [name for name in torch_outputs_dict.keys()]
    for i, k in enumerate(torch_outputs_dict):
        torch_output = torch_outputs_dict[k]
        if not hasattr(torch_output, '_trt'):
            continue

        trt_tensor = torch_output._trt
        trt_tensor.name =  k
        trt_tensor.location = torch_device_to_trt(torch_output.device)
        trt_tensor.dtype = torch_dtype_to_trt(torch_output.dtype)
        ctx.network.mark_output(trt_tensor)
            
def torch2trt_conversion(module, inputs_orig, input_names=None, output_names=None, log_level=trt.Logger.ERROR, max_batch_size=1,
        fp16_mode=False, max_workspace_size=0, strict_type_constraints=False, keep_network=True, add_args = None):
        
    
    inputs =  inputs_orig
    inputs["data"] = inputs["data"][0].clone().cuda().contiguous()
    inputs["im_info"] = inputs["im_info"][0].clone().cuda().contiguous()
    
    logger = trt.Logger(log_level)
    builder = trt.Builder(logger)
    network = builder.create_network()
    
    input_names = None 
    output_names = None
    dummy_inputs = (inputs['data'][0], inputs['im_info'][0]) 

    with ConversionContext(network) as ctx:
        
        add_inputs(ctx, inputs, input_names)
        outputs = module(**inputs)
        for k, v in outputs.items():
            if not isinstance(v, list):
                outputs[k] = [v]

        mark_outputs(ctx, outputs, output_names)
        
        builder.max_workspace_size =  1<<20 
        builder.fp16_mode = fp16_mode
        builder.max_batch_size = max_batch_size
        builder.strict_type_constraints = strict_type_constraints

        engine = builder.build_cuda_engine(network)
        if engine is None:
            print("failed to build  cuda engine")
            exit(-1)
        
        engine_bin = engine.serialize()
        with open(trt_engine_path, "wb") as f:
            f.write(engine_bin)
        print("TRT Engine written at: " + trt_engine_path)
        
        module_trt = TRTModule(engine, ctx.input_names, ctx.output_names)
        if keep_network:
            module_trt.network = network
        
    inputs_1 = []
    inputs_1.append(inputs['data'].clone().cuda().contiguous())
    inputs_1.append(inputs['im_info'].clone().cuda().contiguous())
    result = module_trt(inputs_1)
    print(trt_model_path)
    torch.save(module_trt.state_dict(), trt_model_path)
    print(trt_model_path)
    return result

 After converting into trt model, I am facing exceptions/Errors:

[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0
[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_1

**Comment by PistonY** [comment]
I also have this `[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0` issues, and then all the predictions are the same. @jaybdub Could you please give some suggestion.

**Comment by niaoyu** [comment]
> I also have this `[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0` issues, and then all the predictions are the same. @jaybdub Could you please give some suggestion.

Hi, I also meet the same problem, [TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0
But the result is just OK....

Do you have any further progress?

**Comment by lutianfei** [comment]
> I also have this `[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0` issues, and then all the predictions are the same. @jaybdub Could you please give some suggestion.

你好，我遇到了和你一样的问题，请问最后有解决吗？

**Comment by lutianfei** [comment]
> I also have this `[TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0` issues, and then all the predictions are the same. @jaybdub Could you please give some suggestion.

@PistonY 你好，我遇到了和你一样的问题，请问最后有解决吗？
