### ISSUE TITLE
[SOLVED]Error for interpolate plugin

### ISSUE THREAD

**Issue by shuangshuangguo** [NVIDIA-AI-IOT/torch2trt#295]
Before fixing problem, when run model with interpolate layer, there exists error:
IndexError: list index out of range.

**Fixing method:**
By running the command in torch2trt directory: `ldd -r torch2trt/libtorch2trt.so`, you can clearly see the error / warning, and you should fix the error one by one.

Here is my software version which can work:
    - cuda-10.0
    - cudnn-7.6.2
    - pytorch-1.1.0, torchvision-0.3.0
    - gcc-4.8.5
    - protobuf-3.11.4

**Comment by Jockeypan** [comment]
hello，@shuangshuangguo 
I followed your method, ldd -r  torch2trt/libtorch2trt.so seems fine, but  it still doesn't work.

`python3 -m torch2trt.test --name=interpolate` 
`......
creator = [c for c in registry.plugin_creator_list if c.name == PLUGIN_NAME and c.plugin_namespace == 'torch2trt'][0]
IndexError: list index out of range`

and I tried to load .so in python
`import tensorrt as trt
ctypes.CDLL('~/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so')
registry = trt.get_plugin_registry()
for c in registry.plugin_creator_list:
    print(c.name)
`
and got this result:
`RnRes2Br1Br2c_TRT
CgPersistentLSTMPlugin_TRT
RnRes2Br2bBr2c_TRT
SingleStepLSTMPlugin
FancyActivation
ResizeNearest
Split
InstanceNormalization`

I did not see any plugin related to **interpolate**

What did I miss?

**Comment by shuangshuangguo** [comment]
What is your terminal output of running ldd -r torch2trt/libtorch2trt.so?

**Comment by Jockeypan** [comment]
well there are still some undefined symbols. I've already upgraded protobuf. 
ldd -r ~/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so 
	linux-vdso.so.1 =>  (0x00007ffd675b5000)
	libc10.so => /usr/local/lib/python3.5/dist-packages/torch/lib/libc10.so (0x00007f9a00fab000)
	libc10_cuda.so => /usr/local/lib/python3.5/dist-packages/torch/lib/libc10_cuda.so (0x00007f9a00d81000)
	libtorch.so => /usr/local/lib/python3.5/dist-packages/torch/lib/libtorch.so (0x00007f99b7338000)
	libcudart.so.10.0 => /usr/local/cuda/lib64/libcudart.so.10.0 (0x00007f99b70be000)
	libprotobuf.so.22 => /usr/lib/libprotobuf.so.22 (0x00007f99b6c13000)
	libnvinfer.so.6 => /usr/lib/x86_64-linux-gnu/libnvinfer.so.6 (0x00007f99a9d32000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f99a99b0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f99a979a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f99a93d0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9a01456000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f99a90c7000)
	libgomp-4f651535.so.1 => /usr/local/lib/python3.5/dist-packages/torch/lib/libgomp-4f651535.so.1 (0x00007f99a8e9d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f99a8c80000)
	libcudart-1581fefa.so.10.0 => /usr/local/lib/python3.5/dist-packages/torch/lib/libcudart-1581fefa.so.10.0 (0x00007f99a8a03000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f99a87fb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f99a85f7000)
	libnvToolsExt-3965bdd0.so.1 => /usr/local/lib/python3.5/dist-packages/torch/lib/libnvToolsExt-3965bdd0.so.1 (0x00007f99a83ed000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f99a81d3000)
	libcudnn.so.7 => /usr/lib/x86_64-linux-gnu/libcudnn.so.7 (0x00007f9990905000)
	libcublas.so.10.0 => /usr/local/cuda/lib64/libcublas.so.10.0 (0x00007f998c36f000)
undefined symbol: _ZN6google8protobuf8internal10WireFormat22SerializeUnknownFieldsERKNS0_15UnknownFieldSetEPNS0_2io17CodedOutputStreamE	(/home/jimmypan/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so)
undefined symbol: _ZNK6google8protobuf13RepeatedFieldIlE11unsafe_dataEv	(/home/jimmypan/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so)
undefined symbol: _ZN6google8protobuf2io17CodedOutputStream21WriteVarint32SlowPathEj	(/home/jimmypan/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so)
undefined symbol: _ZN6google8protobuf8internal10WireFormat29SerializeUnknownFieldsToArrayERKNS0_15UnknownFieldSetEPh	(/home/jimmypan/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so)
undefined symbol: _ZN3c1014DeviceTypeNameB5cxx11ENS_10DeviceTypeEb	(/home/jimmypan/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so)
undefined symbol: _ZN6google8protobuf2io17CodedOutputStream21WriteVarint64SlowPathEm	(/home/jimmypan/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so)
undefined symbol: _ZN6google8protobuf8internal9ArenaImpl15AllocateAlignedEm	(/home/jimmypan/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so)
undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(/home/jimmypan/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so)
undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(/home/jimmypan/.local/lib/python3.5/site-packages/torch2trt/libtorch2trt.so)

**Comment by shuangshuangguo** [comment]
Your output has many undefined symbols, which is not normal. You should fix the problem first. You can try to update protobuf verison.

**Comment by dedoogong** [comment]
thank you! i faced same issue and solved according to your guide. protobuf version mismatch is the main problem!!
