### ISSUE TITLE
Is torch2trt only available on embedded boards ??? For example, does the RTX2080TI not work properly?

### ISSUE THREAD

**Issue by seominseok0429** [NVIDIA-AI-IOT/torch2trt#299]
Is torch2trt only available on embedded boards ??? For example, does the RTX2080TI not work properly?

best regards.

**Comment by jaybdub** [comment]
Hi seominseok0429,

Thanks for reaching out!

Nope!  torch2trt should work for other NVIDIA systems as well.  I test most heavily on the Jetson series though.

Please let me know if you have any other questions.

Best,
John

**Comment by seominseok0429** [comment]
Can you tell me the tensorRT version and pytorch version of the image segmentation demo in the code?
