### ISSUE TITLE
[TensorRT] ERROR: (Unnamed Layer* 0) [Shuffle]: input and output volume mismatch. input volume is 2408448 and output volume is 150528

### ISSUE THREAD

**Issue by sunnymoon155** [NVIDIA-AI-IOT/torch2trt#309]
I met this error when I was converting TSM(temporal-shift-module) model from pytorch to trt and my input shape is input_shape = (8, 16, 3, 224, 224)

**Comment by chrisHuxi** [comment]
Hi, did you solve it? I got the same issue... @sunnymoon155

**Comment by yzycps** [comment]
same issue, did you solve it? @sunnymoon155 @chrisHuxi

**Comment by chrisHuxi** [comment]
@yzycps not really, sorry
