### ISSUE TITLE
ConvTranspose1d converter

### ISSUE THREAD

**Issue by tambien** [NVIDIA-AI-IOT/torch2trt#311]
It seems like it's possible to create torch.nn.ConvTranspose1d by reshaping the input and output of the torch.nn.ConvTranspose2d converter. I don't have any experience writing converters. Could someone point me in the right direction of how you would do that for this layer? 

Thanks for any help or guidance!

**Comment by jaybdub** [comment]
Hi tambien,

Thanks for reaching out.  We do this for Conv1d, this file might help guide you

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/converters/Conv1d.py#L5

Please let me know if you have any success with this.

Best,
John

**Comment by tambien** [comment]
🙏🏻I'll give this a shot! if it works out, i'll try contributing it back
