### ISSUE TITLE
Dynamic input of torch 2trt

### ISSUE THREAD

**Issue by shaominghe** [NVIDIA-AI-IOT/torch2trt#317]
hi ，i have two question
1.I want to ask torch2trt if it supports dynamic shape input
2.Whether batch dimension modification is supported ,for example: Z.veiw(-1,512)

thank you

**Comment by jaybdub** [comment]
Hi Shaominghe,

Thanks for reaching out!  

Unfortunately, torch2trt does not currently support dynamic input shapes or variable batch dimensions.  

Do you mind sharing your use-case for this?  This helps me better understand where torch2trt is currently useful or and where additional features might be desired :)

Best,
John

**Comment by shaominghe** [comment]
But I think tensorrt7 supports dynamic input and the modification of batch dimension，Because I'm going to do video super-resolution，So I want to support dynamic input.

**Comment by GabbySuwichaya** [comment]
Hi @jaybdub  ... there are multiple areas where the dynamic input dimensions are useful. 
Many CS problems are involved with multi-scale and/or multi-resolution processing. 
Multi-scale processing roots in many fundamental areas such as feature extraction, image enhancing, compression, super resolutions etc...

I am also working in these areas, and I am looking for the tools that supports both deep learning, multi-scale processing. PyTorch model helps me to do all these with ease. 
However, the need to go from PyTorch to TensorRT has to do with minimizing the runtime, while keeping the level of performance.  
Therefore, it would be nice if torch2trt can support dynamic input shapes. 
Or if you have any techniques to go around this, please let me know.
