### ISSUE TITLE
NvInfer.h: no such file or dictionary

### ISSUE THREAD

**Issue by JachinMa** [NVIDIA-AI-IOT/torch2trt#318]
I was running the setup command and faced this problem:

(py) mjx@rootss-System-Product-Name:~/torch2trt-master/torch2trt-master$ python setup.py install --plugins
running install
Building in plugin support
[1/4] protoc torch2trt/converters/inte...olate.proto --cpp_out=. --python_out=.
FAILED: torch2trt/converters/interpolate/interpolate.pb.h torch2trt/converters/interpolate/interpolate.pb.cc torch2trt/converters/interpolate/interpolate_pb2.py
protoc torch2trt/converters/interpolate/interpolate.proto --cpp_out=. --python_out=.
/bin/sh: 1: protoc: not found
[2/4] g++ -c -fPIC torch2trt/converter...c++11 -I/usr/include/aarch64-linux-gnu
FAILED: interpolate.o
g++ -c -fPIC torch2trt/converters/interpolate/interpolate.cpp -I/usr/local/cuda/include -I/home/mjx/anaconda3/envs/py/lib/python3.6/site-packages/torch/include -I/home/mjx/anaconda3/envs/py/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I. -std=c++11 -I/usr/include/aarch64-linux-gnu
torch2trt/converters/interpolate/interpolate.cpp:2:10: fatal error: NvInfer.h: no such file or dictionary
 #include <NvInfer.h>
          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
running build
running build_py
running install_lib
running install_egg_info
running egg_info
writing torch2trt.egg-info/PKG-INFO
writing dependency_links to torch2trt.egg-info/dependency_links.txt
writing top-level names to torch2trt.egg-info/top_level.txt
reading manifest file 'torch2trt.egg-info/SOURCES.txt'
writing manifest file 'torch2trt.egg-info/SOURCES.txt'
removing '/home/mjx/anaconda3/envs/py/lib/python3.6/site-packages/torch2trt-0.0.3-py3.6.egg-info' (and everything under it)
Copying torch2trt.egg-info to /home/mjx/anaconda3/envs/py/lib/python3.6/site-packages/torch2trt-0.0.3-py3.6.egg-info
running install_scripts

what should I do to solve this problem?

**Comment by prathik-naidu** [comment]
I'm getting a similar error

```
torch2trt/plugins/interpolate.cpp:6:10: fatal error: NvInfer.h: No such file or directory
 #include <NvInfer.h>
          ^~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
```

Were you able to figure this out?

**Comment by wzan0001** [comment]
> 
> 
> I'm getting a similar error
> 
> ```
> torch2trt/plugins/interpolate.cpp:6:10: fatal error: NvInfer.h: No such file or directory
>  #include <NvInfer.h>
>           ^~~~~~~~~~~
> compilation terminated.
> error: command 'gcc' failed with exit status 1
> ```
> 
> Were you able to figure this out?

hi, have you solve this problem?

**Comment by Usernamezhx** [comment]
you should change the setup.py file 'include' and 'lib' to the tensorRT`s include and lib. that works for me.

**Comment by qiushuijushi** [comment]
You should configure tensorrt in CMakeLists, adding the following lines:
```cmake
# tensorRT
include_directories(/....../TensorRT-8.0.0.3/include/)
link_directories(/....../TensorRT-8.0.0.3/lib/)
```
