### ISSUE TITLE
Multiple inputs support?

### ISSUE THREAD

**Issue by lawrencekiba** [NVIDIA-AI-IOT/torch2trt#33]
This is more of a question rather than an issue, but does torch2trt support multiple inputs as in a list/dict of tensors?

I've been eyeing torch2trt as an alternative to torch.onnx.export because the latter needs conversion to onnx & also only accepts one dummy_input.

**Comment by jaybdub** [comment]
Hi lawrencekiba,

Thanks for reaching out.

Currently multiple inputs are accepted as a list.  For example,

```python
model_trt = torch2trt(model, [input_0, input_1, input_2])
```

Should work.  If you have something in a dict format, you could consider creating a wrapper PyTorch module that converts from a dict to list, this would likely work as well.

Please let me know if you have any questions.

Best,
John

**Comment by lawrencekiba** [comment]
Ah, that sounds great. For now, I'm good. Will close this one first & proceed to try it out.

Thank you!

**Comment by eriche2016** [comment]
It doesnot work for list of input tensors

**Comment by chasegh** [comment]
Does torch2trt support for dict input now?
