### ISSUE TITLE
No module named 'torch2trt.module_test'

### ISSUE THREAD

**Issue by wangzifu1994** [NVIDIA-AI-IOT/torch2trt#330]
`import torch2trt` works fine, but `from torch2trt import torch2trt` would raise an error:
```
torch2trt/torch2trt/converters/activation.py in <module>()
      1 from torch2trt.torch2trt import *
----> 2 from torch2trt.module_test import add_module_test
      3 from .unary import UnaryModule
      4 
      5 
ModuleNotFoundError: No module named 'torch2trt.module_test'
```

Since `import torch2trt` just works, I also tried `torch2trt.torch2trt(...)` instead of `torch2trt(...)`, but it still raises an error: `AttributeError: module 'torch2trt' has no attribute 'torch2trt'`.

**Comment by abhinavgoel95** [comment]
I have the same problem!

**Comment by sebastian-sz** [comment]
To install the torch2trt you can run 
`python setup.py install` after cloning the repo.
After that you should be able to 
`from torch2trt import torch2trt`

**Comment by dsandii** [comment]
> To install the torch2trt you can run
> `python setup.py install` after cloning the repo.
> After that you should be able to
> `from torch2trt import torch2trt`

This worked for me when trying to use `torch2trt` as a submodule, thank you!

**Comment by pepinu** [comment]
> `import torch2trt` works fine, but `from torch2trt import torch2trt` would raise an error:
> 
> ```
> torch2trt/torch2trt/converters/activation.py in <module>()
>       1 from torch2trt.torch2trt import *
> ----> 2 from torch2trt.module_test import add_module_test
>       3 from .unary import UnaryModule
>       4 
>       5 
> ModuleNotFoundError: No module named 'torch2trt.module_test'
> ```
> 
> Since `import torch2trt` just works, I also tried `torch2trt.torch2trt(...)` instead of `torch2trt(...)`, but it still raises an error: `AttributeError: module 'torch2trt' has no attribute 'torch2trt'`.

The problem comes from the name collision of package and function. 
you cannot have 
```
import torch2trt
from torch2trt import torch2trt
```
 in the same script, it results in an error.

**Comment by wangzifu1994** [comment]
> > `import torch2trt` works fine, but `from torch2trt import torch2trt` would raise an error:
> > ```
> > torch2trt/torch2trt/converters/activation.py in <module>()
> >       1 from torch2trt.torch2trt import *
> > ----> 2 from torch2trt.module_test import add_module_test
> >       3 from .unary import UnaryModule
> >       4 
> >       5 
> > ModuleNotFoundError: No module named 'torch2trt.module_test'
> > ```
> > 
> > 
> > Since `import torch2trt` just works, I also tried `torch2trt.torch2trt(...)` instead of `torch2trt(...)`, but it still raises an error: `AttributeError: module 'torch2trt' has no attribute 'torch2trt'`.
> 
> The problem comes from the name collision of package and function.
> you cannot have
> 
> ```
> import torch2trt
> from torch2trt import torch2trt
> ```
> 
> in the same script, it results in an error.

**Comment by wangzifu1994** [comment]
I have the above issue when I use some un-verified commits. I think the problem is already solved.
