### ISSUE TITLE
ModuleNotFoundError: No module named 'torch2trt.plugins'

### ISSUE THREAD

**Issue by SpencerJack** [NVIDIA-AI-IOT/torch2trt#336]
Hi - Thanks in advance!

I've installed torch2trt as follows:
git clone https://github.com/NVIDIA-AI-IOT/trt_pose
cd trt_pose
sudo python3 setup.py install

Through a terminal opening python3 i can do the following - HOORAY!

>>> import torch2trt
>>> print(torch2trt.__file__)
/home/user/torch2trt/torch2trt/__init__.py

However when I run my script which imports torch2trt i get the following message:

>>> import torch2trt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/__init__.py", line 14, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/__init__.py", line 7, in load_plugins
ModuleNotFoundError: No module named 'torch2trt.plugins'

Please help my NOOBNESS!

**Comment by jaybdub** [comment]
Hi SpencerJack,

Thanks for reaching out!

Could you try installing with ``--plugins`` flag?

```bash
python3 setup.py install --plugins
```

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by jaybdub** [comment]
Just fixed this issue in this pull request

https://github.com/NVIDIA-AI-IOT/torch2trt/pull/337

You can also try pulling from master and installing.

Best,
John

**Comment by SpencerJack** [comment]
Cheers guys!
