### ISSUE TITLE
TypeError: torch.int64 is not supported by tensorrt

### ISSUE THREAD

**Issue by arijitx** [NVIDIA-AI-IOT/torch2trt#345]
TensorRT doesn't support int64 but in pytorch Embedding layers only work with LongTensors, any workaround for that ?

**Comment by jaybdub** [comment]
Hi arijitx,

Thanks for reaching out!

There may be, I'm not sure at the moment, I don't have much experience with these layers.

Are you able to share an example use case / PyTorch module?

Best,
John

**Comment by zhm9484** [comment]
Same issue for me. 
Is there any solution?
Thanks!

**Comment by arijitx** [comment]
@jaybdub thanks for the response, I found that for Tensorrt7+ it automatically tries to cast any INT64 to INT32. That will solve this issue.

**Comment by zonglin** [comment]
@arijitx Hi, can you tell me which version of tensorrt do you use now? I use the tensorrt 7.0018, but i still have this problem.

**Comment by EphChem** [comment]
+1

**Comment by wenHK** [comment]
+1

**Comment by paulpig** [comment]
@arijitx @zonglin how to solve this problem？

**Comment by Fan9** [comment]
i have this problem with tensorrt 7.2.1

**Comment by iAlexKai** [comment]
Me, too with tensorrt 7.1.3.0

**Comment by iAlexKai** [comment]
I must use the Embedding layer and LongTensors.
Has any found any solution for this?

**Comment by iAlexKai** [comment]
I've found it.
Just update pytorch to 1.8.0+, which supports int32 input to embedding.

**Comment by q2044757581** [comment]
@iAlexKai 
with torch==1.8.1 tensorrt=7.2.2.3
but it still ypeError: torch.int64 is not supported by tensorrt
how can i solve it

**Comment by iAlexKai** [comment]
torch==1.8.1 is the first version that supports int32 input for embedding.
But torch.int64 is still NOT SUPPORT by tensorrt.
You can modify your tensor to torch.int32
