### ISSUE TITLE
succeed in Python, but no libtorch2trt.so generated

### ISSUE THREAD

**Issue by zhulinzhang** [NVIDIA-AI-IOT/torch2trt#348]
I wanna deserialize the engine using TensorRT C++ API. However, after following the instructions, all is well in Python. But no libtorch2trt.so is generated, does anyone have solution?

**Comment by zhulinzhang** [comment]
@jaybdub thanks

**Comment by jaybdub** [comment]
Hi zhulinzhang,

Thanks for reaching out!

The build for plugins has changed to use PyTorch's C++ extension building utility.  libtorch2trt.so is no longer created.  Different steps may be required to link against the plugin library in C++.

Does your model use an interpolation layer?  If you update to TensorRT 7.1 + it's likely you can avoid this by using the native TensorRT interpolation layer.

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by bitwangdan** [comment]
> Hi zhulinzhang,
> 
> Thanks for reaching out!
> 
> The build for plugins has changed to use PyTorch's C++ extension building utility. libtorch2trt.so is no longer created. Different steps may be required to link against the plugin library in C++.
> 
> Does your model use an interpolation layer? If you update to TensorRT 7.1 + it's likely you can avoid this by using the native TensorRT interpolation layer.
> 
> Please let me know if this helps or you run into any issues.
> 
> Best,
> John
hi, My TensorRT is 7.0 and in that case, how can I use the interpolation layer?
