### ISSUE TITLE
Problem in deserializing the engine

### ISSUE THREAD

**Issue by adamwolff2** [NVIDIA-AI-IOT/torch2trt#371]
Hi,

I create an TRT model with your example code (alexnet) and save the engine with the following command:

```
with open('/tmp/trt.engine','wb') as f: 
    f.write(model_trt.engine.serialize())
```

However, when trying to load the engine in cpp I get the following error:
`loadtrt: engine.cpp:868: bool nvinfer1::rt::Engine::deserialize(const void*, std::size_t, nvinfer1::IGpuAllocator&, nvinfer1::IPluginFactory*): Assertion size >= bsize && "Mismatch between allocated memory size and expected size of serialized engine."' failed.`

Can you help with that?

Thanks,
Adam

**Comment by jaybdub** [comment]
Hi Adamwolff2,

Thanks for reaching out!

I'm not sure immediately what the cause would be, I may need to reproduce the issue.

Do you mind sharing the following information

1. Device (ie: Jetson Nano, GTX 1080ti, etc.)
2. PyTorch version
3. TensorRT version
4. Torchvision version

Best,
John

**Comment by adamwolff2** [comment]
Problem solved. It was caused by incompatibility between tensorrt versions
