### ISSUE TITLE
Does anyone try to convert MobileNet?

### ISSUE THREAD

**Issue by G-Bong** [NVIDIA-AI-IOT/torch2trt#386]
Hello

I am trying to convert mobilenet.pth to trt model with tutorial codes.
But I stuck with the following errors.
>[INFO] Beginning ONNX file parsing
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[INFO] Completed parsing of ONNX file
[INFO] Building an engine...
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.

My code for onnx to trt is
```python
import os
import sys
c_folder = os.path.abspath(os.path.dirname(__file__))
p_folder = os.path.abspath(os.path.dirname(c_folder))
sys.path.append(c_folder)
sys.path.append(p_folder)

import argparse
import tensorrt as trt


def fp16_convert_main(args):
    """trt settings"""
    TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
    builder = trt.Builder(TRT_LOGGER)
    # network_flags = 0
    if args['explicit_precision']:
        network_flags = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_PRECISION)
    if args['explicit_batch']:
        network_flags = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    
    # explicit_batch = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    network = builder.create_network(network_flags)
    trt_parser = trt.OnnxParser(network, TRT_LOGGER)
 
    """Parse ONNX"""
    with open(args['onnx_file_path'], 'rb') as onnx_model:
        print('[INFO] Beginning ONNX file parsing')
        trt_parser.parse(onnx_model.read())
    print('[INFO] Completed parsing of ONNX file')

    """allow TensorRT to use up to 1GB of GPU memory for tactic selection"""
    builder.max_workspace_size = 1 << 30

    """we have only one image in batch"""
    builder.max_batch_size = 1

    """select FP16 mode if possible"""
    if builder.platform_has_fast_fp16:
        builder.fp16_mode = True

    """generate TensorRT engine optimized for the target platform"""
    print('[INFO] Building an engine...')
    last_layer = network.get_layer(network.num_layers - 1)
    if not last_layer.get_output(0):
        network.mark_output(last_layer.get_output(0))
    engine = builder.build_cuda_engine(network)
    context = engine.create_execution_context()
    print("[INFO] Completed creating Engine")

    """save built engine"""
    folder_path = os.path.split(args['trt_engine_save_path'])[0]
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    with open(args['trt_engine_save_path'], 'wb') as f:
        f.write(engine.serialize())

    return None


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--onnx_file_path", default=os.path.join(c_folder, 'mobilenet0.25_Final.onnx'), type=str, help='Path of the onnx file.')
    parser.add_argument("--trt_engine_save_path", default=os.path.join(c_folder, 'mobilenet0.25_Final.trt'))
    parser.add_argument("--select_mode", default="fp16", type=str, help="Select mode type of trt engine. (Currently, only fp16 is available.)")
    parser.add_argument("--explicit_batch", default=True, help="Set trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH.")
    parser.add_argument("--explicit_precision", default=False, help="Set trt.NetworkDefinitionCreationFlag.EXPLICIT_PRECISION.")
    args = vars(parser.parse_args())

    fp16_convert_main(args)
```

During online searching, I found this github and asking.

Does anyone tried to convert mobilenet with torch2trt API?

**Comment by jaybdub** [comment]
Hi G-Bong,

Thanks for reaching out!

I've tested MobilenetV2 successfully, before, I'd give it a try.

Please let me know if it works for you or you run into issues (perhaps there is a workaround / fix in this case).

Best,
John
