### ISSUE TITLE
I got an error with torch.nn.functional.interpolate

### ISSUE THREAD

**Issue by G-Bong** [NVIDIA-AI-IOT/torch2trt#387]
With torch2trt API, I got an error as follow.
>Warning: Encountered known unsupported method torch.nn.functional.interpolate
[TensorRT] ERROR: (Unnamed Layer* 94) [Scale]: shift weights has count 64 but 1 was expected

Is there any solution?

**Comment by jaybdub** [comment]
Hi G-Bong,

Thanks for reaching out.

Do you mind sharing which version of TensorRT you're using?  If it's less than 7.1 I would recommend installing torch2trt with plugins.

```bash
cd torch2trt
sudo python3 setup.py install --plugins
```

Please let me know if this helps or you run into issues.

Best,
John

**Comment by G-Bong** [comment]
@jaybdub really thanks for your reply.
First, I would like to give the information you asked me.
> I am using *nvcr.io/nvidia/tensorrt:20.03-py3*
and it contains:
NVIDIA CUDA 10.2.89
TensorRT 7.0.0

In the last late-night, I installed the API with plugins you mentioned, and I got success on conversion of MobileNet.
However, I got a question.
The size of model has been changed from 1.731MB to 11.338 MB.
Is it normal??

**Comment by G-Bong** [comment]
@jaybdub 
Hello again.
With converted  MobileNet model with torch2trt, the model doesn't have the performance as before.

**Comment by Zhang-O** [comment]
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Traceback (most recent call last):
  File "/data/zhangyl/psenet_common_detector/torch2rt.py", line 23, in <module>
    model_trt = torch2trt(model, [x])
  File "/data/tools/anaconda3/envs/yinlei/lib/python3.5/site-packages/torch2trt-0.1.0-py3.5.egg/torch2trt/torch2trt.py", line 506, in torch2trt
  File "/data/tools/anaconda3/envs/yinlei/lib/python3.5/site-packages/torch2trt-0.1.0-py3.5.egg/torch2trt/torch2trt.py", line 372, in mark_outputs
AttributeError: 'Tensor' object has no attribute '_trt'

I have no idea what happened?
