### ISSUE TITLE
Cannot install with plugins

### ISSUE THREAD

**Issue by smell-fishy** [NVIDIA-AI-IOT/torch2trt#41]
Hello, I like this awesome repository and it will be very helpful, but I have some trouble in installing it.
When I tried to install: python setup.py install --plugins
it gived:
![creenshot_20190815211539](https://user-images.githubusercontent.com/34292353/63097052-015d2700-bfa2-11e9-8f2d-375817a6af83.png)
And then i can not convert model with torch.nn.functional.interpolate.

**Comment by jaybdub** [comment]
Hi smelly-fishy,

Thanks for reaching out!

Could you try adding ``-std=c++11`` to this line

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/b9a2c3f6f2be432f3caee07cca4a065d60328b72/build.py#L21

So it would read

```python
  command = g++ -c -fPIC $$in -I$cuda_dir/include -I$torch_dir/include -I$torch_dir/include/torch/csrc/api/include -I. -std=c++11
```

Please let me know if this works for you.

Best,
John

**Comment by smell-fishy** [comment]
> Hi smelly-fishy,
> 
> Thanks for reaching out!
> 
> Could you try adding `-std=c++11` to this line
> 
> https://github.com/NVIDIA-AI-IOT/torch2trt/blob/b9a2c3f6f2be432f3caee07cca4a065d60328b72/build.py#L21
> 
> So it would read
> 
> ```python
>   command = g++ -c -fPIC $$in -I$cuda_dir/include -I$torch_dir/include -I$torch_dir/include/torch/csrc/api/include -I. -std=c++11
> ```
> 
> Please let me know if this works for you.
> 
> Best,
> John

Thank you!
I added the command but now it gives:
![WeChat Screenshot_20190816085418](https://user-images.githubusercontent.com/34292353/63136315-ffc44b00-c003-11e9-9976-9a65bbdb20d5.png)

**Comment by smell-fishy** [comment]
Hi, I solved the problem.It is the problem about protobuf version. I changed my protobuf from 2.6.1 to 3.9.1 and I installed successfully. But when i tried to convert my model,it gives:
![WeChat Screenshot_20190816104008](https://user-images.githubusercontent.com/34292353/63139922-aa436a80-c012-11e9-8fe2-0c9d4c8f4298.png)

**Comment by smell-fishy** [comment]
Thanks! This issue is the same as #20

**Comment by jaybdub** [comment]
Good to know!  Thanks for sharing.

Best,
John
