### ISSUE TITLE
error on : model_trt = torch2trt(model, [data], fp16_mode=True)

### ISSUE THREAD

**Issue by diamondbarcode** [NVIDIA-AI-IOT/torch2trt#413]
When i try to run : " model_trt = torch2trt(model, [data], fp16_mode=True)  " in jetracer " road_following.ipynb i got bellow error ..

Can anyone advise how to fix this? I use the latest pull of projects. 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-dd315960311d> in <module>
      3 data = torch.zeros((1, 3, 224, 224)).cuda().half()
      4 
----> 5 model_trt = torch2trt(model, [data], fp16_mode=True)

/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py in torch2trt(module, inputs, input_names, output_names, log_level, max_batch_size, fp16_mode, max_workspace_size, strict_type_constraints, keep_network, int8_mode, int8_calib_dataset, int8_calib_algorithm, int8_calib_batch_size, use_onnx)
    500             ctx.add_inputs(inputs, input_names)
    501 
--> 502             outputs = module(*inputs)
    503 
    504             if not isinstance(outputs, tuple) and not isinstance(outputs, list):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py in forward(self, x)
    153         x = self.maxpool(x)
    154 
--> 155         x = self.layer1(x)
    156         x = self.layer2(x)
    157         x = self.layer3(x)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py in forward(self, input)
     95     def forward(self, input):
     96         for module in self._modules.values():
---> 97             input = module(input)
     98         return input
     99 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py in forward(self, x)
     53             identity = self.downsample(x)
     54 
---> 55         out += identity
     56         out = self.relu(out)
     57 

/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py in wrapper(*args, **kwargs)
    281 
    282             #             print('%s' % (converter.__name__,))
--> 283             converter["converter"](ctx)
    284 
    285             # convert to None so conversion will fail for unsupported layers

/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/add.py in convert_add(ctx)
     12     output = ctx.method_return
     13     input_a_trt, input_b_trt = add_missing_trt_tensors(ctx.network, [input_a, input_b])
---> 14     input_a_trt, input_b_trt = broadcast_trt_tensors(ctx.network, [input_a_trt, input_b_trt], output.ndim - 1)
     15     layer = ctx.network.add_elementwise(input_a_trt, input_b_trt, trt.ElementWiseOperation.SUM)
     16     output._trt = layer.get_output(0)

AttributeError: 'Tensor' object has no attribute 'ndim'

**Comment by jaybdub** [comment]
Hi chealyte,

Thanks for reaching out!

I believe ndim is not available in older versions of PyTorch, so one method to resolve this error may be to update to a later version of PyTorch (I Believe 1.3+)

Or, you could you try this older commit of torch2trt

https://github.com/NVIDIA-AI-IOT/torch2trt/commit/3ddd70d7cb7074ed204bd77205ab8f6515e06312

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by chealyte** [comment]
how to use older commit, sorry i am new to this.

**Comment by jaybdub** [comment]
No problem.

First, change directories to torch2trt

```bash
cd torch2trt
```

Next, checkout the older commit

```bash
git checkout 3ddd70d
```

Finally, re-install torch2trt

```bash
sudo python3 setup.py install
```

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by chealyte** [comment]
I run a few updates on PyTorch and the problems are gone, however, does it work properly or not I would not know.
