### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorrt'

### ISSUE THREAD

**Issue by Mohamed209** [NVIDIA-AI-IOT/torch2trt#414]
`File "/opt/conda/lib/python3.7/site-packages/torch2trt-0.1.0-py3.7.egg/torch2trt/torch2trt.py", line 2, in <module>
ModuleNotFoundError: No module named 'tensorrt'` i got this error , although tensorrt is installed and i ran this command `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/src/tensorrt/`

**Comment by jaybdub** [comment]
Hi Mohamed209,

Thanks for reaching out!

Do you mind sharing which platform you're using (ie: Jetson Nano, Desktop w. GTX1080, etc.).  As well as steps you took to install TensorRT

Best,
John

**Comment by Mohamed209** [comment]
I am targeting nvidia p100 gpu on ubutnu
Here are all the steps used
`!wget -O nv-tensorrt-repo-ubuntu1804-cuda10.0-trt5.1.2.2-rc-20190227_1-1_amd64.deb https://www.dropbox.com/s/45pz13r4e8ip4bl/nv-tensorrt-repo-ubuntu1804-cuda10.0-trt5.1.2.2-rc-20190227_1-1_amd64.deb?dl=0
!dpkg -i nv-tensorrt-repo-ubuntu1804-cuda10.0-trt5.1.2.2-rc-20190227_1-1_amd64.deb
!apt-key add /var/nv-tensorrt-repo-cuda10.0-trt5.1.2.2-rc-20190227/7fa2af80.pub
!apt-get update
!apt-get install -y python3-libnvinfer-dev
!apt-get install -y --allow-downgrades --no-install-recommends libnvinfer5=5.1.2-1+cuda10.0
!apt-get install -y --allow-downgrades --no-install-recommends libnvinfer-dev=5.1.2-1+cuda10.0
!apt-get install -y tensorrt
!apt-get install -y uff-converter-tf
!dpkg -l | grep TensorRT`
Last command correctly lists that tensorrt is installed

**Comment by ingura** [comment]
What is the solution to this problem? I am in the same situation after installing tensorrt  using pip3 install tensorrt
