### ISSUE TITLE
throughput can be reproduced  on tensorRT，but throughput can‘t  be reproduced  on  pytorch

### ISSUE THREAD

**Issue by wangxiangq** [NVIDIA-AI-IOT/torch2trt#416]
hi，i run the torch2trt on jetson nano，the result is as follows：
 Name | Data Type | Input Shapes | torch2trt kwargs | Max Error | Throughput (PyTorch) | Throughput (TensorRT) | Latency (PyTorch) | Latency (TensorRT) |
| torch2trt.tests.torchvision.classification.resnet18 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 6.84E-03 | **15.2** | 92 | 65.7 | 11.3 |
| torch2trt.tests.torchvision.classification.resnet34 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 1.88E-01 | **6.27** | 51 | 159 | 20.1 |
| torch2trt.tests.torchvision.classification.resnet50 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 6.25E-02 | **7.29** | 31.6 | 137 | 30.1 |
| torch2trt.tests.torchvision.classification.resnet101 | float16 | [(1, 3, 224, 224)] | {'fp16_mode': True} | 0.00E+00 | **3.03** | 18.3 | 328 | 50.8 |
                 
but throughput from NVIDIA-AI-IOT/torch2trt is as follows

![image](https://user-images.githubusercontent.com/38305771/93309065-a72e3580-f835-11ea-9dcd-65ab574c8cb3.png)

i don't know why.
Any clues will be appreciated.

**Comment by jaybdub** [comment]
Hi wangxiangq,

Thanks for reaching out!

Hmm, I'm not sure why this is.  Do you mind sharing

* PyTorch Version
* torchvision version
* JetPack version for Jetson Nano
* power mode of Jetson Nano (by calling ``sudo nvpmodel -q``)
* If you called ``jetson_clocks`` or not

Best,
John

**Comment by jaybdub** [comment]
Also it may help to try profiling with nvprof and providing the log

```python
torch.cuda.profiler.init(‘model.nvvp’, output_mode=‘csv’)
# collect region using context manager
torch.cuda.current_stream().synchronize()
with torch.cuda.profiler.profile():
    y = model(x)
torch.cuda.current_stream().synchronize()
```

This will dump the kernel calls/timings in a format for use with [Nvidia Visual Profiler](https://developer.nvidia.com/nvidia-visual-profiler).

It may provide some insights if you provide that here.

> FYI, you can find more profiling tips in this [webinar](https://developer.nvidia.com/gtc/2020/video/s22676) if it interests you.

Best,
John

**Comment by wangxiangq** [comment]
> * jetson_clocks
hi John jaybdub,
thanks a lot for your advice.
the environment as follows:

Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchvision
>>> print(torch.__version__)
**1.6.0**
>>> print(torchvision.__version__)
**0.7.0**a0+78ed10c
>>> 
**jetPack version**
 head -n 1 /etc/nv_tegra_release
# R32 (release), REVISION: 4.3, GCID: 21589087, BOARD: t210ref, EABI: aarch64, DATE: Fri Jun 26 04:38:25 UTC 2020
**sudo nvpmodel -q i**s as follows：
NVPM WARN: fan mode is not set!
NV Power Mode: MAXN
0
sudo jetson_clocks  is also done.

it's strange for me. because the throughput on tensorRT can be reproduced but can't reproduced on pytorch.
