### ISSUE TITLE
not support hard-tanh?

### ISSUE THREAD

**Issue by yhkim8412** [NVIDIA-AI-IOT/torch2trt#417]
hi, 

I use hard-tanh to replace ReLU8 but failed, is that can not support for hard-tanh?

Best,
Kim

**Comment by jaybdub** [comment]
Hi yhkim8412,

Thanks for reaching out!

It should be relatively straight forward to support [hard-tanh](https://pytorch.org/docs/stable/generated/torch.nn.Hardtanh.html#hardtanh) using the TensorRT [clip activation](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Layers.html#iactivationlayer).

Can you try adding the following _custom converter_ by executing the code below before calling torch2trt

```python
@tensorrt_converter('torch.nn.functional.hardtanh')
def convert_hardtanh(ctx):
    input = get_arg(ctx, 'input', pos=0, default=None)
    min_val = get_arg(ctx, 'min_val', pos=1, default=-1.0)
    max_val = get_arg(ctx, 'max_val', pos=2, default=1.0)
    output = ctx.method_return
    
    layer = ctx.network.add_activation(input._trt, trt.ActivationType.CLIP)
    layer.alpha = min_val
    layer.beta = max_val
    
    output._trt = layer.get_output(0)
```

I haven't yet had the chance to test this. 

Please let me know if you run into issues or have any questions.  If it works, I'll look towards testing / merging in master.

Best,
John

**Comment by samiit** [comment]
Thanks for the suggestion. Any idea how I could convert Hardswish in a similar way? what should be the type for this?

Thanks,
Sam
