### ISSUE TITLE
How to use Efficientnet

### ISSUE THREAD

**Issue by hjlee9182** [NVIDIA-AI-IOT/torch2trt#422]
I want to use Efficientnet.
But When that makes error.

[ TensorRT ] ERROR : INVALID_ARGUMENT: Can not find binding of given name.

How to solve this problem ?

**Comment by CryptoSalamander** [comment]
I encountered this issue too.
did you resolve it?

**Comment by hjlee9182** [comment]
@CryptoSalamander Nope.... please solve this problem... :)

**Comment by CryptoSalamander** [comment]
@hjlee9182 I'm struggling now.
좋은 결과 있으면 공유하겠습니다!

**Comment by 421psh** [comment]
I have the same problem. https://github.com/NVIDIA-AI-IOT/torch2trt/pull/273 helped to convert a model, but [TensorRT] ERROR: INVALID_ARGUMENT error appears and the result is constant. Maybe some layers need their own converters.

**Comment by hjlee9182** [comment]
@421psh 
so you success running 'EfficientNet'?

**Comment by CryptoSalamander** [comment]
I tried efficientnet with "geffnet" library that can be installed by pip.
you can export geffnet based model to onnx.
and convert this onnx file to tensorrt.
if you want to use torch2trt on efficientnet, you should develop converter for Swishme and Conv2dSamepadding.
Try with torch -> onnx -> trt

**Comment by hjlee9182** [comment]
@CryptoSalamander 
So you said 
Make Efficientnet torch-> onnx Using "geffnet"
and onnx to trt Using torch2trt?

**Comment by CryptoSalamander** [comment]
@hjlee9182 Yes. if you want, I can give you sample code.

**Comment by hjlee9182** [comment]
@CryptoSalamander 
If you give to me sample code, I really love that. :)

**Comment by hjlee9182** [comment]
@CryptoSalamander 
Did you experience 
- ' NoneType' object has no attribute 'get_binding_indx' - error?
