### ISSUE TITLE
KeyError: 'engine'

### ISSUE THREAD

**Issue by mfruhner** [NVIDIA-AI-IOT/torch2trt#427]
Hello,
I am trying to convert a Resnet 34 (trained with fastai) to TRT on a Jetson TX2 using the pytorch l4t docker container.
When executing the 'load' command from the Readme:

`model_trt.load_state_dict(torch.load(model_path))`

I get the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-35e32700ec9d> in <module>
----> 1 model_trt.load_state_dict(torch.load(model_path))

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1028                     load(child, prefix + name + '.')
   1029 
-> 1030         load(self)
   1031         load = None  # break load->load reference cycle
   1032 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in load(module, prefix)
   1023             local_metadata = {} if metadata is None else metadata.get(prefix[:-1], {})
   1024             module._load_from_state_dict(
-> 1025                 state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
   1026             for name, child in module._modules.items():
   1027                 if child is not None:

/usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py in _load_from_state_dict(self, state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
    402         error_msgs,
    403     ):
--> 404         engine_bytes = state_dict[prefix + "engine"]
    405 
    406         with trt.Logger() as logger, trt.Runtime(logger) as runtime:

KeyError: 'engine'
```

Do you have an idea why this happens?
thanks!

**Comment by mfruhner** [comment]
Nvm, I did it wrong, sorry.

**Comment by iAlexKai** [comment]
I got this bug, too. How did you solve it, buddy?

**Comment by iAlexKai** [comment]
> Nvm, I did it wrong, sorry.

I've got this bug recently, could you please tell me how you solved this?

**Comment by TianZhenGG** [comment]
> I got this bug, too. How did you solve it, buddy?

{"engine":torch.load...}

**Comment by dinhphuong98** [comment]
> Nvm, I did it wrong, sorry.

Hi, i am facing the problem. Could you share me how to solved this? thank you so much.

**Comment by mfruhner** [comment]
I am very sorry, i don't remember how i solved this. I moved on to Nvidia DeepStream.
Sorry, never meant to write such an answer ...

**Comment by cscid** [comment]
Please check the model path. Check if you have given the directory which has the pth and the engine file inside it.

**Comment by Imamabdulfatah** [comment]
you try your model save    example trt model torch.save(model_trt.state_dict(), 'road_follow_trt.pth')
