### ISSUE TITLE
How to install torch2trt on colab

### ISSUE THREAD

**Issue by weweew1** [NVIDIA-AI-IOT/torch2trt#436]
cd $HOME

git clone https://github.com/NVIDIA-AI-IOT/torch2trt

cd torch2trt

sudo python3 setup.py install
python3: can't open file 'setup.py': [Errno 2] No such file or directory

last code is error
![擷取](https://user-images.githubusercontent.com/73685024/97723711-0b1b6d80-1b07-11eb-8653-08a6040e1417.PNG)
But there is setup.py in my torch2trt folder
Please help me to slove this problem thk!

**Comment by peasant98** [comment]
Hi, what's the output of 
```sh
ls
```
after 

```sh
cd torch2trt
```
?

**Comment by peasant98** [comment]
@weweew1

**Comment by weweew1** [comment]
@peasant98 Hi  The problem was solved thk!!

**Comment by Ratansairohith** [comment]
@weweew1 Hey how do you resolved the issue?? I was facing the same problem. Hope you put some light on this issue. 
-Thank you

**Comment by CyberMaryVer** [comment]
for @Ratansairohith and for somebody who encountered the same problem, here is a solution: 
`python3 /content/torch2trt/setup.py install`

in google colab cd command doesn't work this way, so you need to indicate full path or to do this
`import os
os.chdir('/content/torch2trt/')`
