### ISSUE TITLE
[TensorRT] ERROR: [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis

### ISSUE THREAD

**Issue by smell-fishy** [NVIDIA-AI-IOT/torch2trt#44]
Hi, 
When i tried to convert my model, it gived:
![WeChat Image_20190816144249](https://user-images.githubusercontent.com/34292353/63148569-2c905680-c034-11e9-99e3-ff4eb978e14c.png)
And i am sure that it is not the problem of the model because when i run:

    x=model(sample)
    model_trt = torch2trt(model, [sample])

it didn't report error in first line but did in second line.
Is it the problem in TensorRT?

**Comment by jaybdub** [comment]
Hi smell-fishy,

It could be a limitation or a perhaps an issue in torch2trt.  It may depend on what data format is provided, or the model converter.

I will likely need to debug the issue.

Are you able to share the model architecture that you're using?   (I don't need the weights).

Best,
John

**Comment by jaybdub** [comment]
Thanks, I'll try to take a look soon.

Just to clarify, is it the class PoolNet that is defined here

https://github.com/backseason/PoolNet/blob/master/networks/poolnet.py#L115

Best,
John

**Comment by smell-fishy** [comment]
Yes, and 
the base_model_cfg == 'resnet'
Thank you very much!

**Comment by smell-fishy** [comment]
Sorry! It is the class PoolNet defined here 
https://github.com/backseason/PoolNet/blob/master/networks/joint_poolnet.py#L172
And I remove the mode from the input and rewrite the forward as:

    def forward(self, x):
        mode = 1
        x_size = x.size()
        conv2merge, infos = self.base(x)
        if self.base_model_cfg == 'resnet':
            conv2merge = self.convert(conv2merge)
        conv2merge = conv2merge[::-1]

        edge_merge = []
        merge = self.deep_pool[0](conv2merge[0], conv2merge[1], infos[0])
        edge_merge.append(merge)
        for k in range(1, len(conv2merge)-1):
            merge = self.deep_pool[k](merge, conv2merge[k+1], infos[k])
            edge_merge.append(merge)

        if mode == 0:
            edge_merge = [self.block[i](kk) for i, kk in enumerate(edge_merge)]
            merge = self.fuse(edge_merge, x_size)
        elif mode == 1:
            merge = self.deep_pool[-1](merge)
            edge_merge = [self.block[i](kk).detach() for i, kk in enumerate(edge_merge)]
            edge_merge = self.edgeinfo(edge_merge, merge.size())
            merge = self.score(torch.cat([merge, edge_merge], dim=1), x_size)
        return merge

**Comment by jaybdub** [comment]
Hi smell-fishy,

A couple things I noticed that were causing problems.  

### Issue 1 - ``torch.add`` was not registered.  

We already have this converter it was just not registered for ``torch.add`` specifically (insteal ``torch.Tensor.__add__``.  

I will register it soon, you can add it easily by calling this before calling ``torch2trt``

```python
import torch2trt
import tensorrt as trt

@torch2trt.tensorrt_converter('torch.add')
def convert_add(ctx):
    input_a = ctx.method_args[0]
    input_b = ctx.method_args[1]
    output = ctx.method_return
    layer = ctx.network.add_elementwise(input_a._trt, input_b._trt, trt.ElementWiseOperation.SUM)
    output._trt = layer.get_output(0)
```

### Issue 2 - PoolNet returns format (Tensor, [Tensor, Tensor, ...])

torch2trt only supports single Tensor outputs, or a tuple or List of Tensors, but not nested Tensors.

I modified the return statement of ``PoolNet.forward`` to circumvent this issue like

```python
        return [merge[0]] + merge[1]
```

Which will flatten the outputs into one list


### Issue 3 - Converted AdaptiveAvgPool2d incorrect dimensions (I believe)

After these fixes, I witnessed the concatenation error you mentioned.

I believe the ``AdaptiveAvgPool2d`` converter creating an output dimension that differs from torch.  This has been tested primarily for pooling to divisible factors of the original spatial input dimensions.  My guess, is that this assumption is not true for this model.  

One option is to use the interpolate plugin which will do adaptive_avg_pool_2d if mode='area' is set.  You can do this by replacing references to AdaptiveAvgPool2d with the following module

```python
class AdaptiveAvgPool2d_Interpolate(torch.nn.Module):
    def __init__(self, size):
        super(AdaptiveAvgPool2d_Interpolate, self).__init__()
        if not isinstance(size, tuple) and not isinstance(size, list):
            self.size = (size,)
        else:
            self.size = size
    def forward(self, x):
        return F.interpolate(x, size=self.size, mode='area')
```

This will use the interpolate plugin.

Please note, it seems on some Jetson platforms there is a resource exhausted error when using interpolate.  I believe this is patched in more recent pushes to PyTorch, but I am not certain.  

I believe the breaking reference to ``AdaptiveAvgPool2d`` was in the ``deeplab_resnet.py`` file in ``ResNet_locate``.

I haven't been able to successfully convert yet due to the exhausted resources error, could you try these steps on your platform to see if this is the case?

Please let me know if you have any questions.

Best,
John

**Comment by smell-fishy** [comment]
Hi, John.
Thank you for your reply! It is very helpful!
But I think I get the same error as you mentioned:
![WeChat Image_20190819091739](https://user-images.githubusercontent.com/34292353/63233344-43b48b80-c262-11e9-809f-e7d7ef2a6f64.png)

**Comment by smell-fishy** [comment]
Would you have any advices for this problem？Thanks！

**Comment by smell-fishy** [comment]
Hi, John.
I modify AdaptiveAvgPool2d to AvgPool2d specially for 40*23 input. And I sure it can produce the same spatial size as I want:
![WeChat Image_20190819145811](https://user-images.githubusercontent.com/34292353/63245140-eafce700-c291-11e9-8ea7-a07a1962801b.png)
So I modify the code in the deeplab_resnet.py file in ResNet_locate:
![WeChat Screenshot_20190819150040](https://user-images.githubusercontent.com/34292353/63245266-55158c00-c292-11e9-9b8b-48d05b303073.png)
to:
![WeChat Screenshot_20190819150336](https://user-images.githubusercontent.com/34292353/63245344-9443dd00-c292-11e9-91e8-1a8b749efd64.png)
But it still gives:
![WeChat Screenshot_20190819150514](https://user-images.githubusercontent.com/34292353/63245447-cc4b2000-c292-11e9-8c18-ea3a1a851eca.png)
Do you have any advices?Thanks!

**Comment by jaybdub** [comment]
Hi smell-fishy,

Seems like there is still some dimension mismatch, perhaps elsewhere.  Unfortunately I won't have time to look at this for the next couple of days.

My suggestion would be to add a breakpoint

```python
import pdb
pdb.set_trace()
```

In the concatenation converter here

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/converters/cat.py#L6

This will get called whenever a concatenation is encountered.  You can check the dimensions of the inputs in both torch and tensorrt (by calling ``p input.shape`` and ``p input._trt.shape`` in debugger) to see if there is an obvious mismatch, which would be the first step.

Please let me know if you have any questions.

Best,
John

**Comment by kawa23** [comment]
> Hi smell-fishy,
> 
> A couple things I noticed that were causing problems.
> 
> ### Issue 1 - `torch.add` was not registered.
> We already have this converter it was just not registered for `torch.add` specifically (insteal `torch.Tensor.__add__`.
> 
> I will register it soon, you can add it easily by calling this before calling `torch2trt`
> 
> ```python
> import torch2trt
> import tensorrt as trt
> 
> @torch2trt.tensorrt_converter('torch.add')
> def convert_add(ctx):
>     input_a = ctx.method_args[0]
>     input_b = ctx.method_args[1]
>     output = ctx.method_return
>     layer = ctx.network.add_elementwise(input_a._trt, input_b._trt, trt.ElementWiseOperation.SUM)
>     output._trt = layer.get_output(0)
> ```
> 
> ### Issue 2 - PoolNet returns format (Tensor, [Tensor, Tensor, ...])
> torch2trt only supports single Tensor outputs, or a tuple or List of Tensors, but not nested Tensors.
> 
> I modified the return statement of `PoolNet.forward` to circumvent this issue like
> 
> ```python
>         return [merge[0]] + merge[1]
> ```
> 
> Which will flatten the outputs into one list
> 
> ### Issue 3 - Converted AdaptiveAvgPool2d incorrect dimensions (I believe)
> After these fixes, I witnessed the concatenation error you mentioned.
> 
> I believe the `AdaptiveAvgPool2d` converter creating an output dimension that differs from torch. This has been tested primarily for pooling to divisible factors of the original spatial input dimensions. My guess, is that this assumption is not true for this model.
> 
> One option is to use the interpolate plugin which will do adaptive_avg_pool_2d if mode='area' is set. You can do this by replacing references to AdaptiveAvgPool2d with the following module
> 
> ```python
> class AdaptiveAvgPool2d_Interpolate(torch.nn.Module):
>     def __init__(self, size):
>         super(AdaptiveAvgPool2d_Interpolate, self).__init__()
>         if not isinstance(size, tuple) and not isinstance(size, list):
>             self.size = (size,)
>         else:
>             self.size = size
>     def forward(self, x):
>         return F.interpolate(x, size=self.size, mode='area')
> ```
> 
> This will use the interpolate plugin.
> 
> Please note, it seems on some Jetson platforms there is a resource exhausted error when using interpolate. I believe this is patched in more recent pushes to PyTorch, but I am not certain.
> 
> I believe the breaking reference to `AdaptiveAvgPool2d` was in the `deeplab_resnet.py` file in `ResNet_locate`.
> 
> I haven't been able to successfully convert yet due to the exhausted resources error, could you try these steps on your platform to see if this is the case?
> 
> Please let me know if you have any questions.
> 
> Best,
> John

Hi  @jaybdub ,
I tried to convert [ESRGAN](https://github.com/xinntao/ESRGAN) by torch2trt,  but it complained, 

```
/mnt/TRT/ESRGAN/RRDBNet_arch.py in forward(self, x)
     34 #         return x5 * 0.2 + x
     35         result = torch.mul(x5, 0.2)
---> 36         result = torch.add(result, x)
     37         return result
     38 

/mnt/TRT/venv/lib/python3.6/site-packages/torch2trt-0.0.0-py3.6.egg/torch2trt/torch2trt.py in wrapper(*args, **kwargs)
     95 
     96             #print('%s : %s' % (method.__qualname__, converter.__name__))
---> 97             converter(ctx)
     98 
     99             # convert to None so conversion will fail for unsupported layers

<ipython-input-3-bc2b8d096bb5> in convert_add(ctx)
      7     input_b = ctx.method_args[1]
      8     output = ctx.method_return
----> 9     layer = ctx.network.add_elementwise(input_a._trt, input_b._trt, trt.ElementWiseOperation.SUM)
     10     output._trt = layer.get_output(0)

AttributeError: 'Tensor' object has no attribute '_trt'
```

It seems  to be caused by [Issue 1](https://github.com/NVIDIA-AI-IOT/torch2trt/issues/44#issuecomment-522145338)  that you mentioned, 
but I've registered  `torch.add` before I converted ESRGAN, here my code,

```
import os.path as osp
import glob
import cv2
import numpy as np
import torch
import RRDBNet_arch as arch

model_path = 'RRDB_ESRGAN_x4.pth'  
device = torch.device('cuda')

model = arch.RRDBNet(3, 3, 64, 23, gc=32)
model.load_state_dict(torch.load(model_path), strict=True)
model.eval()
model = model.to(device)

import torch2trt
import tensorrt as trt

@torch2trt.tensorrt_converter('torch.add')
def convert_add(ctx):
    input_a = ctx.method_args[0]
    input_b = ctx.method_args[1]
    output = ctx.method_return
    layer = ctx.network.add_elementwise(input_a._trt, input_b._trt, trt.ElementWiseOperation.SUM)
    output._trt = layer.get_output(0)

from torch2trt import torch2trt
x = torch.ones((1, 3, 224, 224)).cuda()
model_trt = torch2trt(model, [x])
```

Is there something wrong? Any idea would be appreciated.

**Comment by smell-fishy** [comment]
Hi, John.
I did as you adviced, and it gives:
![WeChat Image_20190821161806](https://user-images.githubusercontent.com/34292353/63414979-8b3c4280-c42f-11e9-9105-9e6e49015204.png)

**Comment by smell-fishy** [comment]
Hi, John.
I have solved the problem.
The problem is that when executing  
self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1, ceil_mode=True),
the torch2trt would produce the output with dimension which is not the same as torch.
And I modify the code to:
self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
The issure of incorrect dimension disappear.
BUT...
Now there is another error:
![WeChat Screenshot_20190821173032](https://user-images.githubusercontent.com/34292353/63420524-6c42ae00-c439-11e9-9411-baeea4793d97.png)

**Comment by kawa23** [comment]
> > Hi smell-fishy,
> > A couple things I noticed that were causing problems.
> > ### Issue 1 - `torch.add` was not registered.
> > We already have this converter it was just not registered for `torch.add` specifically (insteal `torch.Tensor.__add__`.
> > I will register it soon, you can add it easily by calling this before calling `torch2trt`
> > ```python
> > import torch2trt
> > import tensorrt as trt
> > 
> > @torch2trt.tensorrt_converter('torch.add')
> > def convert_add(ctx):
> >     input_a = ctx.method_args[0]
> >     input_b = ctx.method_args[1]
> >     output = ctx.method_return
> >     layer = ctx.network.add_elementwise(input_a._trt, input_b._trt, trt.ElementWiseOperation.SUM)
> >     output._trt = layer.get_output(0)
> > ```
> > 
> > 
> > ### Issue 2 - PoolNet returns format (Tensor, [Tensor, Tensor, ...])
> > torch2trt only supports single Tensor outputs, or a tuple or List of Tensors, but not nested Tensors.
> > I modified the return statement of `PoolNet.forward` to circumvent this issue like
> > ```python
> >         return [merge[0]] + merge[1]
> > ```
> > 
> > 
> > Which will flatten the outputs into one list
> > ### Issue 3 - Converted AdaptiveAvgPool2d incorrect dimensions (I believe)
> > After these fixes, I witnessed the concatenation error you mentioned.
> > I believe the `AdaptiveAvgPool2d` converter creating an output dimension that differs from torch. This has been tested primarily for pooling to divisible factors of the original spatial input dimensions. My guess, is that this assumption is not true for this model.
> > One option is to use the interpolate plugin which will do adaptive_avg_pool_2d if mode='area' is set. You can do this by replacing references to AdaptiveAvgPool2d with the following module
> > ```python
> > class AdaptiveAvgPool2d_Interpolate(torch.nn.Module):
> >     def __init__(self, size):
> >         super(AdaptiveAvgPool2d_Interpolate, self).__init__()
> >         if not isinstance(size, tuple) and not isinstance(size, list):
> >             self.size = (size,)
> >         else:
> >             self.size = size
> >     def forward(self, x):
> >         return F.interpolate(x, size=self.size, mode='area')
> > ```
> > 
> > 
> > This will use the interpolate plugin.
> > Please note, it seems on some Jetson platforms there is a resource exhausted error when using interpolate. I believe this is patched in more recent pushes to PyTorch, but I am not certain.
> > I believe the breaking reference to `AdaptiveAvgPool2d` was in the `deeplab_resnet.py` file in `ResNet_locate`.
> > I haven't been able to successfully convert yet due to the exhausted resources error, could you try these steps on your platform to see if this is the case?
> > Please let me know if you have any questions.
> > Best,
> > John
> 
> Hi @jaybdub ,
> I tried to convert [ESRGAN](https://github.com/xinntao/ESRGAN) by torch2trt, but it complained,
> 
> ```
> /mnt/TRT/ESRGAN/RRDBNet_arch.py in forward(self, x)
>      34 #         return x5 * 0.2 + x
>      35         result = torch.mul(x5, 0.2)
> ---> 36         result = torch.add(result, x)
>      37         return result
>      38 
> 
> /mnt/TRT/venv/lib/python3.6/site-packages/torch2trt-0.0.0-py3.6.egg/torch2trt/torch2trt.py in wrapper(*args, **kwargs)
>      95 
>      96             #print('%s : %s' % (method.__qualname__, converter.__name__))
> ---> 97             converter(ctx)
>      98 
>      99             # convert to None so conversion will fail for unsupported layers
> 
> <ipython-input-3-bc2b8d096bb5> in convert_add(ctx)
>       7     input_b = ctx.method_args[1]
>       8     output = ctx.method_return
> ----> 9     layer = ctx.network.add_elementwise(input_a._trt, input_b._trt, trt.ElementWiseOperation.SUM)
>      10     output._trt = layer.get_output(0)
> 
> AttributeError: 'Tensor' object has no attribute '_trt'
> ```
> 
> It seems to be caused by [Issue 1](https://github.com/NVIDIA-AI-IOT/torch2trt/issues/44#issuecomment-522145338) that you mentioned,
> but I've registered `torch.add` before I converted ESRGAN, here my code,
> 
> ```
> import os.path as osp
> import glob
> import cv2
> import numpy as np
> import torch
> import RRDBNet_arch as arch
> 
> model_path = 'RRDB_ESRGAN_x4.pth'  
> device = torch.device('cuda')
> 
> model = arch.RRDBNet(3, 3, 64, 23, gc=32)
> model.load_state_dict(torch.load(model_path), strict=True)
> model.eval()
> model = model.to(device)
> 
> import torch2trt
> import tensorrt as trt
> 
> @torch2trt.tensorrt_converter('torch.add')
> def convert_add(ctx):
>     input_a = ctx.method_args[0]
>     input_b = ctx.method_args[1]
>     output = ctx.method_return
>     layer = ctx.network.add_elementwise(input_a._trt, input_b._trt, trt.ElementWiseOperation.SUM)
>     output._trt = layer.get_output(0)
> 
> from torch2trt import torch2trt
> x = torch.ones((1, 3, 224, 224)).cuda()
> model_trt = torch2trt(model, [x])
> ```
> 
> Is there something wrong? Any idea would be appreciated.


It seems this issue was fixed after I **Restart & Run All** at jupyter notebook Kernel.
But I  got another issue when I tried to convert [ESRGAN](https://github.com/xinntao/ESRGAN)

```
...
/mnt/TRT/ESRGAN/RRDBNet_arch.py in forward(self, x)
     27 
     28     def forward(self, x):
---> 29         x1 = self.lrelu(self.conv1(x))
     30         x2 = self.lrelu(self.conv2(torch.cat((x, x1), 1)))
     31         x3 = self.lrelu(self.conv3(torch.cat((x, x1, x2), 1)))

/mnt/TRT/venv/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

/mnt/TRT/venv/lib/python3.6/site-packages/torch2trt-0.0.0-py3.6.egg/torch2trt/torch2trt.py in wrapper(*args, **kwargs)
     95 
     96             #print('%s : %s' % (method.__qualname__, converter.__name__))
---> 97             converter(ctx)
     98 
     99             # convert to None so conversion will fail for unsupported layers

/mnt/TRT/venv/lib/python3.6/site-packages/torch2trt-0.0.0-py3.6.egg/torch2trt/converters/Conv2d.py in convert_Conv2d(ctx)
     32 
     33     layer = ctx.network.add_convolution(
---> 34         input=input._trt,
     35         num_output_maps=module.out_channels,
     36         kernel_shape=kernel_size,

AttributeError: 'Tensor' object has no attribute '_trt'
```

Any ide? ths.

**Comment by smell-fishy** [comment]
Hi, John.
Last problem is due to that:
torch2trt only supports single Tensor outputs, or a tuple or List of Tensors, but not nested Tensors.
And I successfully convert the model.
Thanks for your help!
But it seems that the speed just increase a little, from 11.63 fps to 13.89.

**Comment by jaybdub** [comment]
Hi smell-fishy.


Great to hear.  Hmm, I guess that's better than no performance improvement.  Typically you should see a bit higher.  Did you pass ``fp16_mode=True`` to torch2trt?

Best,
John

**Comment by smell-fishy** [comment]
> Hi smell-fishy.
> 
> Great to hear. Hmm, I guess that's better than no performance improvement. Typically you should see a bit higher performance improvement. Did you pass `fp16_mode=True` to torch2trt?
> 
> Best,
> John

Hi, John.

Yes, I passed 'fp16_mode=True' to torch2trt, but it is still little performance improvement.
Do you have any idea why it just improve a little?
Is it due to the complex architecture of Poolnet?

**Comment by saulzar** [comment]
I have the same issue with AvgPooling and ceil mode reducing my tensors from 4D 1xCxHxW to CxHxW
