### ISSUE TITLE
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by maky-hnou** [NVIDIA-AI-IOT/torch2trt#444]
**Torch packages:** 
tensorrt==6.0.1.10
torch==1.4.0
torchvision==0.5.0a0+85b8fbf
trt-pose==0.0.1

**Platform:**  
Nvidia Jetson Nano
Jetpack 4.3

I wanted to install torch2trt.  
The steps I followed:  
```
git clone https://github.com/NVIDIA-AI-IOT/torch2trt
cd torch2trt
sudo python3 setup.py install --plugins
```
I used the argument `plugins` because it was asked [here](https://github.com/NVIDIA-AI-IOT/trt_pose#step-1---install-dependencies).  

When I run `sudo python3 setup.py install --plugins`, I get this error:  
```
In file included from torch2trt/plugins/plugins.cpp:3:0:
torch2trt/plugins/group_norm.cpp: In member function ‘void torch2trt::GroupNormPlugin::deserializeFromString(const string&)’:
torch2trt/plugins/group_norm.cpp:52:51: error: cannot convert ‘std::vector<long int>’ to ‘int64_t {aka long int}’ in assignment
             num_groups = value.toIntListRef().vec();
                                                   ^
torch2trt/plugins/group_norm.cpp:72:47: error: cannot convert ‘std::vector<double>’ to ‘double’ in assignment
             eps = value.toDoubleListRef().vec();
                                               ^
```  
And the installation exits with this error:  `error: command 'aarch64-linux-gnu-gcc' failed with exit status 1`

However, when I run the installation without the `--plugins` parameter, it works.  

Is there a difference between installing with and without the plugins?  
How to solve this error?

**Comment by jaybdub** [comment]
Hi @maky-hnou,

Thanks for reaching out!

The ``--plugins`` flag enables two features

1. An interpolation plugin  (used for upsample/interpolation layers with TensorRT < 7.1)
2. A group norm plugin (used for GroupNorm layer)

Fortunately, trt_pose does not depend on either of these layers, so you should be able to install without plugins.

That said, this compilation error shouldn't happen!  I'll track this bug and we can hopefully resolve soon.

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by maky-hnou** [comment]
Hello @jaybdub, thank you for replying. 
I installed torch2trt without the plugins and it worked fine. 
Thank you again.

**Comment by Ekta246** [comment]
> Hi @maky-hnou,
> 
> Thanks for reaching out!
> 
> The `--plugins` flag enables two features
> 
> 1. An interpolation plugin  (used for upsample/interpolation layers with TensorRT < 7.1)
> 2. A group norm plugin (used for GroupNorm layer)
> 
> Fortunately, trt_pose does not depend on either of these layers, so you should be able to install without plugins.
> 
> That said, this compilation error shouldn't happen! I'll track this bug and we can hopefully resolve soon.
> 
> Please let me know if this helps or you run into any issues.
> 
> Best,
> John

What if I want to use the flexibility of interpolate and upsample layers for my object detector model and I am getting 
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

**Comment by KeyKy** [comment]
> Hi @maky-hnou,
> 
> Thanks for reaching out!
> 
> The `--plugins` flag enables two features
> 
> 1. An interpolation plugin  (used for upsample/interpolation layers with TensorRT < 7.1)
> 2. A group norm plugin (used for GroupNorm layer)
> 
> Fortunately, trt_pose does not depend on either of these layers, so you should be able to install without plugins.
> 
> That said, this compilation error shouldn't happen! I'll track this bug and we can hopefully resolve soon.
> 
> Please let me know if this helps or you run into any issues.
> 
> Best,
> John

Hi, this bug is not solved.
