### ISSUE TITLE
Duplicate filenames

### ISSUE THREAD

**Issue by koenvandesande** [NVIDIA-AI-IOT/torch2trt#445]
If you checkout torch2trt on Windows, you will find that 3 files cannot checkout properly, because they exist with 2 different casings:

* torch2trt\torch2trt\converters\Identity.py
* torch2trt\torch2trt\converters\ReLU.py
* torch2trt\torch2trt\converters\ReLU6.py

Is it possible to merge or rename these files?

**Comment by jaybdub** [comment]
Hi koenvandesand.

Thanks for reaching out!

Yes, merging the files is a good idea, and should be trivial to do.  I'd gladly accept a PR with these changes if you are interested in contributing directly.

Identity.py >> identity.py
ReLU.py >> relu.py
ReLU6.py >> relu6.py

If not, I can make a PR soon to address these changes.

Either way, let me know if it interests you or you have any questions.

Best,
John

**Comment by koenvandesande** [comment]
Closed by #448
