### ISSUE TITLE
ERROR on load saved model

### ISSUE THREAD

**Issue by xuhao1** [NVIDIA-AI-IOT/torch2trt#46]
Hi
I am using Python2.7, Torch 1.2, cuda 10.0, tensorrt 5.1.4
When trying to load saved tensorrt model by
```python
model_backbone.load_state_dict(torch.load(weights_trt_path))
```
I got
```
python: engine.cpp:1104: bool nvinfer1::rt::Engine::deserialize(const void*, std::size_t, nvinfer1::IGpuAllocator&, nvinfer1::IPluginFactory*): Assertion `size >= bsize && "Mismatch between allocated memory size and expected size of serialized engine."' failed.
```

This model is saved by
```python
from torch2trt import torch2trt
model_trt = torch2trt(model_backbone, [image.unsqueeze(0)])
torch.save(model_trt.state_dict(), 'weights/yolov3-tiny_drone_trt.pth')
```

**Comment by f-cordes** [comment]
Hey,

did you by chance figure out how to solve that problem?

I have the same problem using a similar setup on a Jetson Tx2 when executing the example in:
[https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/notebooks/image_classification/conversion.ipynb](url)
