### ISSUE TITLE
What's the batchsize used to report benchmark numbers here?

### ISSUE THREAD

**Issue by abhaydoke09** [NVIDIA-AI-IOT/torch2trt#466]
What's the batchsize used to report benchmark numbers here: https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/benchmarks/JETSON_XAVIER.md

**Comment by jaybdub** [comment]
Hi abhaydoke09,

Thanks for reaching out!

The batch size for all reported timings is 1. The input shapes column listed in the table specifies the full shape (including batch size).

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by abhaydoke09** [comment]
Awesome. Thanks for the quick response.
