### ISSUE TITLE
tensorrt model slower than pytorch

### ISSUE THREAD

**Issue by lunlun123** [NVIDIA-AI-IOT/torch2trt#474]
Environment：
ubuntu 18.04
pytorch 1.6
cuda 10.2
cudnn 8.0.1
tensorrt 7.1.3.4

run:   `python3 -m torch2trt.test -o test_output.md --name interpolate`

get this: 

`| torch2trt.converters.interpolate.test_nearest_mode | float32 | [(1, 2, 12, 12)] | {} | 0.00E+00 | 3.68e+04 | 1.67e+04 | 0.0446 | 0.0728 |

| torch2trt.converters.interpolate.test_bilinear_mode | float32 | [(1, 4, 12, 12)] | {} | 2.38E-07 | 3.67e+04 | 1.72e+04 | 0.0435 | 0.0722 |

| torch2trt.converters.interpolate.test_align_corner | float32 | [(1, 3, 12, 12)] | {} | 1.77E+00 | 3.62e+04 | 1.72e+04 | 0.0449 | 0.074 |

| torch2trt.converters.interpolate.test_bilinear_mode_odd_input_shape | float32 | [(1, 5, 13, 13)] | {} | 2.38E-07 | 3.67e+04 | 1.73e+04 | 0.0431 | 0.0723 |

| torch2trt.converters.interpolate.test_size_parameter | float32 | [(1, 4, 12, 12)] | {} | 0.00E+00 | 5.34e+04 | 1.56e+04 | 0.0333 | 0.072 |

| torch2trt.converters.interpolate.test_size_parameter_odd_input | float32 | [(1, 3, 1, 1)] | {} | 0.00E+00 | 3.92e+04 | 1.67e+04 | 0.0406 | 0.0703 |

| torch2trt.converters.interpolate.test_size_parameter_odd_input | float32 | [(1, 3, 13, 13)] | {} | 0.00E+00 | 5e+04 | 1.58e+04 | 0.0324 | 0.0771 |

| torch2trt.converters.interpolate.test_nearest_mode_3d | float32 | [(1, 4, 6, 6, 6)] | {} | 0.00E+00 | 3.67e+04 | 1.71e+04 | 0.0429 | 0.0778 |

| torch2trt.converters.interpolate.test_bilinear_mode_3d | float32 | [(1, 3, 5, 5, 5)] | {} | 2.38E-07 | 2.79e+04 | 1.69e+04 | 0.0525 | 0.0711 |

| torch2trt.converters.interpolate.test_align_corner_3d | float32 | [(1, 4, 8, 8, 8)] | {} | 2.92E+00 | 2.7e+04 | 1.7e+04 | 0.0526 | 0.0736 |

| torch2trt.converters.interpolate.test_bilinear_mode_odd_input_shape_3d | float32 | [(1, 3, 1, 1, 1)] | {} | 0.00E+00 | 2.88e+04 | 1.7e+04 | 0.0532 | 0.0713 |

| torch2trt.converters.interpolate.test_bilinear_mode_odd_input_shape_3d | float32 | [(1, 3, 2, 4, 4)] | {} | 2.38E-07 | 2.81e+04 | 1.71e+04 | 0.0523 | 0.0735 |

| torch2trt.converters.interpolate.test_bilinear_mode_odd_input_shape_3d | float32 | [(1, 6, 7, 7, 7)] | {} | 2.38E-07 | 2.82e+04 | 1.71e+04 | 0.0549 | 0.0749 |

| torch2trt.converters.interpolate.test_size_parameter_3d | float32 | [(1, 1, 12, 12, 12)] | {} | 5.96E-08 | 3.83e+04 | 1.72e+04 | 0.0409 | 0.0714 |

| torch2trt.converters.interpolate.test_size_parameter_odd_input_3d | float32 | [(1, 4, 3, 5, 1)] | {} | 4.77E-07 | 3.02e+04 | 1.71e+04 | 0.0517 | 0.0746 |

| torch2trt.converters.interpolate.test_size_parameter_odd_input_3d | float32 | [(1, 3, 7, 9, 5)] | {} | 2.56E-06 | 2.79e+04 | 1.48e+04 | 0.0543 | 0.0787 |
NUM_TESTS: 16
NUM_SUCCESSFUL_CONVERSION: 16
NUM_FAILED_CONVERSION: 0
NUM_ABOVE_TOLERANCE: 0
` 

it's strange that     trt_fps < pytorch_fps   and     trt_ms>pytorch_ms?

**Comment by shenw8023** [comment]
meet the same problem
