### ISSUE TITLE
Doesnot support indexing 

### ISSUE THREAD

**Issue by eriche2016** [NVIDIA-AI-IOT/torch2trt#476]
Hi, I am using torch2trt in my project. However, the output of the converted model cannot be indexed like regular tensor in torch, and gives me the error below: 
```
IndexError: too many indices for tensor of dimension 1
```
can you give some clues on solving this prolem. 
``` 
# testing script 
mydata = torch.rand(100)
mydata[torch.LongTensor([0,1])]
```

**Comment by jaybdub** [comment]
Hi eriche2016,

Thanks for reaching out!

Hmm, the tensor output by the model is a PyTorch tensor, and should be capable of being indexed.  Do you mind sharing the steps you used to convert the model?

Best,
John

**Comment by eriche2016** [comment]
Hi, John, 
The output of the converted model does not support the batch indexing, and it seems that tensorrt has overwritten some indexing behavior of pytorch tensor, I finally solved this problem by using numpy array as indices.

**Comment by eriche2016** [comment]
Hi, John, the testing script is below: 
```
import torch 
import torch.nn as nn  
from torch2trt import torch2trt
from torch2trt import TRTModule
import pdb 

class model(nn.Module):
    def __init__(self): 
        super(model, self).__init__() 
        self.fc1 = nn.Linear(100, 40)
        self.fc2 = nn.Linear(40,3) 
    def forward(self, x):
        x = self.fc1(x)
        out = self.fc2(x)
        return x 
test_model = model() 

test_model = test_model.cuda() 
test_model = test_model.eval() 
test_model_input = torch.ones((1, 100), dtype=torch.float32, device=torch.device("cuda"))
 
test_model_trt = torch2trt(test_model, [test_model_input], fp16_mode=True, max_workspace_size=1 << 20)

input = torch.rand(1, 100).cuda() 
out = test_model_trt(input) 

# testing pytorch tensor behavior 
mydata = torch.rand(100)
mydata[torch.LongTensor([0,1])]
```
