### ISSUE TITLE
spconv inference

### ISSUE THREAD

**Issue by lunlun123** [NVIDIA-AI-IOT/torch2trt#481]
i add spconv plugin, only write plugin create . spconv main process(like getindicepairs，indconv...) have no change. when inference, tensorRT context execute_async spend more time than pytorch inference. Is this normal？？

2080ti，voxelnet of centerpoint network , pytorch time ： 60ms ;   tensorRT time :  65ms

thanks for your help!

**Comment by jaybdub** [comment]
Hi lunlun123,

Thanks for reaching out!

This might depend on the plugin, and how it appears in the neural network.  

Do you have a link to the model you're converting?

Best,
John

**Comment by lunlun123** [comment]
> Hi lunlun123,
> 
> Thanks for reaching out!
> 
> This might depend on the plugin, and how it appears in the neural network.
> 
> Do you have a link to the model you're converting?
> 
> Best,
> John

I mainly changed spconv，Modify spconv plugin like the interpolate.cpp.
spconv：https://github.com/traveller59/spconv

then , use spconv plugin to convert voxelnet of centerpoint.
centerpoint: https://github.com/tianweiy/CenterPoint

**Comment by xiaoxifuhongse** [comment]
> spconv plugin

hello ,I have the same question, do you solve it now? Thks
