### ISSUE TITLE
expand unsupported

### ISSUE THREAD

**Issue by jaybdub** [NVIDIA-AI-IOT/torch2trt#486]
expand broadcasts tensors along specified dimensions.

https://pytorch.org/docs/stable/tensors.html

**Comment by jaybdub** [comment]
Following converter seems to work

```python
@torch2trt.tensorrt_converter('torch.Tensor.expand')
def convert_expand(ctx):
    input = ctx.method_args[0]
    sizes = ctx.method_args[1:]
    output = ctx.method_return
    
    inshape = tuple(input.shape)[1:]
    shape = sizes[1:] # exclude batch
    ndim = len(shape)
    start = tuple([0]*ndim)
    stride = tuple([int(i == o) for i, o in zip(inshape, shape)])  # stride == 1 if dimensions match, 0 otherwise
    
    layer = ctx.network.add_slice(input._trt, start, shape, stride)
    
    output._trt = layer.get_output(0)
    print(output._trt.shape)
```

**Comment by jaybdub** [comment]
converter now added in master as of https://github.com/NVIDIA-AI-IOT/torch2trt/pull/487

**Comment by DaweiLi-Topcon** [comment]
@jaybdub Hi John, I failed to pass this module, Here is the log I met.
  File "/XXXX/networks.py", line 525, in forward
    levels = levels.expand((xsize + [len(self.levels)]))
  File "/XXXX/venv/lib/python3.6/site-packages/torch2trt-0.3.0-py3.6.egg/torch2trt/torch2trt.py", line 300, in wrapper
    converter["converter"](ctx)
  File "/XXXX/lib/python3.6/site-packages/torch2trt-0.3.0-py3.6.egg/torch2trt/converters/expand.py", line 17, in convert_expand
    layer = ctx.network.add_slice(input._trt, start, shape, stride)
AttributeError: 'Tensor' object has no attribute '_trt'

and here is the original code to trans. 
class quantize(nn.Module):
    def __init__(self, nquant, sigma=1.0):
        super(quantize, self).__init__()
        # nquant: number of quantization levels
        quant_delta = 2.0 / int(nquant)
        quant_levels = [-1.0 + quant_delta / 2.0 + l * quant_delta for l in range(nquant)]
        self.levels = quant_levels
        self.sigma = sigma

    def forward(self, input):
        levels = input.data.new(self.levels)
        xsize = list(input.size())
        # Compute differentiable soft quantized version
        input = input.view(*(xsize + [1]))
        level_var = Variable(levels, requires_grad=False)
        dist = torch.pow(input-level_var.clone(), 2)
        output = torch.sum(level_var.clone() * nn.functional.softmax(-self.sigma*dist, dim=dist.ndim-1), dim=dist.ndim-1) # dim = -1 & dim = -1 to dim = dist.dim()

        # Compute hard quantization (invisible to autograd)
        _, symbols = torch.min(dist.data, dim=dist.data.ndim-1, keepdim=True)
        for _ in range(len(xsize)):
            levels.unsqueeze_(0)
        levels = levels.expand((xsize + [len(self.levels)]))

        quant = levels.gather(-1, symbols.long()).squeeze_(dim=levels.ndim-1)

        # Replace activations in soft variable with hard quantized version
        output.data = quant

        return output
