### ISSUE TITLE
Can torch2trt export torch model to uff,or tensorRT engine file?

### ISSUE THREAD

**Issue by leaf918** [NVIDIA-AI-IOT/torch2trt#499]
RT

**Comment by jaybdub** [comment]
Hi @leaf918,

Thanks for reaching out!!  You can export the serialized engine file for direct use with TensorRT API as follows

```python
model_trt = torch2trt(...)

with open('model.engine', 'wb') as f:
    f.write(model_trt.engine.serialize())
```

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by leaf918** [comment]
Works for me,thanks.
