### ISSUE TITLE
Error executing the example notebook

### ISSUE THREAD

**Issue by bobogumizelka** [NVIDIA-AI-IOT/torch2trt#51]
I'm executing the example notebook image_classification/conversion.ipynb and i'm getting:
AttributeError: 'Tensor' object has no attribute '_trt'.

**Comment by bobogumizelka** [comment]
Thanks for the response! I have Python 3.6.8, PyTorch 1.1.0 and TensorRT 5.1.6.1.

**Comment by bobogumizelka** [comment]
It's Jetson Nano, and torchvision is 0.3.0.

Best,
bobogumizelka

**Comment by adrianosantospb** [comment]
Hello, 

When I run the convert example I'm receiving Segmentation fault message. Any idea?
