### ISSUE TITLE
AttributeError: type object 'Tensor' has no attribute '__ifloordiv__'

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [NVIDIA-AI-IOT/torch2trt#510]
Working on Waveshare Jetbot, I cloned this repository and installed setup.py then I try and run the code below:

         from torch2trt import torch2trt
         data = torch.zeros((1, 3, 224, 224)).cuda().half()
         model_trt = torch2trt(model, [data], fp16_mode=True)

But instead of converting my model to tensorRT, instead I get the following error:

    AttributeError                            Traceback (most recent call last)
    <ipython-input-6-dd315960311d> in <module>
    ----> 1 from torch2trt import torch2trt
          2 
          3 data = torch.zeros((1, 3, 224, 224)).cuda().half()
          4 
          5 model_trt = torch2trt(model, [data], fp16_mode=True)

    /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

    /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

    /usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

    /usr/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

    /usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/__init__.py in <module>
          1 from .torch2trt import *
    ----> 2 from .converters import *
          3 import tensorrt as trt
          4 
          5 

    /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

    /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

    /usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

    /usr/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

    /usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/__init__.py in <module>
         27 from .div import *
         28 from .expand import *
    ---> 29 from .floordiv import *
         30 from .getitem import *
         31 from .identity import *

    /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

    /usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

    /usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

    /usr/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

    /usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/converters/floordiv.py in <module>
          4 
          5 @tensorrt_converter('torch.Tensor.__floordiv__')
    ----> 6 @tensorrt_converter('torch.Tensor.__ifloordiv__')
          7 @tensorrt_converter('torch.floor_divide')
          8 def convert_floordiv(ctx):

    /usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py in tensorrt_converter(method, is_real, enabled, imports)
        594         module, module_name, qual_name = importlib.import_module(method.__module__), method.__module__, method.__qualname__
        595 
    --> 596     method_impl = eval('copy.deepcopy(module.%s)' % qual_name)
        597 
        598     def register_converter(converter):

    /usr/local/lib/python3.6/dist-packages/torch2trt-0.1.0-py3.6.egg/torch2trt/torch2trt.py in <module>

    AttributeError: type object 'Tensor' has no attribute '__ifloordiv__'

Any help in troubling shooting this would be very much appreciated!

**Comment by jaybdub** [comment]
Hi @abuelgasimsaadeldin ,

Thanks for reaching out!

This seems to be a duplicate of this issue

https://github.com/NVIDIA-AI-IOT/torch2trt/issues/508

The workaround they suggested is to use PyTorch 1.6.

I'm going to work on addressing this issue.

Do you mind sharing which version of PyTorch you're using?  I'd like to make sure the error doesn't occur for your use case.

Best,
John

**Comment by abuelgasimsaadeldin** [comment]
Hi @jaybdub,

Wow, thanks allot for the prompt reply, my PyTorch version is 1.3.0. Thanks again! 

Best,
Abu

**Comment by abuelgasimsaadeldin** [comment]
Hi @jaybdub,

Worked. Thanks you!
