### ISSUE TITLE
ModuleNotFoundError: No module named 'torch2trt'

### ISSUE THREAD

**Issue by whcjb** [NVIDIA-AI-IOT/torch2trt#515]
i meet a problem that it's ok to import torch2trt in python command line, but fail to import in .py file. someone know why?

it's ok in command line
![image](https://user-images.githubusercontent.com/11767995/109477815-74aa8900-7ab3-11eb-9db7-fd10fa579d46.png)

fail when run .py file
![image](https://user-images.githubusercontent.com/11767995/109477965-9f94dd00-7ab3-11eb-9e5e-8cfb281b6873.png)

**Comment by whcjb** [comment]
path setting problem.

**Comment by uuu686** [comment]
hello, can you tell me how to solve the problem? which path should I set?
