### ISSUE TITLE
how can I use  torch.nn.functional.conv1d in tensor RT

### ISSUE THREAD

**Issue by yulinhuyang** [NVIDIA-AI-IOT/torch2trt#523]
I use torch.nn.functional.conv1d(img, query) as a module in torch, but it can not convert to a onnx/tensorRT module successfully,so how can I implement it in tensorRT。

**Comment by jaybdub** [comment]
Hi yulinhuyang,

Thanks for reaching out!

We have a Conv1d converter implemented in torch2trt here

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/converters/Conv1d.py

Is this working for you?  If not, are you able to share some example code to reproduce the issue you're seeing?

Best,
John

**Comment by yulinhuyang** [comment]
Many Thanks for  you ! I used it liked this. 

>>> filters = torch.randn(33, 16, 3)
>>> inputs = torch.randn(20, 16, 50)
>>> F.conv1d(inputs, filters)

the filters and inputs are all forward inputs and  equivocal .  it is a function  used for  Convolution and correlation operation. the filters shape can be known. 

It is different from:  

 m = nn.Conv1d(16, 33, 3, stride=2)

this kernel is fixed.

Thank you for your help!
