### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by chongyangwang-song** [NVIDIA-AI-IOT/torch2trt#540]
Error: condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 2, but engine max batch size was: 1
mycode:
______________________________________________________________________________
import torchvision
import time
model = torchvision.models.resnet18(pretrained=True).cuda().half().eval()
import torch
data = torch.randn((2, 3, 224, 224)).cuda().half()
from torch2trt import torch2trt
model_trt = torch2trt(model, [data], fp16_mode=True)
trt_start = time.time()
data1 = torch.randn((2, 3, 224, 224)).cuda().half()
for i in range(10):
    output_trt = model_trt(data1)
trt_end = time.time()
print("trt consume:",trt_end - trt_start)
print("result:",output_trt.shape)
torch_start = time.time()
for i in range(10):
    output = model(data1)
print("result:",output.shape)
_________________________________________________________________________
moreover ,could I make the batchsize of the input dynamic?
manythanks!

**Comment by jeshxxx** [comment]
use max_batch_size likemodel_trt = torch2trt(model, [data], fp16_mode=True)

**Comment by chongyangwang-song** [comment]
@jeshxxx Thank you for your reply.
