### ISSUE TITLE
How can i use it for converting to int8 mode????

### ISSUE THREAD

**Issue by ginamkim** [NVIDIA-AI-IOT/torch2trt#55]
with this code I can successfully achieve to convert from torch to fp32 and fp16. but I want to convert to int8. How can i do that???

**Comment by jaybdub** [comment]
Hi ginamkim,

Thanks for reaching out!  Unfortunately, we haven't yet implemented int8 calibration in torch2trt.  If this changes I will update this thread.

Best,
John

**Comment by ginamkim** [comment]
Hi John

Thanks for your answer. :)

Best,
Ginam

**Comment by jaybdub** [comment]
To close this off.  torch2trt does now support int8.  Please see the following documentation page for details

https://nvidia-ai-iot.github.io/torch2trt/master/usage/reduced_precision.html
