### ISSUE TITLE
[TensorRT] ERROR: safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [NVIDIA-AI-IOT/torch2trt#554]
This is script  I am using 
import torch
from torch2trt import torch2trt

# create some regular pytorch model...
# load trained model -------------------------------------------------------------------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
checkpoint = 'checkpoint_ssd300.pth'
checkpoint = torch.load(checkpoint)
model = checkpoint['model']
model = model.to(device)

# create example data
x = torch.ones((1, 3, 300, 300)).cuda()

# convert to TensorRT feeding sample data as input
model_trt = torch2trt(model, [x])

but giving below error
Warning: Encountered known unsupported method torch.Tensor.pow
[TensorRT] ERROR: safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
[TensorRT] ERROR: safeContext.cpp (124) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)

**Comment by DWendou** [comment]
when i run the demo ，i also  have same problem，do you solve it？

**Comment by nhewitt99** [comment]
Make sure that you have [installed cudnn properly](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html).

Also, check that your driver, CUDA, cudnn, and TensorRT versions are all compatible. Mismatching versions can cause this error as well. Check the official install guides for each technology to get the latest information on which versions they are compatible with.
