### ISSUE TITLE
Cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by Rafipaulino** [NVIDIA-AI-IOT/torch2trt#563]
PyTorch version : 1.6.0
TensorRT version: 7.1.3
Platform : Jetson Nano

Hi,
I'm just trinyg to run the sample notebook following the descriptions given. When I try to run the first cell of the live_demo notebook, I'm getting that:

`OSError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block`

Here is the log :

`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-0c2219f9314e> in <module>
      1 import json
----> 2 import trt_pose.coco
      3 
      4 with open('human_pose.json', 'r') as f:
      5     human_pose = json.load(f)

/usr/local/lib/python3.6/dist-packages/trt_pose-0.0.1-py3.6-linux-aarch64.egg/trt_pose/__init__.py in <module>
----> 1 import torch

~/.local/lib/python3.6/site-packages/torch/__init__.py in <module>
    186     # See Note [Global dependencies]
    187     if USE_GLOBAL_DEPS:
--> 188         _load_global_deps()
    189     from torch._C import *
    190 

~/.local/lib/python3.6/site-packages/torch/__init__.py in _load_global_deps()
    139     lib_path = os.path.join(os.path.dirname(here), 'lib', lib_name)
    140 
--> 141     ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
    142 
    143 

/usr/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
`

What can be wrong?
Thanks in advance!!

**Comment by danielgran** [comment]
What was wrong? LD_PRELOAD isn't working for me because of dlopen sitting in between.. :-(
