### ISSUE TITLE
another 'Tensor' object has no attribute '_trt'

### ISSUE THREAD

**Issue by ooodragon94** [NVIDIA-AI-IOT/torch2trt#568]
Hi
Trying out EfficientNet_b1 for jetson

seems like I get the following warning and error

```
Warning: Encountered known unsupported method torch.nn.functional.has_torch_function_variadic
Warning: Encountered known unsupported method torch.nn.functional.linear

  File "model_convert.py", line 24, in <module>
    model_trt = torch2trt(model, [x])
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.2.0-py3.6.egg/torch2trt/torch2trt.py", line 546, in torch2trt
  File "/usr/local/lib/python3.6/dist-packages/torch2trt-0.2.0-py3.6.egg/torch2trt/torch2trt.py", line 407, in mark_outputs
AttributeError: 'Tensor' object has no attribute '_trt'
```

I am aware SiLU is not implemented for onnx so I have changed them to ReLU
but it seems like there is another error

**Comment by jaybdub** [comment]
Hi @ooodragon94,

Thanks for reaching out!

Currently, ``torch.nn.functional.linear`` isn't registered with a converter, but ``torch.nn.Linear`` is.

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/e01279cfc7cfc26cb8754a8310aceef1d5bfc421/torch2trt/converters/Linear.py#L5

You may be able to make small modifications to this converter to get past the second warning.

Do you mind sharing a link to the EfficicnetNet_b1 model that you're attempting to convert?  This may help me spot other issues.

Please let me know if you have any questions or run into issues.

Best,
John

**Comment by ooodragon94** [comment]
Thanks for your reply!
the code I referred is [timm](https://github.com/rwightman/pytorch-image-models)

It can be downloaded with
```shell
pip install timm
```

you can initialize it by coding something like
```python
import timm
model = timm.models.efficientnet_b1(pretrained=True)
```

**Comment by jaybdub** [comment]
Hi @ooodragon94,

I was able to convert the model by registering converters for ``torch.nn.functional.silu`` and ``torch.nn.functional.linear``

Below is the program I used to convert the model.  

```python
import timm
import torch
from torch2trt import torch2trt, tensorrt_converter, get_arg, trt, add_missing_trt_tensors, torch_dtype_to_trt

# REGISTER NEW CONVERTERS
@tensorrt_converter('torch.nn.functional.silu')
def convert_silu(ctx):
    input = get_arg(ctx, 'input', pos=0, default=None)
    output = ctx.method_return
    input_trt = add_missing_trt_tensors(ctx.network, [input])[0]
    
    layer = ctx.network.add_activation(input_trt, trt.ActivationType.SIGMOID)
    layer = ctx.network.add_elementwise(input_trt, layer.get_output(0), trt.ElementWiseOperation.PROD)
    
    output._trt = layer.get_output(0)
    
@tensorrt_converter('torch.nn.functional.linear')
def convert_Linear(ctx):
    input = ctx.method_args[0]
    weight = get_arg(ctx, 'weight', 1, None)
    bias = get_arg(ctx, 'bias', 2, None)
    input_trt = add_missing_trt_tensors(ctx.network, [input])[0]
    output = ctx.method_return

    # reshape to ...xNx1x1
    layer = ctx.network.add_shuffle(input_trt)
    layer.reshape_dims = tuple(input_trt.shape) + (1, 1) 

    bias_trt = trt.Weights(torch_dtype_to_trt(weight.dtype))
    if bias is not None:
        bias_trt = bias.detach().cpu().numpy()
        
    # add fully connected
    layer = ctx.network.add_fully_connected(
        input=layer.get_output(0),
        num_outputs=int(weight.shape[0]),
        kernel=weight.detach().cpu().numpy(),
        bias=bias_trt)

    # reshape back to N
    layer = ctx.network.add_shuffle(layer.get_output(0))
    layer.reshape_dims = tuple(output.shape[1:])

    output._trt = layer.get_output(0)


# CONVERT MODEL
model = timm.models.efficientnet_b1(pretrained=True).cuda().eval()
data = torch.zeros(1, 3, 224, 224).cuda()
model_trt = torch2trt(model, [data])

# TEST
data = torch.randn(1, 3, 224, 224).cuda()
print(torch.max(torch.abs(model_trt(data) - model(data)))
```

Please let me know if this works for you and I'll work on a pull-request to integrate these converters into the project.

Best,
John

**Comment by ooodragon94** [comment]
thanks! it works as charm
Sorry to come back late... 

One last question (sorry to bother you..)
1. It seems like it works with normal torchvision dataset and loader but with batch size 1. Am I doing this right? Or should I change my method?
2. Does calling torch2trt on jetson nano will optimize the network according to jetson's preference (in other words, will it call and build engine wrt jetson's architecture?)

**Comment by jaybdub** [comment]
Hi @ooodragon94 ,

### 1 - Processing Pipeline

Depending on your application, different methods for constructing a processing pipeline might be fit.  For example, if you're working on a robot like [JetRacer](https://github.com/NVIDIA-AI-IOT/jetracer), you might require batch size 1 to minimize latency.  For other applications, like streaming video analytics, you might prefer higher throughput, and accept the slightly delayed processing.

### 2 - Platform dependence

Indeed!  Calling torch2trt performs TensorRT optimization, which is platform dependent.  TensorRT will automatically select and tune processing kernels by timing on the actual hardware.  For this reason, the optimized _engine_ only executes on similar platforms (with similar versions of TensorRT).  

Once created, the optimized engine is serialized and stored inside ``network_trt.pth``.  When you construct a ``TRTModule`` and call ``load_state_dict`` it deserializes this engine internally and prepares a context for execution.

### 3 - Quantization / Batch Size

Yes, you can perform network quantization to INT8 precision.  Please refer to the documentation here and let me know if you have questions

https://nvidia-ai-iot.github.io/torch2trt/v0.2.0/usage/reduced_precision.html

The batch size is specified by setting the ``max_batch_size`` parameter.  For example, ``torch2trt(..., max_batch_size=16)``.  This means during execution you will then be able to call your model up to batch size ``16``.

Please let me know if this helps or you have any questions. 

Best,
John

**Comment by ooodragon94** [comment]
Your explanation rocks.
Thank you so much for your kind and thorough response!
