### ISSUE TITLE
Example fails with 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size'

### ISSUE THREAD

**Issue by Paul92** [NVIDIA-AI-IOT/torch2trt#592]
I am using CUDA 11.3 with TensorRT 8.

The example in image_classification/conversion.ipynb fails with the error 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size'.

I assume this has to do with the deprecations introduced by TensorRT 8.

**Comment by romanvey** [comment]
Actually, you can use this repo with a fixed version: https://github.com/gcunhase/torch2trt Just reinstall it. Worked for me
