### ISSUE TITLE
TensorRT-8.0 Support

### ISSUE THREAD

**Issue by kinglintianxia** [NVIDIA-AI-IOT/torch2trt#593]
TensorRT-8.0 changed the api, do you conside support it? @saulzar @vellamike

**Comment by SrivastavaKshitij** [comment]
what changed exactly ? I havent looked at the documentation yet.

**Comment by kinglintianxia** [comment]
> what changed exactly ? I havent looked at the documentation yet.
* [TensorRT OSS v8.0.1](https://github.com/NVIDIA/TensorRT/releases/tag/8.0.1) removed TensorRT 6.0's `IPlugin` and `IPluginFactory` interfaces, the changes of API leads to build error!
* Another question by the way, does the `interpolate` plugin fix the `Pytorch -> TensorRT-7.0` problem which was rehauled by TensorRt-8.0?
Thanks!

**Comment by jaybdub** [comment]
Thanks for reaching out!

Regarding TensorRT 8.0 support.

There are a couple open PRs from community developers for supporting TensorRT 8.0 

https://github.com/NVIDIA-AI-IOT/torch2trt/pull/581

https://github.com/NVIDIA-AI-IOT/torch2trt/pull/560

I have not yet verified these, but hope to do so soon.  

Please let me know if these help for your use case, or you run into any issues.

Best,
John

**Comment by kinglintianxia** [comment]
> Thanks for reaching out!
> 
> Regarding TensorRT 8.0 support.
> 
> There are a couple open PRs from community developers for supporting TensorRT 8.0
> 
> #581
> 
> #560
> 
> I have not yet verified these, but hope to do so soon.
> 
> Please let me know if these help for your use case, or you run into any issues.
> 
> Best,
> John

Thanks for your reply!
I'm using Jetson Xavier Nx(L4T R32.5.1, TensorRT-7.1.3) and encount the [interpolate](https://github.com/NVIDIA/TensorRT/issues/1194#issuecomment-837724904) transition problem, can I fix it through cerrect the interpolate plugin or the only thing I can do is just waiting for the next release of Jetpack(with TensorRT-8.0)?
Thanks!

**Comment by jaybdub** [comment]
Hi @kinglintianxia ,

I've started the following PR for integrating TensorRT 8.0 and addressing the issues that arise.

https://github.com/NVIDIA-AI-IOT/torch2trt/pull/599

One issue that was addressed was an API change for the interpolate layers when ``align_corners=True``.

That said, both TensorRT 7.1, and 8.0 shouldn't rely on the interpolate plugin, but instead use the native TensorRT layers.

Please let me know if this helps or you have any questions.

Best,
John

**Comment by kinglintianxia** [comment]
@jaybdub 
Thanks for your reply!
I have solved the interpolate transition problem by using `torch.nn.functional.interpolate(align_corner=True, size)` mode instead of `torch.nn.functional.interpolate(align_corner=True, scale_factor)`mode, this leeds to correct transition path.
Thanks again for your job!
