### ISSUE TITLE
Deconvolution INT8 conversion in AGX xavier with tensorcore

### ISSUE THREAD

**Issue by gaizerik** [NVIDIA-AI-IOT/torch2trt#601]
## Environment
- - -
HW : AGX Xavier
Jetpack version: 32.5.1-20210219084708
TensorRT version : 7.1.3.0
- - -

Hi,

I'm trying to speed-up my model using INT8 quantization on my AGX Xavier.
I have layers like, 

```
nn.Sequential(
            nn.Conv2d(256, 64, 3, padding=1, bias=bias),
            BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.ConvTranspose2d(64, 64, 2, 2),
            BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.ConvTranspose2d(64, 1, 2, 2), ........
```
After converting model, I've run nvprof and seems that ConvTranspose2d was not converted to tensorcore kernels.
Below is log.
```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
          Range:  100.00%  31.706ms       253  125.32us  98.953us  1.4160ms  [DECONVOLUTION #1] torch.nn.ConvTranspose2d.forward(ConvTranspose2d(64, 64, kernel_size=(2, 2), stride=(2, 2)), tensor(shape=[1, 64, 128, 256], dtype=torch.float32))
 GPU activities:   59.21%  242.42ms       253  958.20us  889.54us  3.9069ms  void nhwkuv_to_nkpq_ker<int=4>(char*, float const *, int, int, int, int, int, int, nvinfer1::rt::reduced_divisor, int, int, nvinfer1::rt::reduced_divisor, nvinfer1::rt::reduced_divisor, int, int, int, float const *, float const *)
                   36.72%  150.33ms       253  594.20us  542.15us  1.9700ms  trt_volta_fp32_igemm_int8_128x128_ldg4_relu_nn_v0
                    4.08%  16.686ms       253  65.954us  57.605us  924.10us  void nchw_to_nhwcin_ker<unsigned int>(unsigned int*, unsigned int const *, int, int, nvinfer1::rt::reduced_divisor, nvinfer1::rt::reduced_divisor, int, nvinfer1::rt::reduced_divisor, int, int, int, int, int, int)
      API calls:  100.00%  21.742ms       759  28.645us  20.610us  527.76us  cudaLaunchKernel
```
It is using trt_volta_fp32_igemm_int8_128x128_ldg4_relu_nn_v0. 
Unlike INT8 mode, I saw tensorcore kernel (volta_h884gemm_128x64_ldg8_nn) with FP16 mode as below
```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
          Range:  100.00%  36.821ms       253  145.54us  122.37us  393.33us  [DECONVOLUTION #1] torch.nn.ConvTranspose2d.forward(ConvTranspose2d(64, 64, kernel_size=(2, 2), stride=(2, 2)), tensor(shape=[1, 64, 128, 256], dtype=torch.float32))
 GPU activities:   45.79%  97.978ms       253  387.26us  362.77us  1.2018ms  void nhwuvk_to_npqk_ker<int=1>(__half*, __half const *, int, nvinfer1::rt::reduced_divisor, int, int, int, int, int, nvinfer1::rt::reduced_divisor, nvinfer1::rt::reduced_divisor, int, int, int, __half const *)
                   44.01%  94.164ms       253  372.19us  340.43us  1.1755ms  volta_h884gemm_128x64_ldg8_nn
                   10.20%  21.821ms       253  86.247us  79.491us  114.85us  void nhwc_to_nhwcin_ker<int=1>(int4*, int4 const *, int, int, nvinfer1::rt::reduced_divisor, nvinfer1::rt::reduced_divisor, int, nvinfer1::rt::reduced_divisor, int, int, int, int)
      API calls:  100.00%  21.229ms       759  27.970us  19.744us  103.33us  cudaLaunchKernel
```
Kernel "trt_volta_fp32_igemm_int8_128x128_ldg4_relu_nn_v0" takes time longer than "volta_h884gemm_128x64_ldg8_nn" because igemm kernels are not using tensorcore.
This layer meets condition of tensorcore in INT8. (all dimensions are multiple of 16).
Except this layer, I saw several layers which were converted to i8816 tensorcore kernels.

My questions are, 

1. Why was this layer not converted to tensorcore kernel like *i8816gemm* ?
2. On below link, volta architecture seems not supporting INT8 tensorcore acceleration.
    https://www.nvidia.com/en-us/data-center/tensor-cores/
    But apparently, my AGX Xavier is showing it is using i8816 kernel as below.
```
7.59%  384.82ms      3036  126.75us  26.690us  817.66us  trt_volta_int8_i8816cudnn_int8_128x128_ldg16_relu_small_nt_v1
```
    Is this information on nvidia homepage wrong?

**Comment by SrivastavaKshitij** [comment]
1. When TensorRT creates an engine , it goes for the kernel with the best runtime. It is quite possible, for that particular layer with a specific shape and size, TRT chose not to run an INT8 kernel as that kernel was not faster than the fp32 one. 

Now your question must be "why didnt it fallback to FP16". The reason is if TRT doesnt find INT8 kernel, it falls back to FP32. Make sure to set FP16 flag = True along with INT8 flag = True, so that it can fallback to FP16. 

2. Volta arch supports INT8 kernels but it doesnt support any acceleration for those kernels as you clearly mentioned "volta architecture seems not supporting INT8 tensorcore acceleration." You can run INT8 kernels on volta but it's not going to be any faster than FP16

**Comment by gaizerik** [comment]
@SrivastavaKshitij  Thanks!
