### ISSUE TITLE
Submitting a Pull Request

### ISSUE THREAD

**Issue by JWLee89** [NVIDIA-AI-IOT/torch2trt#606]
Hi, 

I want to make a pull request for some `tensorrt_converter` layers that I wrote but was having a few issues with permissions. 

Below are the steps that I took.

1. Checked out from master branch 
2. Created a new local branch
3. Added new converter.
4. Pushed new branch to upstream (error occurs here) 

I am assuming this is because I don't have permission to push to the torch2trt repository, so I was wondering:

What are the proper procedures for making a pull request? 

FYI I read through `CONTRIBUTING.md` - [link](https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/CONTRIBUTING.md)

Thank you for your time. 

Best regards,
Jay

P.S. I am uncertain as to whether this is the recommended approach for asking a question, but just in case my question flies under the radar.

**Comment by jaybdub** [comment]
Hi @JWLee89 ,

Thanks for the question.

Pushing directly to torch2trt isn't permitted.

I'd recommend making a personal fork of torch2trt, and then you can make the pull request from any branch in your fork.

Perhaps we should update the contributing guide with these instructions.

Please let me know if this helps or you run into any issues / questions.

Best,
John

**Comment by JWLee89** [comment]
Hi @jaybdub John,

Thank you for the answer. 
It makes perfect sense to make a personal fork and making the pull request from there. 

I think it may help out some people like myself who are not used to contributing to open source. 

I managed to make the pull request [here](https://github.com/NVIDIA-AI-IOT/torch2trt/pull/607).

Thank you for your help John.

Best regards,
Jay
