### ISSUE TITLE
Jetson Nano install error.

### ISSUE THREAD

**Issue by Richard-mei** [NVIDIA-AI-IOT/torch2trt#609]
I'am trying to install torch2trt at Jetson Nano, but `Illegal instruction` occured.

**Comment by ycdhqzhiai** [comment]
@Richard-mei  Has your problem been solved. I met the same problem

**Comment by Richard-mei** [comment]
> @Richard-mei Has your problem been solved. I met the same problem
This is because torch cannot be imported. try `export OPENBLAS_CORETYPE=ARMV8`

**Comment by ycdhqzhiai** [comment]
> export OPENBLAS_CORETYPE=ARMV8

@Richard-mei torch can be imported successfully. I tried to add an environment variable, but it didn't work

![image](https://user-images.githubusercontent.com/12273405/131447819-b0cb6ad7-e23c-4cf1-a3fb-8cd562e47bb9.png)

**Comment by Richard-mei** [comment]
> @Richard-mei torch can be imported successfully. I tried to add an environment variable, but it didn't work

I mean, the `Illegal instruction` caused by `import torch` in the second line of `setup.py`. You can test it.

**Comment by taylorshineboy** [comment]
> > export OPENBLAS_CORETYPE=ARMV8
> 
> @Richard-mei torch can be imported successfully. I tried to add an environment variable, but it didn't work
> 
> ![image](https://user-images.githubusercontent.com/12273405/131447819-b0cb6ad7-e23c-4cf1-a3fb-8cd562e47bb9.png)

Has your problem been solved. I met the same problem.After setting the variable it still didnot work

**Comment by guyiyifeurach** [comment]
I met the same problem, and I set OPENBLAS_CORETYPE correctly, and can ``import torch``. Any suggestions? Thank you!

**Comment by Richard-mei** [comment]
Hello, I remember that the “import torch” statement appeared in “setup.py”. This is the reason why the error is reported.
But I have forgotten the details, if necessary, I will reply to you tomorrow



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月21日 16:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NVIDIA-AI-IOT/torch2trt] Jetson Nano install error. (#609) |

I met the same problem, and I set OPENBLAS_CORETYPE correctly, and can import torch. Any suggestions? Thank you!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Richard-mei** [comment]
Hello, I remember that the “import torch” statement appeared in “setup.py”. This is the reason why the error is reported.
But I have forgotten the details, if necessary, I will reply to you tomorrow



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月08日 14:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NVIDIA-AI-IOT/torch2trt] Jetson Nano install error. (#609) |

export OPENBLAS_CORETYPE=ARMV8

@Richard-mei torch can be imported successfully. I tried to add an environment variable, but it didn't work

Has your problem been solved. I met the same problem.After setting the variable it still didnot work

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guyiyifeurach** [comment]
> > > export OPENBLAS_CORETYPE=ARMV8
> > 
> > 
> > @Richard-mei torch can be imported successfully. I tried to add an environment variable, but it didn't work
> > ![image](https://user-images.githubusercontent.com/12273405/131447819-b0cb6ad7-e23c-4cf1-a3fb-8cd562e47bb9.png)
> 
> Has your problem been solved. I met the same problem.After setting the variable it still didnot work

Illegal instruction, but torch can be imported. @Richard-mei

**Comment by guyiyifeurach** [comment]
> > > export OPENBLAS_CORETYPE=ARMV8
> > 
> > 
> > @Richard-mei torch can be imported successfully. I tried to add an environment variable, but it didn't work
> > ![image](https://user-images.githubusercontent.com/12273405/131447819-b0cb6ad7-e23c-4cf1-a3fb-8cd562e47bb9.png)
> 
> Has your problem been solved. I met the same problem.After setting the variable it still didnot work

![Uploading 捕获.PNG…]()

Illegal instruction, but torch can be imported. @Richard-mei

**Comment by chainfitness** [comment]
@guyiyifeurach @taylorshineboy @chitoku illegal instruction was caused by NumPy-1.19.5. just pip uninstall NumPy and then pip install numpy==1.19.4, it works for me

**Comment by Fischer-pixel** [comment]
wow,excellent!!

**Comment by mubrij** [comment]
![Screenshot 2024-05-27 183925](https://github.com/NVIDIA-AI-IOT/torch2trt/assets/123904799/f885c230-4bb9-489c-ae46-541349c45a68)

Am getting these error when importing torch and torchvision
