### ISSUE TITLE
mapping_names_resnets can not find

### ISSUE THREAD

**Issue by KeyKy** [NVIDIA-AI-IOT/torch2trt#618]
examples/contrib/quantization_aware_training/infer.py do not find mapping_names_resnets

**Comment by jzh1082** [comment]
Same problem. Do you slove it?

**Comment by VisuallStudio** [comment]
so do i !  did you slove it?

**Comment by VisuallStudio** [comment]
> so do i ! did you slove it?

emmmm maybe i find it ,  the orignal mathod name meybe the "mapping_names"  , which is in \utils\utilities.py.
