### ISSUE TITLE
[TensorRT 8] error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 

### ISSUE THREAD

**Issue by joytsay** [NVIDIA-AI-IOT/torch2trt#619]
So as mentioned in #559, #558, #444 
I have the same error:
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
when using `python3 setup.py install --plugins`
without the plugin flag it can build just fine with no errors
@jaybdub any fix? I really need plugins for interpolation layers used in my model

My environment:
- NGC docker image: nvcr.io/nvidia/tensorrt:21.08-py3
- torch==1.9.0+cu111
- torchvision==0.10.0+cu111

Error Log:
```
/usr/local/lib/python3.8/dist-packages/torch/include/pybind11/detail/init.h:63:64: error: invalid new-expression of abstract class type ‘torch2trt::InterpolatePlugin’
/usr/local/lib/python3.8/dist-packages/torch/include/pybind11/detail/init.h: In instantiation of ‘Class* pybind11::detail::initimpl::construct_or_initialize(Args&& ...) [with Class = torch2trt::GroupNormPlugin; Args = {long int, at::Tensor, at::Tensor, double}; typename std::enable_if<(! std::is_constructible<_Tp, _Args>::value), int>::type <anonymous> = 0]’:
/usr/local/lib/python3.8/dist-packages/torch/include/pybind11/detail/init.h:175:66:   required from ‘static void pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<torch2trt::GroupNormPlugin>; Extra = {pybind11::arg, pybind11::arg, pybind11::arg, pybind11::arg}; typename std::enable_if<(! Class::has_alias), int>::type <anonymous> = 0; Args = {long int, at::Tensor, at::Tensor, double}]’
/usr/local/lib/python3.8/dist-packages/torch/include/pybind11/pybind11.h:1346:9:   required from ‘pybind11::class_< <template-parameter-1-1>, <template-parameter-1-2> >& pybind11::class_< <template-parameter-1-1>, <template-parameter-1-2> >::def(const pybind11::detail::initimpl::constructor<Args ...>&, const Extra& ...) [with Args = {long int, at::Tensor, at::Tensor, double}; Extra = {pybind11::arg, pybind11::arg, pybind11::arg, pybind11::arg}; type_ = torch2trt::GroupNormPlugin; options = {}]’
torch2trt/plugins/plugins.cpp:20:144:   required from here
/usr/local/lib/python3.8/dist-packages/torch/include/pybind11/detail/init.h:63:64: error: invalid new-expression of abstract class type ‘torch2trt::GroupNormPlugin’
/usr/local/lib/python3.8/dist-packages/torch/include/pybind11/detail/init.h: In instantiation of ‘Class* pybind11::detail::initimpl::construct_or_initialize(Args&& ...) [with Class = torch2trt::GroupNormPlugin; Args = {const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; typename std::enable_if<(! std::is_constructible<_Tp, _Args>::value), int>::type <anonymous> = 0]’:
/usr/local/lib/python3.8/dist-packages/torch/include/pybind11/detail/init.h:175:66:   required from ‘static void pybind11::detail::initimpl::constructor<Args>::execute(Class&, const Extra& ...) [with Class = pybind11::class_<torch2trt::GroupNormPlugin>; Extra = {pybind11::arg}; typename std::enable_if<(! Class::has_alias), int>::type <anonymous> = 0; Args = {const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]’
/usr/local/lib/python3.8/dist-packages/torch/include/pybind11/pybind11.h:1346:9:   required from ‘pybind11::class_< <template-parameter-1-1>, <template-parameter-1-2> >& pybind11::class_< <template-parameter-1-1>, <template-parameter-1-2> >::def(const pybind11::detail::initimpl::constructor<Args ...>&, const Extra& ...) [with Args = {const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; Extra = {pybind11::arg}; type_ = torch2trt::GroupNormPlugin; options = {}]’
torch2trt/plugins/plugins.cpp:21:66:   required from here
/usr/local/lib/python3.8/dist-packages/torch/include/pybind11/detail/init.h:63:64: error: invalid new-expression of abstract class type ‘torch2trt::GroupNormPlugin’
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by labrat97** [comment]
I'm also having this issue.

**Comment by xd-Nanan** [comment]
me too。。。

**Comment by isra60** [comment]
I have the same problem with Jetpack 4.6 and the pytorch docker....

**Comment by chitoku** [comment]
It looks like `IPLuginV2` virtual base class is updated in TensorRT and some definition that has been marked deprecated is finally gone, so those need to be taken cared.
I came up with this https://github.com/NVIDIA-AI-IOT/torch2trt/pull/627 and it looked like it solved the issue and I got to install torch2trt on JetPack 4.6.

This is not yet tested, so if anyone can verifty the PR, that would be great.

**Comment by joytsay** [comment]
@chitoku I tested #627 on `NGC docker image: nvcr.io/nvidia/tensorrt:21.08-py3`
and it seems to compile successful with no errors with the plugin flag:  `python3 setup.py install --plugins`
Thanks for the update, i will close this issue.

P.S.  I encountered another issue:
`fp16_mode, strict_type_constraints incompatibility, and max_workspace_size incompatibility with TRT v8+ `
and fixed it with these commit in the following fork:
https://github.com/gcunhase/torch2trt/commits/master

**Comment by laisimiao** [comment]
> @chitoku I tested #627 on `NGC docker image: nvcr.io/nvidia/tensorrt:21.08-py3` and it seems to compile successful with no errors with the plugin flag: `python3 setup.py install --plugins` Thanks for the update, i will close this issue.
> 
> P.S. I encountered another issue: `fp16_mode, strict_type_constraints incompatibility, and max_workspace_size incompatibility with TRT v8+ ` and fixed it with these commit in the following fork: [8f74290#diff-f682ce583d8646e112002fb3631f7d205b63aae7b0ca673b020fed7244d4ed38](https://github.com/NVIDIA-AI-IOT/torch2trt/commit/8f742904d603fcde4fe521baa31bdc18002c23cb#diff-f682ce583d8646e112002fb3631f7d205b63aae7b0ca673b020fed7244d4ed38)

Could you please discuss more detailed try using #627? Because I still have the same problem using TRT 8.2.1 and cuda10.2 on ubuntu18.04
