### ISSUE TITLE
Error while convert yolov5s.pt 

### ISSUE THREAD

**Issue by github2016-yuan** [NVIDIA-AI-IOT/torch2trt#624]
I follow cmd like below to convert **alexnet.pt** to **alexnet_trt.pth**  successfully.

```
import torch
from torch2trt import torch2trt
from torchvision.models.alexnet import alexnet

# create some regular pytorch model...
model = alexnet(pretrained=True).eval().cuda()

# create example data
x = torch.ones((1, 3, 224, 224)).cuda()

# convert to TensorRT feeding sample data as input
model_trt = torch2trt(model, [x])

y = model(x)
y_trt = model_trt(x)

# check the output against PyTorch
print(torch.max(torch.abs(y - y_trt)))
torch.save(model_trt.state_dict(), 'alexnet_trt.pth')
```

Now I want to convert **yolov5s.pt** trained by myself (https://github.com/ultralytics/yolov5).
After some changes, I get the following  error:

```
/home/nvidia/.local/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3agg.py:16: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "
/home/nvidia/Downloads/yuan/torch2trt-master/utils/plots.py:22: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'GTK3Agg' by the following code:
  File "mytrt.py", line 4, in <module>
    from models.yolo import Model
  File "/home/nvidia/Downloads/yuan/torch2trt-master/models/yolo.py", line 15, in <module>
    from models.common import *
  File "/home/nvidia/Downloads/yuan/torch2trt-master/models/common.py", line 17, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "/home/nvidia/Downloads/yuan/torch2trt-master/utils/datasets.py", line 25, in <module>
    from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
  File "/home/nvidia/Downloads/yuan/torch2trt-master/utils/augmentations.py", line 10, in <module>
    from utils.general import colorstr, segment2box, resample_segments, check_version
  File "/home/nvidia/Downloads/yuan/torch2trt-master/utils/general.py", line 28, in <module>
    from utils.metrics import box_iou, fitness
  File "/home/nvidia/Downloads/yuan/torch2trt-master/utils/metrics.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/home/nvidia/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/home/nvidia/.local/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('Agg')  # for writing to files only
Traceback (most recent call last):
  File "mytrt.py", line 89, in <module>
    model_trt = torch2trt(model, [x])
  File "/home/nvidia/Downloads/yuan/torch2trt-master/torch2trt/torch2trt.py", line 552, in torch2trt
    outputs = module(*inputs)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/Downloads/yuan/torch2trt-master/models/yolo.py", line 122, in forward
    return self.forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/nvidia/Downloads/yuan/torch2trt-master/models/yolo.py", line 153, in forward_once
    x = m(x)  # run
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/Downloads/yuan/torch2trt-master/models/yolo.py", line 62, in forward
    y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i]) * self.stride[i]  # xy
  File "/home/nvidia/Downloads/yuan/torch2trt-master/torch2trt/torch2trt.py", line 300, in wrapper
    converter["converter"](ctx)
  File "/home/nvidia/Downloads/yuan/torch2trt-master/torch2trt/converters/getitem.py", line 30, in convert_tensor_getitem
    input_trt = input._trt
AttributeError: 'Tensor' object has no attribute '_trt'
```

I read lots of issues and find this  #527 

It said that after add converter-silu, yolov5s.pt can be converted successfully.
I add some print in ../torch2trt/converts/silu.py and it is called indeed.
But as  I mentioned above,  yolov5s.pt still can not be converted and giving the error: **AttributeError: 'Tensor' object has no attribute '_trt'**
@jaybdub @421psh
Would you mind giving me some advice ? Thanks.

**Comment by fabiozappo** [comment]
Did you get any solution to your problem? I'm also trying to convert yolov5 to tensorrt with this repo

**Comment by github2016-yuan** [comment]
Not yet. Try .pt->onnx->trt instead of this repo.

**Comment by wwqgtxx** [comment]
You need set before convert
```python
model.model[-1].export = True
```
when detect add a warpper like this:
```python
def trt_model_warp(model, model_trt):
    self = model.model[-1]  # get Detect() layer

    def _decoder(x, *k, **kk):
        # inference by trt
        x = model_trt(x)

        # running missing part of Detect.forward() when self.export=True
        z = []  # inference output
        for i in range(self.nl):
            bs, _, ny, nx, _ = x[i].shape

            if self.grid[i].shape[2:4] != x[i].shape[2:4]:
                self.grid[i] = self._make_grid(nx, ny).to(x[i].device)

            y = x[i].sigmoid()
            y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i]) * self.stride[i]  # xy
            y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
            z.append(y.view(bs, -1, self.no))

        return torch.cat(z, 1), x

    return _decoder
```
finally replace model before inference
```python
model = trt_model_warp(model, model_trt)
```

NOTICE: you should set `half` to `False` in `detect.py` but can set `fp16_mode=True,` when export by torch2trt

**Comment by github2016-yuan** [comment]
Here are two solutions:
(1) follow @wwqgtxx 

> You need set before convert
> 
> ```python
> model.model[-1].export = True
> ```
> 
> when detect add a warpper like this:
> 
> ```python
> def trt_model_warp(model, model_trt):
>     self = model.model[-1]  # get Detect() layer
> 
>     def _decoder(x, *k, **kk):
>         # inference by trt
>         x = model_trt(x)
> 
>         # running missing part of Detect.forward() when self.export=True
>         z = []  # inference output
>         for i in range(self.nl):
>             bs, _, ny, nx, _ = x[i].shape
> 
>             if self.grid[i].shape[2:4] != x[i].shape[2:4]:
>                 self.grid[i] = self._make_grid(nx, ny).to(x[i].device)
> 
>             y = x[i].sigmoid()
>             y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i]) * self.stride[i]  # xy
>             y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
>             z.append(y.view(bs, -1, self.no))
> 
>         return torch.cat(z, 1), x
> 
>     return _decoder
> ```
> 
> finally replace model before inference
> 
> ```python
> model = trt_model_warp(model, model_trt)
> ```
> 
> NOTICE: you should set `half` to `False` in `detect.py` but can set `fp16_mode=True` when export by torch2trt

(2)try yolov5s.pt->onnx->trt
    It works for me.

**Comment by DuyguSerbes** [comment]
@github2016-yuan Hello, which repos did you used for this conversion (yolov5s.pt->onnx->trt)?

**Comment by redzhepdx** [comment]
> You need set before convert
> 
> ```python
> model.model[-1].export = True
> ```
> 
> when detect add a warpper like this:
> 
> ```python
> def trt_model_warp(model, model_trt):
>     self = model.model[-1]  # get Detect() layer
> 
>     def _decoder(x, *k, **kk):
>         # inference by trt
>         x = model_trt(x)
> 
>         # running missing part of Detect.forward() when self.export=True
>         z = []  # inference output
>         for i in range(self.nl):
>             bs, _, ny, nx, _ = x[i].shape
> 
>             if self.grid[i].shape[2:4] != x[i].shape[2:4]:
>                 self.grid[i] = self._make_grid(nx, ny).to(x[i].device)
> 
>             y = x[i].sigmoid()
>             y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i]) * self.stride[i]  # xy
>             y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
>             z.append(y.view(bs, -1, self.no))
> 
>         return torch.cat(z, 1), x
> 
>     return _decoder
> ```
> 
> finally replace model before inference
> 
> ```python
> model = trt_model_warp(model, model_trt)
> ```
> 
> NOTICE: you should set `half` to `False` in `detect.py` but can set `fp16_mode=True` when export by torch2trt

This solution is a bit inadequate and misleading. Could you provide a working script for yolov5?
