### ISSUE TITLE
No module named 'torch2trt.module_test'

### ISSUE THREAD

**Issue by hanoul1124** [NVIDIA-AI-IOT/torch2trt#626]
All installation and execution were performed in colab. tensorRT is version 7.0.0.11. The following error occurs when executing the following statement.
`from torch2trt import torch2trt`

Already done setup.py install already.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-132-07feadd741f5> in <module>()
      1 import torch
----> 2 from torch2trt import torch2trt
      3 from torchvision.models.alexnet import alexnet

2 frames
/content/drive/My Drive/PF_AFN/torch2trt/torch2trt/converters/AdaptiveAvgPool2d.py in <module>()
      1 from torch2trt.torch2trt import *
----> 2 from torch2trt.module_test import add_module_test
      3 
      4 
      5 @tensorrt_converter('torch.nn.AdaptiveAvgPool2d.forward')

ModuleNotFoundError: No module named 'torch2trt.module_test'

Also, if I use `import torch2trt` instead of `from torch2trt import torch2trt`, the following error occurs and execution is impossible.

in case `model_trt = torch2trt(model, [x])`,

TypeError                                 Traceback (most recent call last)
<ipython-input-7-8cc4b6409631> in <module>()
      6 
      7 # convert to TensorRT feeding sample data as input
----> 8 model_trt = torch2trt(model, [x])

TypeError: 'module' object is not callable

and `model_trt = torch2trt.torch2trt(model, [x])`,
>>>>>

AttributeError                            Traceback (most recent call last)
<ipython-input-6-3d072e788155> in <module>()
      6 
      7 # convert to TensorRT feeding sample data as input
----> 8 model_trt = torch2trt.torch2trt(model, [x])

AttributeError: module 'torch2trt' has no attribute 'torch2trt'

**Comment by hanoul1124** [comment]
solved.

**Comment by victormatheus** [comment]
I'm having this same issue actually and I have already done:

```
git clone https://github.com/NVIDIA-AI-IOT/torch2trt
cd torch2trt
python setup.py install
```

from torch2trt import torch2trt
ModuleNotFoundError: No module named 'torch2trt.module_test'

This is on latest master.

**Comment by victormatheus** [comment]
Using TRT7 instead of TRT8 fixes the issue.
