### ISSUE TITLE
How to enlarge the batch size

### ISSUE THREAD

**Issue by reborm** [NVIDIA-AI-IOT/torch2trt#63]
Thanks for sharing this amazing work! The torch2trt is good when using single image, but when I expand the number of pictures, it doesn't work. I desire to when does the torch2trt support multiple image input? Thanks for your time!!!

**Comment by jaybdub** [comment]
Hi reborm,

Thanks for reaching out.  You should be able to expand the maximum batch size by passing the argument ``max_batch_size``.  For example, 

```python
model_trt = model(model, [data], max_batch_size=8)
```

Will allow for up to 8 images at runtime

```python
output = model_trt(data)
```

Please let me know if this works for you or you run into any issues.

Best,
John

**Comment by reborm** [comment]
Wow, thanks for replying so quickly. I haven't noticed this parameter before, now it's ok!!!!! This is perfect!!!!
