### ISSUE TITLE
Error between y and y_trt is very high

### ISSUE THREAD

**Issue by vishnuvarreddy** [NVIDIA-AI-IOT/torch2trt#703]
Hi, I am trying to convert OSNet (https://github.com/KaiyangZhou/deep-person-reid) to torchtrt model. Though the inference speed is optimized a lot, the difference between torch model y and trt model y_trt is very high. I tried x.contiguous() as well but no luck. 

I am not sure which layer in the model is not implemented in the torch2trt, is ADAPTIVEAVGPOOL2D (https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveAvgPool2d.html) and INSTANCENORM2D (https://pytorch.org/docs/stable/generated/torch.nn.InstanceNorm2d.html) are implemented in torch2trt??

**Comment by vishnuvarreddy** [comment]
Resolved it.

**Comment by a227799770055** [comment]
@vishnuvarreddy  Hi, can you show how ti solve the problem?
I meet the same problem as well.
