### ISSUE TITLE
Error Code 1: Cuda Runtime (CUDA driver version is insufficient for CUDA runtime version)

### ISSUE THREAD

**Issue by wxthu** [NVIDIA-AI-IOT/torch2trt#711]
when I run alexnet in pytorch using torch2trt, I met the above errors and cannnot terminate programs.
cuda version:10.2
tensorrt version:8.4.0.6

**Comment by wxthu** [comment]
fix

**Comment by sydat2701** [comment]
> when I run alexnet in pytorch using torch2trt, I met the above errors and cannnot terminate programs. cuda version:10.2 tensorrt version:8.4.0.6

sir, how could you solve this problem? I faced the same problem. Hope your answer. Thanks
