### ISSUE TITLE
Monkey patching `torch.Tensor.__getitem__` returns an extra dimension outside of the TRT conversion scope when running Python versions < 3.7.0

### ISSUE THREAD

**Issue by chaoz-dev** [NVIDIA-AI-IOT/torch2trt#738]
Posting this issue for posterity, as the issue appears to be resolved when running with Python versions >= 3.7.0 (according to my testing) and so no fixes to this codebase are required at this time. A hack-around is given below for users still running Python versions < 3.7.0. 

**Issue**
After running the `torch2trt(...)` conversion process, regular calls to `torch.Tensor.__getitem__` (outside of TRT conversion) return an extra dimension if the input argument is a `torch.Tensor`. This issue appears to occur in Python versions < 3.7.0.

This can be observed with the following script (`getitem.py`):
```  
  import logging    
  import tensorrt    
  import torch    
  import torch2trt    
      
      
  logging.basicConfig(level=logging.INFO)    
  torch.manual_seed(0)    
      
  DEVICE = 'cuda:0'    
  TENSOR = torch.randn(2, 3).to(DEVICE)    
  MASK = torch.tensor([True]*2, dtype=torch.bool).to(DEVICE)    
      
      
  def call_getitem(tensor, mask):    
      return tensor[mask]    
      
      
  class Model(torch.nn.Module):    
      def __init__(self):    
          super().__init__()    
      
      def forward(self, tensor, mask):    
          return call_getitem(tensor, mask)    
      
      
  if __name__ == "__main__":    
      out = call_getitem(TENSOR, MASK)    
      print(f'Expected getitem output shape: {out.shape}')    
      
      model = Model().eval().to(DEVICE)    
      out = model(TENSOR, MASK)    
      print(f'Expected model output shape: {out.shape}')    
      
      model_trt = torch2trt.torch2trt(    
          model, [TENSOR, MASK], max_batch_size=TENSOR.shape[0], log_level=tensorrt.Logger.INFO    
      )    
      out = model_trt(TENSOR, MASK)    
      print(f'TRT model output shape: {out.shape}')    
      
      model = Model().eval().to(DEVICE)    
      out = model(TENSOR, MASK)    
      print(f'Non-TRT model output shape: {out.shape}')    
      
      out = call_getitem(TENSOR, MASK)    
      print(f'getitem output shape: {out.shape}')    
```
which outputs the following:
```
(torch2trt-master-py3.6.9) ~/workspace/pytorch-scratch/torch2trt $ python getitem.py
Expected getitem output shape: torch.Size([2, 3])
Expected model output shape: torch.Size([2, 3])
...
TRT model output shape: torch.Size([2, 3])
Non-TRT model output shape: torch.Size([1, 2, 3])
getitem output shape: torch.Size([1, 2, 3])
```
Note that the `Non-TRT model` and `getitem` output shapes are now `[1, 2, 3]` following the TRT conversion, when they should remain `[2, 3]`. 

Digging into this problem more, it appears that the monkey patching is causing the issue and can be reproduced outside of torch2trt entirely. This can be observed with the following script (`monkeypatch.py`):
```
  import logging    
  import torch    
      
      
  logging.basicConfig(level=logging.INFO)    
  torch.manual_seed(0)    
      
  DEVICE = 'cuda:0'    
  TENSOR = torch.randn(2, 3).to(DEVICE)    
  MASK = torch.tensor([True]*2, dtype=torch.bool).to(DEVICE)    
      
  def getitem_wrapper(method=torch.Tensor.__getitem__):    
      def wrapper(*args, **kwargs):    
          return method(*args, **kwargs)            
      return wrapper                
                                       
                        
  def set_method(method):    
      exec('torch.Tensor.__getitem__ = method')    
                             
                                                   
  def call_getitem(tensor, mask):    
      return tensor[mask]    
                                     
                             
  class Model(torch.nn.Module):    
      def __init__(self):    
          super().__init__()       
                             
      def forward(self, tensor, mask):    
          return call_getitem(tensor, mask)    
                                          
                                               
  if __name__ == "__main__":    
      out = call_getitem(TENSOR, MASK)    
      print(f'Expected getitem output shape: {out.shape}')    
                                          
      model = Model().eval().to(DEVICE)                       
      out = model(TENSOR, MASK)    
      print(f'Expected model output shape: {out.shape}')    
                                   
      # Break __getitem__ by monkey patching.               
      set_method(getitem_wrapper())    
                                                 
      out = call_getitem(TENSOR, MASK)    
      print(f'getitem output shape: {out.shape}')    
                                          
      model = Model().eval().to(DEVICE)              
      out = model(TENSOR, MASK)    
      print(f'Model output shape: {out.shape}')    
```
which outputs the following:
```
(torch2trt-master-py3.6.9) ~/workspace/pytorch-scratch/torch2trt $ python monkeypatch.py
Expected getitem output shape: torch.Size([2, 3])
Expected model output shape: torch.Size([2, 3])
getitem output shape: torch.Size([1, 2, 3])
Model output shape: torch.Size([1, 2, 3])
```
Note that after monkey patching `torch.Tensor.__getitem__`, the op returns a different shape than what was originally returned. This occurs despite monkey patching the definition to itself and with the same input arguments. 

**Environment**
This was tested using Conda:
- Python versions 3.6.9 and 3.7.0.
- PyTorch 1.11
- TensorRT 8.4.0.6
- CUDA 11.6 (with compatible cuBLAS and cuDNN)
- torch2trt master commit `953d60039e0c81e90eea467c3df2e6e3f7040242`

**Solution**
From my testing, it appears the issue is no longer present when using Python versions >= 3.7.0. As such there is no immediate need for a fix.

However, for Python < 3.7.0 users, the following hack-around _should_ address the issue transparently (although more testing may be needed):

When monkey patching `torch.Tensor.__getitem__` back to its original definition, we can instead redefine it to its "correct" definition instead of its now incorrect original definition. We do this by monkey patching the definition to a new wrapper function that intercepts the `torch.Tensor` input argument and wrapping it in a `tuple` before passing it on to the original definition -- this seems to resolve issue.

The changes look like the following:
In `torch2trt/torch2trt.py`:

Add the following function definition:
```
+ def getitem_wrapper(method=torch.Tensor.__getitem__):    
+     def wrapper(arg0, arg1):    
+         if type(arg1) is torch.Tensor:    
+             arg1 = (arg1, )    
+         return method(arg0, arg1)    
+     return wrapper    
```
Then call this function appropriately for `torch.Tensor.__getitem__` in the `__exit__` method in `ConversionHook`:
```
  class ConversionHook(object):    
  ...
        def __exit__(self, type, val, tb):    
~         if '__getitem__' in self.converter['method_str']:    
+             self._set_method(getitem_wrapper())    
+         else:    
+             self._set_method(self.converter['method_impl'])    
```

Patching these changes and rerunning the above `getitem.py` script now returns the correct output:
```
(torch2trt-master-py3.6.9) ~/workspace/pytorch-scratch/torch2trt $ python getitem.py
Expected getitem output shape: torch.Size([2, 3])
Expected model output shape: torch.Size([2, 3])
...
TRT model output shape: torch.Size([2, 3])
Non-TRT model output shape: torch.Size([2, 3])
getitem output shape: torch.Size([2, 3])
```

**Comment by chaoz-dev** [comment]
@SrivastavaKshitij @jaybdub for vis.

I can push a cleaner version of the above solution as a PR if we decide we want to support this in master.

**Comment by chaoz-dev** [comment]
This likely addresses issue #270 as well.

**Comment by jaybdub** [comment]
Hi @chaoz-dev ,

Thanks for spending the time to investigate this!  Seems like several others were frustrated with the same issue, I think this post will help them a lot.

Such a strange issue, and a pretty creative workaround!

I'm not yet sure if we should merge.  It would be great if there were a solution that returns things to their original state (before torch2trt is called), but perhaps the tuple wrapping solution will solve the immediate need.

- Any idea why the issue occurs in Python 3.6.9 but not 3.7.0?
- Any issues you can foresee with the tuple wrapping workaround?

Best,
John

**Comment by SrivastavaKshitij** [comment]
Hi @jaybdub :

If we dont want to merge this in master, then another workaround is to create a patch under the `scripts` folder, update build command to include this optional patch, and update the documentation to reflect this potential workaround so that any user who is facing a similar situation can patch it on their end. 

How does this sound?

**Comment by chaoz-dev** [comment]
Hey @jaybdub,

As far as why this issue only occurs on Python versions < 3.7.0, I'm not entirely sure yet, but I currently suspect a bug or a change in definition in the Python ABI which PyTorch relies on when converting from Python to C++/C. Stepping through the code in Python and looking at the C++ PyTorch definition for `__getitem__`, it appears that this extra dimension is likely unintentionally added before any real processing even occurs, on the first ingest of the `torch.Tensor` argument of the first iteration of the recursive function call (continue reading for more details).

With regards to the tuple wrap workaround, I currently do not foresee any major issues. I don't know if other input types suffer from this same issue (in which case we may need to expand the current hack to encompass these other input types), but for a single `torch.Tensor` input into `torch.Tensor.__getitem__`, this should work exactly as the non-tuple wrapped version. In fact, the hack actually works by relying on the PyTorch definitions themselves:

In Python, I believe the `torch.Tensor.__getitem__` signature should be:
```
# torch/_C/__init__.pyi 

def __getitem__(self, indices: Union[None, _int, slice, Tensor, List, Tuple]) -> Tensor: ...
```

This should eventually call the C++ implementation:
```
// torch/csrc/autograd/python_variable_indexing.cpp

PyObject* THPVariable_getitem(PyObject* self, PyObject* index) {...}
```

This implies that `torch.Tensor.__getitem__` should only take two arguments: `self` (aka. the tensor being sliced/indexed), and the indexing argument (in our case, originally a single `torch.Tensor`). But looking at the definition of `THPVariable_getitem`, there's a call internally to wrap this second argument in a tuple as well!
```
    // wrap index in a tuple if it's not already one    
    THPObjectPtr holder = wrapTuple(index);                  
```
where `wrapTuple(...)` will wrap `index` in a `tuple` if it's not already wrapped; otherwise, it just converts the `tuple` into the C++ representation of said `tuple`. 

So by pre-wrapping our index `torch.Tensor` argument, we're actually just performing the exact same function earlier in Python instead of in the `THPVariable_getitem` C++ function. This also hints at where the underlying issue is, as we are bypassing the C++ tuple wrapping logic with our workaround. In any case, because we're still using the same compatible definitions here, I don't think there should be any major issues with performing the tuple wrapping logic ourselves.

**Comment by chaoz-dev** [comment]
#750 as a temp PR for addressing this issue directly. 
Will create a new PR for building and patching separately for landing onto master.
