### ISSUE TITLE
the saved trt model can't deserialize by C++！

### ISSUE THREAD

**Issue by jcyhcs** [NVIDIA-AI-IOT/torch2trt#753]
hi.professor:
refer to example convert alexnet to tensorrt, then deserialize with c++, got error:
Error Code 1: Serialization (Serialization assertion magicTagRead == magicTag failed.Magic tag does not match)
[ERROR]: 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
please help!

**Comment by toshalpatel** [comment]
hey @jcyhcs how did you solve this?
