### ISSUE TITLE
#error This file was gener     ated by an older version of protoc which is

### ISSUE THREAD

**Issue by waries** [NVIDIA-AI-IOT/torch2trt#78]
When I run "python setup.py install --plugins", there is an error 
![image](https://user-images.githubusercontent.com/17260141/65874851-f8d97800-e3b8-11e9-801f-4fdb76327315.png)
Can you tell me which version of protoc you are using?

**Comment by GYxiaOH** [comment]
i meet the same problem ,do you solve it
