### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by Wallace00V** [NVIDIA-AI-IOT/torch2trt#8]
'TRTModule' object has no attribute '_register_state_dict_hook'

my pytorch version is 0.4.1
tensorrt5.0.2.6

**Comment by jaybdub** [comment]
Hi Wallace00V,

Thanks for reaching out.  The ``torch.nn.Module._register_state_dict_hook`` method is used to attach a callback to the ``state_dict()`` method of a PyTorch module serialize the TensorRT engine.  This is used for saving the model.

This repository is developed against PyTorch 1.1.  I would guess this method was not available in PyTorch ``0.4.1``, so unfortunately, it may not be supported.

Best,
John
