### ISSUE TITLE
Manually load int8 weight from QAT model (quantized with pytorch-quantization-tool)

### ISSUE THREAD

**Issue by thancaocuong** [NVIDIA-AI-IOT/torch2trt#816]
After done QAT, I save state dict of the quantized model and found in the state dict, the weight for a simple conv2d consists of _input_quantizer._amax and _weight_quantizer._amax. So I want to create Conv2d with TensorRT python API and manually load the weight. So how can I do that? I would appreciate that you can help me. thanks (I'm using TensorRT 8.2)

**Comment by thancaocuong** [comment]
@SrivastavaKshitij  I think that you can help me to answer this question

**Comment by SrivastavaKshitij** [comment]
Hi @thancaocuong : 

1. You will have to convert `_amax` value to corresponding `scale` and `zero_point` as `IQuantize` and `IDequantize` nodes expect scale and zero point. zero_point being 0 because TRT today only supports symmetric quantization. 

In this [function ](https://github.com/NVIDIA/TensorRT/blob/7d2a70a18bb0e5cf76b9a82eb0db0fb20e89b034/tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py#L279)  , Nvidia converts amax to scale and zero point. 

This is my working solution to add a pair of quantization and dequantization node for both weights and input

```
scale_trt = ctx.network.add_constant(tuple(module.infer_input_quantizer.quant_scale.shape),module.infer_input_quantizer.quant_scale.detach().cpu().numpy())
    input_quantizer = ctx.network.add_quantize(
            input=input_trt,
            scale=scale_trt.get_output(0))
    
    if hasattr(module.infer_input_quantizer,'quant_axis'):
        input_quantizer.axis = module.infer_input_quantizer.quant_axis.to(torch.long).item()
    else:
        input_quantizer.axis=0

    input_dequantizer = ctx.network.add_dequantize(
            input = input_quantizer.get_output(0),
            scale = scale_trt.get_output(0))

    if hasattr(module.infer_input_quantizer,'quant_axis'):
        input_dequantizer.axis = module.infer_input_quantizer.quant_axis.to(torch.long).item()
    else:
        input_dequantizer.axis=0
    
    # Weight quantization
    ## currently not using weight quantizer, waiting for a resolution on the issue.
    kernel_trt = ctx.network.add_constant(tuple(kernel.shape),kernel.cpu().numpy())
    scale_trt = ctx.network.add_constant(tuple(module.infer_weight_quantizer.quant_scale.shape),module.infer_weight_quantizer.quant_scale.detach().cpu().numpy()) 
    weight_quantizer = ctx.network.add_quantize(
            input=kernel_trt.get_output(0),
            scale=scale_trt.get_output(0))
    
    if hasattr(module.infer_weight_quantizer,'quant_axis'):
        weight_quantizer.axis = module.infer_weight_quantizer.quant_axis.to(torch.long).item()
    else:
        weight_quantizer.axis = 0
    
    weight_dequantizer = ctx.network.add_dequantize(
            input = weight_quantizer.get_output(0),
            scale = scale_trt.get_output(0))

if hasattr(module.infer_weight_quantizer,'quant_axis'):
        weight_dequantizer.axis = module.infer_weight_quantizer.quant_axis.to(torch.long).item()
    else:
        weight_dequantizer.axis = 0

    # Creating dummy kernel to pass creation of conv layer. will substitute this with an actual kernel later
    dummy_kernel = trt.Weights()

    layer = ctx.network.add_convolution_nd(
        input=input_dequantizer.get_output(0),
        num_output_maps=module.out_channels,
        kernel_shape=kernel_size,
        kernel=dummy_kernel, 
        bias=bias)
    layer.stride_nd = stride
    layer.padding_nd = padding
    layer.dilation_nd = dilation
    layer.set_input(1,weight_dequantizer.get_output(0))

    if module.groups is not None:
        layer.num_groups = module.groups
    
 
```

Now ofcourse you will have to make changes to `module.infer_input_quantizer.quant_scale` because you have `_input_quantizer._amax` 

Let me know if you need any help. I hope this give you a good starting point to work with

**Comment by thancaocuong** [comment]
@SrivastavaKshitij  thanks a lot for your help. I will try as you recommend

**Comment by thancaocuong** [comment]
@SrivastavaKshitij  
an error occurs when set the input with this line
```layer.set_input(1,weight_dequantizer.get_output(0))```
Error: 
```[Convolution]: Can not set more than one input while using Implicit batch size```
How can I manage to solve this?

**Comment by thancaocuong** [comment]
![image](https://user-images.githubusercontent.com/43930651/198920344-ca89a614-54f3-4304-81c3-b81ddbd77f2d.png)
I've tried your solution with my network, the network was initialized okay, But when serializing to the inference engine, it throws this error? Do you know what I need to change?
@SrivastavaKshitij
