### ISSUE TITLE
Problem with convertation 

### ISSUE THREAD

**Issue by razbiralochka** [NVIDIA-AI-IOT/torch2trt#856]
[TRT] [E] 3: [builderConfig.cpp::canRunOnDLA::382] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builderConfig.cpp::canRunOnDLA::382, condition: dlaEngineCount > 0

**Comment by jaybdub** [comment]
Hi @razbiralochka ,

Thanks for reaching out.

Which platform are you running on?  Are you on Jetson Orin?

Best,
John

**Comment by razbiralochka** [comment]
Hello, I use Jetson Nano 2GB

**Comment by Armandpl** [comment]
Hi, I'm running into the same issue trying to convert a resnet18 to trt. I'm using a Jetson Nano 4GB. This code was previously running without issue, unsure what's changed?

**Comment by drkhanusa** [comment]
I have the same issue when trying to convert torch2tensorrt. I'm using a Jetson Nano 4 GB too.

[06/23/2023-13:07:48] [TRT] [E] 3: [builderConfig.cpp::canRunOnDLA::382] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builderConfig.cpp::canRunOnDLA::382, condition: dlaEngineCount > 0

**Comment by drkhanusa** [comment]
@razbiralochka  Hi bro, I see you closed this topic, so how can you resolve this issue?
