### ISSUE TITLE
INVALID_ARGUMENT: Can not find binding of given name

### ISSUE THREAD

**Issue by xsacha** [NVIDIA-AI-IOT/torch2trt#86]
I receive this error whenever I try to run my model (Resnet IR_50 or Resnet IR_152) converted to torchrt on an input.

Code:
```Python
    with torch.no_grad():
        input = torch.randn(1,3,112,112)
        input = input.to(device)
        jit = torch.jit.trace(backbone, input)
        trt = torch2trt(backbone, [input])
        for i in range(10):
            tic = time.time()
            x = trt(input)
            torch.cuda.synchronize()
            print('trt forward time: {:.4f}'.format(time.time() - tic))
            tic = time.time()
            y = backbone(input)
            torch.cuda.synchronize()
            print('backbone forward time: {:.4f}'.format(time.time() - tic))
            tic = time.time()
            z = jit(input)
            torch.cuda.synchronize()
            print('jit forward time: {:.4f}'.format(time.time() - tic))
            print('TRT Error: ', torch.max(torch.abs(y - x)))
            print('JIT Error: ', torch.max(torch.abs(y - z)))
```

Output:
```
... x 10
[TensorRT] ERROR: INVALID_ARGUMENT: Can not find binding of given name
trt forward time: 0.0031
backbone forward time: 0.0067
jit forward time: 0.0065
TRT Error:  tensor(1.6327, device='cuda:0')
JIT Error:  tensor(6.1989e-06, device='cuda:0')
```

Sidenote: I had to add synchronize in because torch.cudnn.benchmark = True causes a crash in torch2trt

**Comment by jaybdub** [comment]
Hi xsacha,

Thanks for reaching out!  I haven't witnessed this before using torch2trt.

Are you able to share the model source that you're using?

Best,
John

**Comment by xsacha** [comment]
@jaybdub 
It happens with these models: https://github.com/ZhaoJ9014/face.evoLVe.PyTorch/blob/master/backbone/model_irse.py

**Comment by jaybdub** [comment]
Hi xsacha,

It seemed the ``torch.nn.functional.prelu`` was not yet implemented, and was used in those models.

I've implemented it and tested ``IR_50``.   It is merged into master.

Please let me know if this works for you, or if you run into any issues.

Best,
John

**Comment by xsacha** [comment]
Thanks!

**Comment by jaybdub** [comment]
Hi xacha,

Thanks for sharing.  

Do you mind sharing the system architecture you're using (ie: CPU/GPU/MEM)?  

Also, you may see improvements using reduced/mixed precision.

```python
model = model.eval().half()
input = input.half()
model_trt = torch2trt(model, [input], fp16_mode=True)
```

Please let me know if this helps.

Best,
John

**Comment by jaybdub** [comment]
On Jetson Xavier / PyTorch 1.2 / TensorRT 5.1 I see the following  FPS

```bash
PyTorch: 52.804743
PyTorch (JIT): 84.671527
TensorRT: 160.455885
```

Using the following code to evaluate

```python
import torch
from torch2trt import torch2trt
import time
from ir_net import *


def benchmark_throughput(model, data, num_iter=50):
    with torch.no_grad(), torch.jit.optimized_execution(True):
        model(*tuple(data)) #omit first run
        
        t0 = time.time()
        torch.cuda.current_stream().synchronize()
        for i in range(num_iter):
            out = model(*tuple(data))
        torch.cuda.current_stream().synchronize()
        t1 = time.time()
    
    return float(num_iter) / (t1 - t0)


dtype = torch.float16
device = torch.device('cuda')
data = torch.randn((1, 3, 112, 112)).type(dtype).to(device)


model = IR_50([112, 112]).eval().type(dtype).to(device)
print('Converting JIT...')
model_jit = torch.jit.trace(model, [data])
print('Converting TRT...')
model_trt = torch2trt(model, [data], fp16_mode=True)


print('PyTorch: %f' % benchmark_throughput(model, [data]))
print('PyTorch (JIT): %f' % benchmark_throughput(model_jit, [data]))
print('TensorRT: %f' % benchmark_throughput(model_trt, [data]))
```

Best,
John

**Comment by xsacha** [comment]
I think the difference is I am not using float16. I'm using a Titan V by the way.
`torch.jit.optimized_execution(True)` <-- this is the default as well so not necessary.

**Comment by xieydd** [comment]
@xsacha  I also meet the problem `[TensorRT] ERROR: INVALID_ARGUMENT: Can not find binding of given name`, when  i build  `trt_net = torch2trt(net, inputs, fp16_mode=fp16,max_workspace_size=1 << 25)` no error. But when i want get the output `preds_trt = trt_net(image)` will cause a error.

**Comment by PistonY** [comment]
@xieydd Do you fix this?Same issue.
