### ISSUE TITLE
[Bug] Model save is broken for Python 2.7

### ISSUE THREAD

**Issue by nhiem2000** [NVIDIA-AI-IOT/torch2trt#87]
With the latest master running Python 2.7, saving TRT model does not work.
```
        # Convert model to TRT
        print("Running torch2trt ...")
        model = torch2trt(model, [input_t])
        print("Saving TRT module ...")
        torch.save(model.state_dict(), 'model_trt.pth')
```
The above works fine with Python 3 installation for torch2trt.
With Python 2.7, the saved model_trt.pth is written out with no warning, but it's only a few hundred bytes.
I am testing with resnet50 and it should be 200 MB+ (and it is with Python 3).

**Comment by jaybdub** [comment]
Hi nhiem,

Thanks for reaching out.  I'll try to see what is causing the issue.

Best,
John

**Comment by jaybdub** [comment]
Hi nhiem,

I think I've discovered the issue, and am working on a fix.

In Python 2 ``bytes`` is an alias for ``str``, which causes different behavior vs. Python3 on this line

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/torch2trt.py#L290

Best,
John

**Comment by jaybdub** [comment]
Should be fixed in

https://github.com/NVIDIA-AI-IOT/torch2trt/pull/93

Which is merged to master.

Please try and let me know if this works for you.

Best,
John

**Comment by nhiem2000** [comment]
Thanks John for the quick fix.  Yes, works for me.
I appreciate your effort to support PY 2.7 even though it will be officially "end of support" by the end of the year.  There are still many PY 2.7 installations around.  If it is possible to support it, it will enable even wider adoption for torch2trt.
