### ISSUE TITLE
Installation Issue: No module named 'torch2trt.flattener'

### ISSUE THREAD

**Issue by braj29** [NVIDIA-AI-IOT/torch2trt#877]
Hi,

I am trying to install torch2trt in a databricks gpu enabled cluster. I am able to first install tensorrt as its required for installation of torch2rt. I use the method mentioned in documentation: clone the torch2rt repo and then do python setup.py install. 

The installation seems successful but when i do: from torch2trt import torch2trt
I get an module not found error: ModuleNotFoundError: No module named 'torch2trt.flattener'

Can you please help ? Thanks!

**Comment by braj29** [comment]
Issue resolved. The way libraries are installed and located are a bit different in Databricks clusters. It worked using using: 
%pip install git+https://github.com/NVIDIA-AI-IOT/torch2trt

**Comment by PhoenixStormJr** [comment]
Here's my solution, I FINALLY figured out in google colab:

Basic install script copied and pasted from the repo:

git clone https://github.com/NVIDIA-AI-IOT/torch2trt
cd torch2trt
python setup.py install
cmake -B build . && cmake --build build --target install && ldconfig

Python code I made:

import sys
sys.path.append('/usr/local/lib/python3.10/dist-packages/torch2trt-0.4.0-py3.10.egg')

**Comment by PhoenixStormJr** [comment]
> %pip install git+https://github.com/NVIDIA-AI-IOT/torch2trt

Returns this error. I have a different solution though:

error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by fighterhit** [comment]
> Here's my solution, I FINALLY figured out in google colab:
> 
> Basic install script copied and pasted from the repo:
> 
> git clone https://github.com/NVIDIA-AI-IOT/torch2trt cd torch2trt python setup.py install cmake -B build . && cmake --build build --target install && ldconfig
> 
> Python code I made:
> 
> import sys sys.path.append('/usr/local/lib/python3.10/dist-packages/torch2trt-0.4.0-py3.10.egg')

Hi @PhoenixStormJr , I follow your steps but I didn't find the `torch2trt-0.4.0-py3.10.egg` in the `/usr/local/lib/python3.10/dist-packages/`.

**Comment by vtyw** [comment]
@fighterhit 

`pip install git+https://github.com/NVIDIA-AI-IOT/torch2trt` didn't work for me, but running `python3 setup.py install` I noted the third to last output line:
```
...
creating dist
creating 'dist/torch2trt-0.4.0-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch2trt-0.4.0-py3.8.egg
creating /usr/lib/python3.8/site-packages/torch2trt-0.4.0-py3.8.egg
Extracting torch2trt-0.4.0-py3.8.egg to /usr/lib/python3.8/site-packages
/usr/lib/python3.8/site-packages/torch2trt-0.4.0-py3.8.egg/torch2trt/dataset.py:61: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(len(self) > 0, 'Cannot create default flattener without input data.')
Adding torch2trt 0.4.0 to easy-install.pth file

Installed /usr/lib/python3.8/site-packages/torch2trt-0.4.0-py3.8.egg
Processing dependencies for torch2trt==0.4.0
Finished processing dependencies for torch2trt==0.4.0
```

So I added that installed path as the first `sys.path` entry before importing, and this got rid of the "torch2trt.flattener" error.

**Comment by ArtemSivtsov** [comment]
As mentioned in another related issue, and it worked for me, it is the solution: https://github.com/NVIDIA-AI-IOT/torch2trt/issues/799#issuecomment-1625724421
