### ISSUE TITLE
AttributeError: 'DataParallel' object has no attribute 'img_size'

### ISSUE THREAD

**Issue by huangshilong911** [NVIDIA-AI-IOT/torch2trt#925]
Hi，I'm using torch2trt for model conversion, and I'm getting the following error when converting .pth to .engine, but previously converting another network's .pth worked fine, is this due to network structure or parameter mismatch or something like that when I'm training the model?

In addition, it should be mentioned that the problematic .pth file was pruned, could it be that the pruning operation resulted in missing or null parameters and hence the error? Since the trained .pth file behaves normally in the inference operation, and the problem occurs only in the model transformation, is it due to the fact that the training model and the model transformation do not have the same stringent requirements for the parameters and other contents in the .pth file?

Traceback (most recent call last):
  File "convert-sam-trt.py", line 90, in <module>
    model_trt = torch2trt(model, [batched_input, multimask_output], fp16_mode=True,strict_type_constraints=True)
  File "/home/jetson/miniconda3/envs/sam0/lib/python3.8/site-packages/torch2trt-0.5.0-py3.8.egg/torch2trt/torch2trt.py", line 558, in torch2trt
    outputs = module(*inputs)
  File "/home/jetson/miniconda3/envs/sam0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jetson/miniconda3/envs/sam0/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jetson/Workspace/aicam/ircamera/segment_anything_kd/modeling/sam.py", line 97, in forward
    input_images = torch.stack([self.preprocess(x["image"]) for x in batched_input], dim=0)
  File "/home/jetson/Workspace/aicam/ircamera/segment_anything_kd/modeling/sam.py", line 97, in <listcomp>
    input_images = torch.stack([self.preprocess(x["image"]) for x in batched_input], dim=0)
  File "/home/jetson/Workspace/aicam/ircamera/segment_anything_kd/modeling/sam.py", line 171, in preprocess
    padh = self.image_encoder.img_size - h
  File "/home/jetson/miniconda3/envs/sam0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1186, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DataParallel' object has no attribute 'img_size'

**Comment by jaybdub** [comment]
Hi @huangshilong911 ,

Thanks for reaching out.

Are you able to share the script you're running to optimize the model with torch2trt?

FYI - We have a repository that optimizes SAM with TensorRT and knowledge distillation here:

https://github.com/NVIDIA-AI-IOT/nanosam


John

**Comment by huangshilong911** [comment]
Thanks john for your reply. Of course, the following is the script that corresponds to the error, which I modified based on the error for insufficient input parameters:

`
import torch
from torch2trt import torch2trt
from torch2trt import TRTModule
from segment_anything_kd.modeling.transformer import TwoWayTransformer
from segment_anything_kd.modeling.mask_decoder import MaskDecoder
from segment_anything_kd.modeling.image_encoder import ImageEncoderViT

device = torch.device("cuda")
print("CUDA visible devices: " + str(torch.cuda.device_count()))
print("CUDA Device Name: " + str(torch.cuda.get_device_name(device)))

# Load the .pth model file
model_path = "/home/jetson/Workspace/aicam/ircamera/vit_b_slim_step2_.pth"
SlimSAM_model = torch.load(model_path)
SlimSAM_model.image_encoder = SlimSAM_model.image_encoder.module
SlimSAM_model.to(device)
SlimSAM_model.eval()
print("model_path:",model_path)

prompt_encoder = model.prompt_encoder
image_encoder = model.image_encoder

# Provide necessary parameters
embed_dim = 384
image_embedding_size = (1024, 1024)
input_image_size = (1024, 1024)
mask_in_chans = 16

# Create a transformer instance, this is just an example, you need to replace it with the transformer model you actually use
transformer_dim = 256  # Set the value of transformer_dim according to your actual needs
num_heads = 8  # Number of heads in your transformer model
mlp_dim = 1536  # mlp_dim in your transformer model
depth = 12  # Number of layers in your transformer model
transformer = TwoWayTransformer(
    depth=depth,
    embedding_dim=transformer_dim,
    num_heads=num_heads,
    mlp_dim=mlp_dim
)

# Create MaskDecoder instance
mask_decoder = MaskDecoder(
    transformer_dim=transformer_dim,
    transformer=transformer,
    num_multimask_outputs=3,  # Example parameter, modify as needed
    iou_head_depth=3,  # Example parameter, modify as needed
    iou_head_hidden_dim=256  # Example parameter, modify as needed
)

# Set the model's state to evaluation mode
model.eval().cuda()

# Move pixel_mean and pixel_std to the GPU
pixel_mean = torch.Tensor([123.675, 116.28, 103.53]).view(-1, 1, 1).cuda()
pixel_std = torch.Tensor([58.395, 57.12, 57.375]).view(-1, 1, 1).cuda()

# Create example data
image = torch.zeros((3, 1024, 1024)).cuda()  # Example image data, assume it's a zero tensor
original_size = (1024, 1024)  # Original size of the image
point_coords = torch.zeros((1, 5, 2)).cuda()  # Example data for point hints, assume it's a zero tensor
point_labels = torch.zeros((1, 5)).cuda()  # Point hint labels, assume it's a zero tensor
boxes = torch.zeros((1, 4)).cuda()  # Example data for box hints, assume it's a zero tensor
mask_inputs = torch.zeros((1, 1, 1024, 1024)).cuda()  # Example data for mask inputs, assume it's a zero tensor

# Create a batched_input list containing example input data
batched_input = [{
    'image': image,
    'original_size': original_size,
    'point_coords': point_coords,
    'point_labels': point_labels,
    'boxes': boxes,
    'mask_inputs': mask_inputs
}]

# Define the multimask_output parameter in the example input
multimask_output = False

# Check if the model contains the image_encoder attribute
if hasattr(model, 'image_encoder'):
    # If the model object contains the image_encoder attribute, use it directly
    image_encoder = model.image_encoder
    # Check if image_encoder contains the img_size attribute
    if hasattr(image_encoder, 'img_size'):
        # If image_encoder contains the img_size attribute, use it
        img_size = image_encoder.img_size
    else:
        # If image_encoder does not contain the img_size attribute, set a default value or perform other processing as needed
        img_size = 1024  # Set the default value to 1024, or handle it according to the actual situation
    # Continue with subsequent operations here
else:
    # If the model object does not contain the image_encoder attribute, obtain default values or perform other processing from the ImageEncoderViT class
    img_size = 1024  # Set the default value to 1024, or handle it according to the actual situation
    # Other operations can be performed here as needed

# Convert to TensorRT model
model_trt = torch2trt(model, [batched_input, multimask_output], fp16_mode=True)

# Save the converted model to the current folder
torch.save(model_trt.state_dict(), "./vit_b_slim_step2_trt.pth")

# Save the converted model as a TensorRT engine
model_trt_engine = TRTModule()
model_trt_engine.load_state_dict(model_trt.state_dict())
torch.save(model_trt_engine.state_dict(), "vit_b_slim_step2_trt.engine")

# @author: Shilong Huang

# This script is used to convert a .pth model of PyTorch to a .engine model optimized by TensorRT.

`Thanks for the reply. Of course, the following is the script that corresponds to the error, which I modified based on the error for insufficient input parameters:

`
import torch
from torch2trt import torch2trt
from torch2trt import TRTModule
from segment_anything_kd.modeling.transformer import TwoWayTransformer
from segment_anything_kd.modeling.mask_decoder import MaskDecoder
from segment_anything_kd.modeling.image_encoder import ImageEncoderViT

device = torch.device("cuda")
print("CUDA visible devices: " + str(torch.cuda.device_count()))
print("CUDA Device Name: " + str(torch.cuda.get_device_name(device)))

# Load the .pth model file
model_path = "/home/jetson/Workspace/aicam/ircamera/vit_b_slim_step2_.pth"
SlimSAM_model = torch.load(model_path)
SlimSAM_model.image_encoder = SlimSAM_model.image_encoder.module
SlimSAM_model.to(device)
SlimSAM_model.eval()
print("model_path:",model_path)

prompt_encoder = model.prompt_encoder
image_encoder = model.image_encoder

# Provide necessary parameters
embed_dim = 384
image_embedding_size = (1024, 1024)
input_image_size = (1024, 1024)
mask_in_chans = 16

# Create a transformer instance, this is just an example, you need to replace it with the transformer model you actually use
transformer_dim = 256  # Set the value of transformer_dim according to your actual needs
num_heads = 8  # Number of heads in your transformer model
mlp_dim = 1536  # mlp_dim in your transformer model
depth = 12  # Number of layers in your transformer model
transformer = TwoWayTransformer(
    depth=depth,
    embedding_dim=transformer_dim,
    num_heads=num_heads,
    mlp_dim=mlp_dim
)

# Create MaskDecoder instance
mask_decoder = MaskDecoder(
    transformer_dim=transformer_dim,
    transformer=transformer,
    num_multimask_outputs=3,  # Example parameter, modify as needed
    iou_head_depth=3,  # Example parameter, modify as needed
    iou_head_hidden_dim=256  # Example parameter, modify as needed
)

# Set the model's state to evaluation mode
model.eval().cuda()

# Move pixel_mean and pixel_std to the GPU
pixel_mean = torch.Tensor([123.675, 116.28, 103.53]).view(-1, 1, 1).cuda()
pixel_std = torch.Tensor([58.395, 57.12, 57.375]).view(-1, 1, 1).cuda()

# Create example data
image = torch.zeros((3, 1024, 1024)).cuda()  # Example image data, assume it's a zero tensor
original_size = (1024, 1024)  # Original size of the image
point_coords = torch.zeros((1, 5, 2)).cuda()  # Example data for point hints, assume it's a zero tensor
point_labels = torch.zeros((1, 5)).cuda()  # Point hint labels, assume it's a zero tensor
boxes = torch.zeros((1, 4)).cuda()  # Example data for box hints, assume it's a zero tensor
mask_inputs = torch.zeros((1, 1, 1024, 1024)).cuda()  # Example data for mask inputs, assume it's a zero tensor

# Create a batched_input list containing example input data
batched_input = [{
    'image': image,
    'original_size': original_size,
    'point_coords': point_coords,
    'point_labels': point_labels,
    'boxes': boxes,
    'mask_inputs': mask_inputs
}]

# Define the multimask_output parameter in the example input
multimask_output = False

# Check if the model contains the image_encoder attribute
if hasattr(model, 'image_encoder'):
    # If the model object contains the image_encoder attribute, use it directly
    image_encoder = model.image_encoder
    # Check if image_encoder contains the img_size attribute
    if hasattr(image_encoder, 'img_size'):
        # If image_encoder contains the img_size attribute, use it
        img_size = image_encoder.img_size
    else:
        # If image_encoder does not contain the img_size attribute, set a default value or perform other processing as needed
        img_size = 1024  # Set the default value to 1024, or handle it according to the actual situation
    # Continue with subsequent operations here
else:
    # If the model object does not contain the image_encoder attribute, obtain default values or perform other processing from the ImageEncoderViT class
    img_size = 1024  # Set the default value to 1024, or handle it according to the actual situation
    # Other operations can be performed here as needed

# Convert to TensorRT model
model_trt = torch2trt(model, [batched_input, multimask_output], fp16_mode=True)

# Save the converted model to the current folder
torch.save(model_trt.state_dict(), "./vit_b_slim_step2_trt.pth")

# Save the converted model as a TensorRT engine
model_trt_engine = TRTModule()
model_trt_engine.load_state_dict(model_trt.state_dict())
torch.save(model_trt_engine.state_dict(), "vit_b_slim_step2_trt.engine")

# @author: Shilong Huang

# This script is used to convert a .pth model of PyTorch to a .engine model optimized by TensorRT.

`

**Comment by huangshilong911** [comment]
Thanks john for your reply. The problem was solved by converting the model from DataParallel to normal format：

``
SlimSAM_model = torch.load(<model_path>)
SlimSAM_model.image_encoder = SlimSAM_model.image_encoder.module
``

**Comment by huangshilong911** [comment]
BTW, here is the original conversion script I created based on the code from the author of slim_sam (the original version of the code in the previous reply), which will show the lack of input parameters error:
`
import torch
from torch2trt import torch2trt
from torch2trt import TRTModule

device = torch.device("cuda")
print("CUDA visible devices: " + str(torch.cuda.device_count()))
print("CUDA Device Name: " + str(torch.cuda.get_device_name(device)))

x = torch.randn(1, 3, 1024, 1024).to(device)

model_path = "/home/jetson/Workspace/aicam/ircamera/vit_b_slim_step2_.pth"
SlimSAM_model = torch.load(model_path)
SlimSAM_model.image_encoder = SlimSAM_model.image_encoder.module
SlimSAM_model.to(device)
SlimSAM_model.eval()
print("model_path:",model_path)

def forward(self, x):
    x = self.patch_embed(x)
    if self.pos_embed is not None:
        x = x + self.pos_embed
    for blk in self.blocks:
        x, qkv_emb, mid_emb, x_emb = blk(x)
    x = self.neck(x.permute(0, 3, 1, 2))
    return x

import types
funcType = types.MethodType
SlimSAM_model.image_encoder.forward = funcType(forward, SlimSAM_model.image_encoder)

model_trt = torch2trt(SlimSAM_model, [x], fp16_mode=True)

torch.save(model_trt.state_dict(), "./vit_b_slim_step2_trt.pth")

model_trt_engine = TRTModule()
model_trt_engine.load_state_dict(model_trt.state_dict())
torch.save(model_trt_engine.state_dict(), "vit_b_slim_step2_trt.engine")

`

The error is reported as follows:

CUDA visible devices: 1
CUDA Device Name: Orin
model_path: /home/jetson/Workspace/aicam/ircamera/vit_b_slim_step2_.pth
Traceback (most recent call last):
  File "convert-sam-trt.py", line 35, in <module>
    model_trt = torch2trt(SlimSAM_model, [x], fp16_mode=True)
  File "/home/jetson/miniconda3/envs/sam0/lib/python3.8/site-packages/torch2trt-0.5.0-py3.8.egg/torch2trt/torch2trt.py", line 558, in torch2trt
    outputs = module(*inputs)
  File "/home/jetson/miniconda3/envs/sam0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jetson/miniconda3/envs/sam0/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'multimask_output'
