### ISSUE TITLE
 ONNX export mode is set to TrainingMode.EVAL, but operator 'instance_norm' is set to train=True

### ISSUE THREAD

**Issue by edwardnguyen1705** [NVIDIA-AI-IOT/torch2trt#935]
Dear @jaybdub ,

I have tried [torch2trt](https://github.com/NVIDIA-AI-IOT/torch2trt) to convert an [OSNet-AIN](https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/osnet_ain.py) model based on [fast-reid](https://github.com/JDAI-CV/fast-reid/blob/master/tools/deploy/onnx_export.py), and I observe the following `WARNING`

```bash
UserWarning: ONNX export mode is set to TrainingMode.EVAL, but operator 'instance_norm' is set to train=True. Exporting with train=True.
```

 It seems that the warning could lead to the difference between outputs of pytorch and tensorrt are quite different on a person reid dataset.  I attach the scripts to produce the results.
[torch2trt.zip](https://github.com/user-attachments/files/15881913/torch2trt.zip)
![delta_y](https://github.com/NVIDIA-AI-IOT/torch2trt/assets/7928673/3e5dc209-f35c-4793-9181-c9be1f419bc7)

Have encountered this issue and figured out a way to tackle this?
Thanks for your time.

**Comment by jayong-sv** [comment]
@edwardnguyen1705 I encountered the same error. Did you solve it?

**Comment by edwardnguyen1705** [comment]
Hi @jayong-sv ,
I made a mistake, actually the warning does not affect the result.
